- eligibility_verification/core/templates/core/includes/form.html
- eligibility_verification/eligibility/api.py
- eligibility_verification/eligibility/forms.py
- eligibility_verification/eligibility/views.py
- eligibility_verification/static/css/styles.css
The API supports HTTP 400 responses with two types of field errors:
* `missing`
* `invalid`
The former should never happen since our form requires all fields. The latter is defined and validated by the Verification Server, so this gives the Server a way to acknowledge an invalid field without divulging specifics.
Messages for each class of error are hard-coded in the form for now.
> Display form field errors from API server

- .devcontainer.json
- Dockerfile.dev
Wait to `pre-commit install` until dev container attaches to local source.
At Docker build time, the git repository is not available!
> Fix dev container pre-commit installation

- benefits/locale/es/LC_MESSAGES/django.po
Several changes to language including
- using "transporte público"
- making bank card language simpler and clearer
- making age requirements clearer
- updating spelling and accents that were wrong
@thekaveman one question - i feel like some of the language from the "Payment Options" ("Opciones de Pago") page is missing but it's hard for me to tell. Is that in another file?
> Updated Spanish translations based on feedback

- .aws/ecs-task-definition.json
- .env.sample
- benefits/__init__.py
- benefits/core/analytics.py
- benefits/core/context_processors.py
- benefits/core/middleware.py
- benefits/core/session.py
- benefits/core/templates/core/base.html
- benefits/core/templates/core/includes/analytics.html
- benefits/core/views.py
- benefits/discounts/templates/discounts/index.html
- benefits/discounts/views.py
- benefits/eligibility/analytics.py
- benefits/eligibility/api.py
- benefits/eligibility/views.py
- benefits/settings.py
- docker-compose.yml
Use Amplitude to track key events through the app flow while maintaining user anonymity. The [javascript SDK](https://developers.amplitude.com/docs/javascript) is used for a handful of client-side events, but the bulk of the logging is done server-side via the [HTTP API V2](https://developers.amplitude.com/docs/http-api-v2).
* `user_id` and `device_id` are random UUIDs generated on the server per-session
* event for important lifecycle pages
* events for begin/end of eligibility process
* events for begin/end of enrollment process
* event for language change
* events for external link clicks
Following guidance from Amplitude's [Data Taxonomy Playbook](https://help.amplitude.com/hc/en-us/articles/115000465251-Data-Taxonomy-Playbook)
> Instrument with Amplitude

- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- benefits/core/session.py
[Bandit](https://bandit.readthedocs.io/en/latest/) looks for common security issues by analyzing python code.
Exclude the test server directory since this is not part of any production deployment, and is meant for local testing only. The exclusion is done via pre-commit's `exclude` key, since the action runs pre-commit with `--all-files` and Bandit's exclude doesn't take effect when given an explicit list of files to check. See https://github.com/PyCQA/bandit/issues/499 and https://stackoverflow.com/a/61046953
> Pre-commit hook runs bandit

- benefits/eligibility/api.py
Interpreting the HTTP response as JSON is incorrect; the response body comes back as the text of the encrypted, encoded JWT.
> Fix API response parsing

- benefits/core/migrations/0001_initial.py
- benefits/core/models.py
- benefits/core/viewmodels.py
- benefits/core/views.py
- benefits/eligibility/views.py
- benefits/enrollment/views.py
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
- benefits/static/css/styles.css
- data/client.json
Rename the unused `logo_url` field to `help_url`, meant to point to the agency's online resources for their benefits program.
Display the a link to the agency's help URL along with phone link wherever a phone link was displayed before.
Closes #58.
Also introduces explicit primary key `id` fields on each model, to suppress newer Django warnings related to a changed default. The explicit fields implement what was implicit and default in versions of Django prior to the new warning.
> Agency info URLs

- .aws/ecs-task-definition.json
- benefits/core/templates/core/includes/button.html
- benefits/core/viewmodels.py
Need to sign in to Docker Hub with credentials because we're being rate limited pulling `aws/aws-cli` from a public AWS IP address.  
Quick fix on the `agency.info_url` to allow `target=_blank`.
> Deploy fixes

- .aws/ecs-task.json
- .env.sample
- .github/workflows/ecs-deploy.yml
Getting ready for a dev, test, and prod deployment. 
Remove environment-specific info from ECS task template, add a step that uses `sed` to fill in with environment secrets.
> Refactor ECS task and workflow for environments

- .aws/ecs-task.json
- .env.sample
- .github/workflows/ecs-deploy-dev.yml
- .gitignore
- docker-compose.yml
Major simplification over secrets, store an .env file in S3 and reference it in the ECS task with the `environmentFiles` property. 
GitHub Action secret points to bucket per deploy environment, with replacement in the ECS task template.
> Manage ECS container environment with environmentFiles

- .aws/ecs-task.json
AWS is complaining about the file, maybe because it didn't have a full name
> Naming env with explicit .env extension

- .github/workflows/mkdocs.yml
- Dockerfile.dev
- docs/requirements.txt
`mhausenblas/mkdocs-deploy-gh-pages` pip installs the requirements.txt from the root of the repo unless overridden with another path.
There is currently no way to opt-out; this was under discussion in Dec 2020: https://github.com/mhausenblas/mkdocs-deploy-gh-pages/pull/55
This is problem, we don't want to install requirements from benefits for mkdocs, so provide the REQUIREMENTS env with our mkdocs dependencies.
> Fix the mkdocs action

- Dockerfile
- Dockerfile.dev
- docs/README.md
- docs/requirements.txt
Fix an issue with the `docs` Compose service by splitting `ENTRYPOINT` and `CMD` in the upstream Docker image.
Also pin to `mkdocs==v1.1.2` to address an issue with newly released v1.2.0.
> Fixing mkdocs build/serve

- benefits/core/models.py
- benefits/core/session.py
- benefits/eligibility/api.py
- benefits/eligibility/views.py
- benefits/enrollment/views.py
The central change in this PR is to adapt get/set of eligibility information from/to session to use the `EligibilityType.id` property rather than `name`. Since this object carries the value sent in the eligibility phase and also the group identifier for the enrollment phase, we may have multiple types with the same name pointing to different enrollment groups.
The current logic relying on `name` causes errors when there are duplicates because we cannot determine which `EligibilityType` was meant. 
A future todo could be to refactor the models to separate eligibility name and benefit group identifier.
> Refactor handling of eligibility types

- .aws/ecs-task.json
- .github/workflows/ecs-deploy-dev.yml
Even with Docker Hub API credentials, we're experiencing intermittent timeouts and other errors trying to bring in the official 
`aws-cli` Docker image. We use this at ECS service startup to pull in configuration data from S3.
This PR refactors the ECS templates to instead pull from a local (ECR, not Docker Hub) version of the `aws-cli` image that we'll tag and maintain. The current assumption is that this local `aws-cli` image resides in the same ECR registry as where we deploy this application image into.
> Use local copy of aws-cli image

- mkdocs.yml
A media query selects the initial preferred mode from system settings.
See: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle
> Enable light/dark mode toggle for docs site

- benefits/settings.py
- localhost/.env.sample
The problem was only seen when `DEBUG=False`, as settings tried to load the allowed hosts from the environment.
Since the value in the `.env` file was quoted, the quotes were taken as part of the value when read into settings.
`"host.com"` is not the same as `host.com`, and so the app failed to load!
> Fix ALLOWED_HOSTS setting

- benefits/enrollment/api.py
The Payment Processor API is returning `{"customer_ref": None}` for some customers. Contrary to their API documentation, `customer_ref` is not a required value when we send a payload back in the customer update `PATCH` request.
Since we don't actually use/need this value, and there is no reason for the Benefits app to generate one for a customer, this PR removes handling of the value entirely.
This fixes a bug when the value was `None` but the customer was already marked as registered in the Payment processor system.
> Payment processor API fix

- benefits/core/middleware.py
- benefits/core/urls.py
- benefits/core/views.py
- benefits/settings.py
Prior to this change, ELB healthcheck requests were failing with 400 as the HOST_HEADER was the ELB node's (internal) IP address.
This change moves the healthcheck to a middleware placed before the HOST_HEADER verification (in `django.middleware.common.CommonMiddleware`), so healthcheck requests always pass.
Based on https://stackoverflow.com/a/64623669.
Closes #105.
> Move healthcheck to middleware

- .github/workflows/mkdocs.yml
closes #109 
1. Fork this repository
2. As an extra precaution, delete all unrelated GitHub Action workflows. To make sure unnecessary deploys to Production were absolutely impossible, I deleted the `.github/workflows/ecs-deploy.dev.yml` and `.github/workflows/ecs-deploy-test.yml' files.
3. Merge the PR I am testing into `dev`. I merged `109-docs-action-config`.
4. Click **Actions** tab. Click the button to turn on Actions for this repository. (Sidenote: It's great that GitHub turns Actions off by default on repositories that are forked.)
5. Create new PRs to test the workflow filter: I first created a PR that changes a `/localhost/` file. Then, I created a PR that changes a `/docs/` file. 
6. Merge one PR at a time and look at the **Actions** tab to confirm the desired result.
After the …
> Workflow: Only deploy Docs site when docs files change

- .github/workflows/ecs-deploy-dev.yml
close #111 
adds `paths` filter so this dev deploy workflow only runs if at least one file in the explicitly specified list is changed.
Follow the instructions from #109 
https://github.com/machikoyasuda/benefits/actions
I made 2 PRs - one PR that changes app code (a i18n copy file) and another that changes a `/docs/` file. 
Only the PR that made changes to app code triggered the Deploy Dev workflow:
> Workflow: Only deploy Dev if dev code has changed

- .devcontainer.json
- .vscode/launch.json
- localhost/Dockerfile.dev
- localhost/docker-compose.yml
Maintain the `F5`-to-start sequence, but allow for stop/restart unlike the attach type. We no longer need to expose a debugger port.
The compose service definition was simplified to decouple the app and devcontainer startup, using the `sleep infinity` command ensures the devcontainer stays active if the app/debugger crash.
Since VS Code handles the debugger interaction, we don't need to explicitly install `debugpy`.
1. Rebuild and Reopen the devcontainer
2. Add a breakpoint to `/healthcheck`, Hit `F5` to launch the debugger, navigate to `/healthcheck`, hit breakpoint
3. Observe you can **stop** the debugger, then **restart** with `F5`
> Use launch type debugger

- .pre-commit-config.yaml
Closes #165 
As noted by @machikoyasuda in cal-itp/eligibility-server#47, you will see a warning due to this `rev`, but 
> we decided it's okay, because the Dev Container always will install only once.
> Pin conventional-pre-commit to v1

- Dockerfile
- bin/init.sh
- bin/start.sh
- localhost/Dockerfile.dev
Closes #171 
- Added lines to `Dockerfile.dev` to use the `calitp` user so that the npm dependencies are installed using that user rather than root
- Added lines in `Dockerfile` to make the Python packages be installed using `calitp` as well
> Fix Linux devcontainer issue from file permissions

- Dockerfile
Related to #171 
The [deploy to dev](https://github.com/cal-itp/benefits/actions/runs/1419184744) failed because the `benefits/locale/**` directories are not writable by the `calitp` user.
[Changes](https://github.com/cal-itp/benefits/pull/172/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L44) from #172 removed the explicit ownership-change on `benefits/locale` and moved the `USER $USER` switch to occur before we `COPY` the source files. We thought this would make `calitp` the owner of the app files/directories, but it turns out [COPY commands are run as root](https://stackoverflow.com/a/44766666/453168).
We actually decided it is better to have `root` be the owner, so in this pull request we just change the permissions for `benefits/locale/**`.
> Make sure locale directory is writable by calitp user

- .aws/ecs-task.json
- .pre-commit-config.yaml
- .vscode/launch.json
- .vscode/settings.json
- benefits/static/css/styles.css
- localhost/data/client.json
- tests/e2e/cypress.json
- tests/e2e/cypress/integration/eligibility.spec.js
- tests/e2e/cypress/integration/help.spec.js
- tests/e2e/cypress/integration/index.spec.js
- tests/e2e/cypress/integration/payment-options.spec.js
- tests/e2e/cypress/integration/spanish.spec.js
closes #184 
- Add prettier to the pre-commit list of linters
- Configures prettier to lint .js, .json, .css files only
- Lints all .css, .js and .json files
- Add Prettier VSCode extension
- We decided to lint CSS, JS, JSON for now. HTML will require more careful testing, so we're not adding HTML yet. Created a ticket in backlog.
> Add JavaScript/JSON/CSS linting

- benefits/core/middleware.py
- benefits/enrollment/views.py
This fixes #186.
Add a new middleware definition similar to `AgencySessionRequired` that raises an exception when the `session` does not contain a verified eligibility.
Apply this middleware to the enrollment views instead of `AgencySessionRequired` (the new middleware effectively requires an agency in the session as well).
We already had the [`session.eligible()`](https://github.com/cal-itp/benefits/blob/dev/benefits/core/session.py#L92) helper for doing this check. This is being used in routing the [`/eligibility/confirm` form response](https://github.com/cal-itp/benefits/blob/dev/benefits/eligibility/views.py#L66). This PR builds on that helper to guard the `/enrollment` phase as well.
Additionally, UI test(s) would normally accompany this fix to ensure we don't introduce a regression …
> Require confirmed eligibility for enrollment

- benefits/core/templates/core/base.html
close #182 
- Upgrade jQuery from 3.4.1 to 3.6.0
- Remove jQuery Migrate plugin
- 3.4: https://blog.jquery.com/2019/04/10/jquery-3-4-0-released/
- 3.5: https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/
- 3.6: https://blog.jquery.com/2021/03/02/jquery-3-6-0-released/
> Upgrade jQuery from 3.4.1 to 3.6.0

- benefits/settings.py
- requirements.txt
Closes #203.
The Content Security Policy blocks assets from loading unless configured correctly. After `git checkout` the branch, load the app in your browser and run through the flow - you should see no errors in loading scripts, styles, fonts, etc. and all images, styles, etc. should be applied and visible.
To break the Policy and see what happens, comment out everything after the [`CSP_DEFAULT_SRC` directive in `settings.py`](https://github.com/cal-itp/benefits/blob/feat/content-security-policy/benefits/settings.py#L199). Then load the app locally and check the browser console:
> Implement Content Security Policy

- benefits/settings.py
Fixes #204 
[`SECURE_BROWSER_XSS_FILTER`](https://docs.djangoproject.com/en/3.2/ref/settings/#secure-browser-xss-filter) set to `True` will achieve the desired response header. That setting comes from [`SecurityMiddleware`](https://docs.djangoproject.com/en/3.2/ref/middleware/#x-xss-protection) which we are using in [`settings.py`](https://github.com/cal-itp/benefits/blob/dev/benefits/settings.py#L46), so all we need to do is set it.
- Launch the benefits app
- Open dev console (F12) and use the Network tab to ensure the response header is as expected (`X-XSS-Protection: 1; mode=block`)
> Configure X-XSS-Protection

- .github/lighthouserc.json
- .github/workflows/tests-ui.yml
closes #167
- Add a step to the existing UI Test GitHub Action that runs `Lighthouse` testing on the homepage and the help page
- Run A11y and Best Practices, on Mobile
- The test will show a "Warn" when the overall Best Practices score is under 90%
- The test will show a blocking "Error" when the overall A11y score is under 100%
- The test results will be uploaded so they can be viewed easily, like this: https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1637284608781-6224.report.html and the link can be found in the Action logs https://github.com/cal-itp/benefits/runs/4259113826?check_suite_focus=true#step:7:47 (The report only lasts for 60 days)
- The tests take about 30 seconds
- What Lighthouse's a11y test checks: …
> Add Lighthouse a11y testing to Test UI workflow

- benefits/settings.py
Following up to #211.
Chrome understands the `script-src-elem` directive for JavaScript and `style-src-elem` for CSS. Firefox and Safari don't support either of these.
This PR falls back to the `script-src` and `style-src` directives for wider browser support.
More info: 
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src-elem
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src-elem
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src
> Fix browser support in Content Security Policy

- benefits/core/templates/core/base.html
#220 
This is a small fix that came from a Lighthouse test.
- Replace https://california.azureedge.net/cdt/statetemplate/6.0.2/css/cagov.core.css with https://california.azureedge.net/cdt/statetemplate/6.0.2/css/cagov.core.min.css
- Replace https://california.azureedge.net/cdt/statetemplate/6.0.2/css/colorscheme-oceanside.css with https://california.azureedge.net/cdt/statetemplate/6.0.2/css/colorscheme-oceanside.min.css
- Replace https://california.azureedge.net/cdt/statetemplate/6.0.2/js/cagov.core.js with https://california.azureedge.net/cdt/statetemplate/6.0.2/js/cagov.core.min.js
I found the links here:
https://template.webstandards.ca.gov/cdn.html
> Use minified JS and CSS files

- benefits/core/templates/core/base.html
- benefits/core/templates/core/help.html
- benefits/core/templates/core/includes/button.html
- benefits/core/viewmodels.py
closes #221 
- Add `rel="noopener noreferrer"` to external links in 3 places: GitHub link, Privacy Policy link and transit agency link
- Adds `rel` as a parameter to the `Button` class, hardcodes `rel` value into `agency_contact_links` method, and adds `rel` to button template
- Removed extra space between `GitHub` and `.`
vs.
From 
https://web.dev/external-anchors-use-rel-noopener/
- Run the app and click all the links
- Links should open in a new tab, as usual
- Check the Lighthouse test result for `Best Practices` for the Help page and the Home Page. The Best Practices score improves to 100%. Currently, it's at 93% (https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1637367932497-10685.report.html).
New results: …
> Use`noopener noreferrer` for external links

- benefits/core/templates/core/base.html
close #224 
- Adds a meta description, for SEO
- It's important b/c https://web.dev/meta-description/
Currently using copy from the Help page. If and when specific copy for this description is written, we can update the copy.
> Add meta description

- benefits/core/urls.py
- benefits/settings.py
* Attempt to process agency paths last, avoiding errors in processing e.g. `/help`
* Only add `DebugSession` middleware when in debug mode
> Fix some logging and error noise

- benefits/core/viewmodels.py
- benefits/enrollment/templates/enrollment/index.html
- benefits/enrollment/urls.py
- benefits/enrollment/views.py
- tests/e2e/cypress/specs/integration/eligibility.spec.js
When a user successfully verifies their eligibility, we redirect the user into the `enrollment` flow. The first step of that flow (on the server) is to acquire an API access token for the Payment Processor's API.
This presents a number of problems, such as that documented in #178 - but also e.g. we lose the ability to give the user a more nuanced error message if their eligibility _was verified_ but the initial connection to the Payment Processor / API token failed.
This PR delays the request for the API access token until the page has loaded in the user's browser. By introducing a simple `JsonResponse` endpoint and moving the existing code around, it was a minor change to `$.get()` the token async via JavaScript rather than in the Django request.
> Delay acquisition of Enrollment access token

- benefits/core/templates/core/base.html
- benefits/static/css/styles.css
closes part of #183
- Add 2 css classes from [oceanside](https://github.com/Office-of-Digital-Innovation/California-State-Template/blob/master/css/colorscheme-oceanside.css) into benefits/static/css/styles.css
- Remove oceanside.css call from base template
- Fewer CSS files to load ==> Lighter page weight and faster web performance
- I manually visually compared all the pages on the site, in both Desktop and Mobile, side by side with this branch and production:
- Check focus, hover states, check `Skip to Main Content` button visually
This PR:
> Refactor CSS: Reduce number of css file calls

- benefits/core/templates/core/base.html
- benefits/settings.py
closes part of #183
- Remove the California state JS template entirely.
- I _believe_ this was only used to render the up arrow that appears once you scroll. The Benefits app does not need this.
- Go through the app in desktop and mobile and look for any regressions
Shows marked improvement in speed index and first contentful paint from previous PR https://github.com/cal-itp/benefits/pull/234
- Help page
- Home page - The image slows it down
> Refactor JS

- .github/workflows/tests-ui.yml
Separated this out from #238 because it's really unrelated to that PR's intent.
- GitHub Actions: Add a `workflow_dispatch` manual override option to the UI test action
> Fix: Add workflow_dispatch to ui test

- .github/workflows/tests-ui.yml
Since the `tests-ui` job is used as a PR merge check, we need a PR-related event to trigger the check --> `workflow_dispatch` doesn't trigger the check. 
See https://github.community/t/workflow-dispatch-does-not-update-commit-status/125981/2 for more.
This PR changes the workflow so the the job runs on all PRs to the deploy branches (`dev`, `test`, `prod`)
> Run tests-ui on all paths on deploy branches

- .github/workflows/codeql.yml
New version of #239
> https://codeql.github.com/docs/codeql-overview/about-codeql/
>
>> CodeQL is the analysis engine used by developers to automate security checks, and by security researchers to perform variant analysis.
>
> Runs on:
>
> * PR to `dev`
> * Push to `dev`, `test`, `prod`
> * Weekly on Saturdays
>
> See the scan results under the *Security* tab of this repo: https://github.com/cal-itp/benefits/security/code-scanning
Also see the *Checks* tab of a PR, under *Code scanning results* > *CodeQL* to see the results for a given PR.
For example, for this PR: https://github.com/cal-itp/benefits/pull/242/checks?check_run_id=4413708654
> CI: CodeQL scanning workflow

- benefits/settings.py
- nginx.conf
Introduce caching at the `nginx` layer for static file requests (images, CSS, JS, etc.)
Use a static file storage mechanism in Django that silently rewrites file names with a hash of their contents, allowing long cache times and easy cache busting when the contents changes.
See the new headers for `/static`/ files:
**NOTE:** when running locally, to get `nginx` to run, you have to have to `docker compose up client` _outside_ the devcontainer. `F5` inside the devcontainer uses the Django debug server.
> Cache headers for static files

- .aws/ecs-task.json
`aws s3 cp` doesn't recognize glob/unix file patterns in the path, they can be used with `--exclude`/`--include` flags though.
https://docs.aws.amazon.com/cli/latest/reference/s3/index.html#use-of-exclude-and-include-filters
Pattern support is needed to copy all of the new separated [fixture files](https://github.com/cal-itp/benefits/tree/dev/fixtures).
`CONFIG_FILE` is set in the [.env](https://github.com/cal-itp/benefits/blob/dev/.devcontainer/.env.sample) file inside the same `AWS_BUCKET`.
> Fix: AWS copy files matching CONFIG_FILE pattern

- .github/workflows/codeql.yml
Push directly to deploy branches blocked with protection rules, check runs on PRs only.
> CI: run CodeQL on PRs to deploy branches

- bin/init.sh
List the `DJANGO_INIT_PATH` variable then use `xargs` to call Django's `loaddata` with each result.
> Fix: list init path before loading

- benefits/enrollment/api.py
The 500 response is used to indicate a duplicate group enrollment with the payment processor. 
In order to determine if a 500 is a a duplicate registration or a "real" server error, we need to ensure the `customer_id` exists in the error details coming back with the 500.
> Fix: more error handling for duplicate enrollment

- benefits/enrollment/api.py
When a customer's card has already been seen by the payment processor (e.g. they have tapped on a device), before registering through `benefits`, the payment processor considers the customer account as _unregistered_ (e.g. unregistered for any discounts) - although the account does exists.
Our current implementation handled this case, by registering any unregistered customers.
However, there is a mismatch in some of the API docs and what happens during real API calls. It turns out that when updating a customer, we need to include the customer's ID in the request payload (in addition to the URL fragment) in order to get it back in the response payload.
Instead of sending `{"is_registered: "true"}` we need to send `{"is_registered: "true", "id": "UUID"}`.
This PR adds the `id` field to …
> Fix: enrollment flow for existing customers

- .github/workflows/check-api.yml
Fixes #252 
This workflow will alert us if our access to the payment processor is broken. There are two ways it can be triggered:
- via the configured schedule (set to run at 12:00 UTC)
- manually through the Actions tab
Secrets need to be configured for this to work. For the cert-file secrets, the expectation is that they are base64-encoded strings.
The general idea is:
- decode the strings back into files
- build up the `curl` command to call the API endpoint, with the `-i` flag to include the HTTP header in the output
- check that the response code is what we expect
Note that we are **not** printing the payload or anything about the certs/endpoint to the console.
I got very familiar with the GitHub Actions documentation while working on this workflow. 😂 Here are some notes about …
> Add workflow to monitor API

- .github/workflows/check-api.yml
It is not necessary to base64-encode the cert files as a single string.
The workflow will now read the secret, which is expected to be simply the file contents, newlines and all).
> Simplify API check's usage of cert files

- benefits/core/analytics.py
This will allow for more kinds of event segmentation by transit agency when the app is eventually configured for multiple agencies.
`provider_name` as an event prop doesn't make as much sense as it is largely independent from the type of event and more down to the (type of) user - however segmentation of events by `provider_name` may prove useful so this PR leaves the prop there.
More info: https://help.amplitude.com/hc/en-us/articles/115002380567-User-properties-and-event-properties
> Feat: Add provider_name to analytics user props

- benefits/eligibility/api.py
Fixes #279 
I modified my local `eligibility-server` instance to return a 403 for the `/verify` endpoint. Then, I modified the `benefits` compose.yml file so that it would point at `eligibility_server:latest` for the `server` service. I rebuilt all the images and then launched `benefits` with the debugger.
My hard-coded 403 was returned and raised an `ApiError` as expected.
Screenshots:
> Tokenize response only for expected statuses

- requirements.txt
closes #284 
- Reverts work from #256 and #276 
- Reverts to 3.2.10 because of outstanding bug #283 
- Tested locally on 3.2.10
> fix(deps): revert django from 4.0.1 to 3.2.10

- benefits/core/templates/core/base.html
- benefits/core/templates/core/includes/alert.html
- benefits/eligibility/views.py
- benefits/settings.py
- Adds `alert` template, adds `alert` conditional rendering in `base` template. The alert is red with a close button. This requires `https://california.azureedge.net/cdt/statetemplate/6.0.2/js/cagov.core.js`
- Adds an alert that opens when `messages.error()` is called in a view template.
This is PR _into_ the main `feat/recaptcha` branch.
> Feature: Add Alert for Recaptcha failure

- benefits/core/middleware.py
Note: This PR merges into the main `feat/rate-limit` PR.
- Adds code to the `RateLimit` middleware mixin method that uses `viewmodels.ErrorPage` to return a 400 bad request error and this page
Adds a small feature where: When a user reaches the rate limit on the eligibility confirmation page (by exceeding the number of accepted requests per minute), the user will be taken to this error page with a `Return home` button. The `Return home` button will take them back to the `/eligibility/` page
> Feat: Show error page when rate limit is reached

- benefits/core/session.py
Instead of every time the lesser session variables are reset.
> Fix: Reset rate limit only for new sessions

- benefits/core/migrations/0001_initial.py
- benefits/core/models.py
- fixtures/02_eligibilityverifier.json
Closes #208.
Note this PR only modifies the `EligiblityVerifier` model to add the fields that capture the validation settings. In the follow-up for #324, the form will be updated to use these new settings for validation.
> Feat: Add validation fields to verifier model

- .gitignore
- docs/getting-started/testing.md
- tests/cypress/package-lock.json
- tests/cypress/specs/ui/eligibility.spec.js
closes #339 
- Modifies existing UI specs for Eligibility Confirmation page, by having the user select `DEFtl` Transit (which is set to be the single-verifier path)
- Adds UI specs for the Verifier selection page, testing for:
After a user selects `ABC` Transit, a multiple verifier path:
1. Whether a user can click `Continue` to get to the Verifier selection page
2. Whether a user sees 2 radio buttons, with `MST Courtesy Cardholder` and `Senior Discount Program`*
3. Whether a user gets a validation message if they click `Continue` without choosing a radio button**
4. Whether a user can click `Continue` to get to the Eligibility start page, after selecting a radio button
- Modify the existing Eligibilty confirmation page spec to:
1. Add the actions of selecting a radio button (`Senior …
> Tests: Update UI tests for multiple verifier flow

- benefits/eligibility/views.py
Fixes #379.
A couple of small changes to the `eligibility/views.py`, `unverified()` view function:
1. Require a verifier in the session - using the new `VerifierSessionRequired` middleware from #333 
2. Get the verifier from session before creating the `Page` viewmodel
3. Translate `msgid` from the verifier for the `Page` viewmodel
Here's the result of failing the eligibility check for "ABC" with "Senior Discount":
And for "ABC" with "Courtesy Cards":
In order to get a server to run that you can test (and fail) an eligibility verification request against, modify `.devcontainer/compose.yml` entry for `server` to use a different image:
```diff
server:
-   image: ghcr.io/cal-itp/eligibility-server:main
+   image: ghcr.io/cal-itp/eligibility-server@sha256:337d5b2beb1e458980be49a778efd4a47f8daa …
```
> Fix: use verifier's translation strings on eligibility unverified page

- .gitattributes
This code is run in a Linux environment, and expects LF line-endings. The `.gitattributes` file forces all cloners to use LF regardless of their OS.
See https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings
> Fix: gitattributes to force LF

- .github/CODEOWNERS
Adds a `CODEOWNERS` file, which defaults all reviews to the @cal-itp/benefits-admin team.
Read more about this file: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
> Feat: add CODEOWNERS file

- .devcontainer/.env.sample
- .devcontainer/compose.yml
For the upcoming SSO integration, we need to be able to pin a static localhost port for testing with the dev environment.
But only for the app container and devcontainer, the others can still be dynamic.
This only affects the _host machine_ port and only at development time; internally in the containers, the ports are unaffected.
> Feat: re-introduce static Docker port config

- benefits/eligibility/templates/eligibility/start.html
- benefits/eligibility/views.py
This closes #374.
This PR simply creates the template and makes the view use it. This will be the basis of most of the other work for the Login.gov milestone, as this is the key page in the flow that needs to adapt to the new requirements.
> Feat: create template for eligibility start page

- benefits/eligibility/templates/eligibility/start.html
Quick follow on to #391, these are the blocks that are used in this template. Easier to refactor them now as a basis for other work on this page.
> Fix: explicit blocks in start template

- benefits/core/session.py
closes #370 
- Adds new logs messages: `Get session auth`, `Update session auth`
- Auth key/value pair now in DEBUG_MODE: `"auth": "None"`
> Track sign in status in user session

- benefits/core/templates/core/base.html
Makes it safer to rely on a third-party CDN.
https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity
Fixes https://github.com/cal-itp/benefits/security/code-scanning/474.
> Fix: add SRI attributes for jQuery

- .devcontainer/compose.yml
Unclear what changed to make the previous configuration stop working on my machine (something in Docker, perhaps?), causing this error:
```
$ docker compose up dev
[+] Running 2/2
⠿ Container benefits-server-1  Created                                                       0.0s
⠿ Container benefits-dev-1     Recreated                                                     0.2s
Attaching to benefits-dev-1
Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "-c": executable file not found in $PATH: unknown
```
This seems to be [the recommended way to override the `ENTRYPOINT`](https://docs.docker.com/compose/compose-file/#entrypoint) and solved the problem.
> fix: override entrypoint in the Docker Compose config

- benefits/core/templates/core/agency_index.html
- benefits/core/views.py
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
- tests/cypress/specs/feature/eligibility.spec.js
- tests/cypress/specs/ui/eligibility.spec.js
- tests/cypress/specs/ui/index.spec.js
Closes #367 
Follows approach outlined in the ticket. Using a new template specific to `agency_index` gave us the flexibility to use `blocktranslate` for embedding the link to "Learn more about Cal-ITP Benefits."
Note that I didn't attempt to style the page. I think @machikoyasuda has an idea for doing a focused cleanup of styles in a separate ticket. Let me know though if that's not correct! 🙏 
Latest screen from Figma mockup:
Current view on this branch:
Here's the Before (from dev branch):
> Refactor: agency index

- Dockerfile
- docs/getting-started/README.md
Switching branches was getting time-consuming; this moves the expensive operation of installing the Python packages earlier in the `Dockerfile` so that changes to application/configuration files don't require all packages to be reinstalled.
> refactor: speed up Docker image rebuild times

- benefits/core/templates/core/agency_index.html
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
- benefits/static/css/styles.css
Related to #435 , but does not close it entirely.
This PR makes the `agency_index` page better match the Figma mockup. 
I noticed that #397 did not actually change the font-size, letter-spacing, and line-height for this page (at least for the resolution/screen size that I normally use). This was because the `@media (min-width: 992px)` styles were overriding the changes made in #397. I fixed that (which probably fixes it for other pages too?) and then added styles for better spacing on the title, paragraphs, and button label.
| Before | After |
| ------- | ------ |
| ![image](https://user-images.githubusercontent.com/25497886/163654489-044cfb98-8238-4734-9412-bdcdb8dd81b8.png) | ![image](https://user-images.githubusercontent.com/25497886/163654414-ab51dc15-f700-48ca-9774-deb156eebc81.png) …
> Style: agency index

- benefits/core/templates/core/base.html
- benefits/static/css/styles.css
#435 
Fixes most of 435.
Moves the `DEBUG BAR` _out_ of the `<header>` HTML element, which has a lot of CSS added on it. 
Open any page _with_ this PR, and then open another tab of the same page -- with the Debug bar entirely removed. (You can remove it by commenting out the Debug bar HTML code, or also removing it from the DOM within DevTools). The spacing of everything under the header _should remain the same_.
> fix(header): move debug bar out of <header>, remove header height css

- benefits/eligibility/views.py
Fixes #439 
Reorders the creation of the `ctx` for the template to:
* Create the `eligibility:confirm` button and default media item list first
* If auth is required, insert into the media list
* If auth is required and not signed in, overwrite the button to `oauth:login`
* Finally, create page with button, and then create `ctx` from page and media list
> Fix: simplify context creation for Eligibility start

- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
Related to #433 
The change made in #437 was missing a space in between `every` and `time`. This was noticeable when the user selects their transit agency since both pages should have the same content title.
> Fix index content title to match Figma mockup

- benefits/settings.py
Closes #442 
The nginx reverse proxy sits in front of the application in deployed environments, and SSL terminates before getting to Django. 
We already add this header in the [nginx configuration](https://github.com/cal-itp/benefits/blob/dev/nginx.conf#L55) using the value of the request `$scheme`.
Adding the setting allows Django to determine if the original request was secure or not, if the header value (set by nginx on the request) matches the setting value (`https`).
See https://docs.djangoproject.com/en/3.2/ref/settings/#secure-proxy-ssl-header
> Fix: add SECURE_PROXY_SSL_HEADER for nginx

- .github/workflows/tests-pytest.yml
- tests/pytest/conftest.py
- tests/pytest/test_views.py
Also add configuration to run Django tests in GitHub Actions. Want a baseline test that works as a starting place for adding tests in https://github.com/cal-itp/benefits/pull/445. Merged in https://github.com/cal-itp/benefits/pull/455 to build off of those.
> Chore: run pytest in CI

- benefits/static/css/styles.css
Part of #456, only addresses the button
Note that all buttons in the app are using the same style, so we have to be careful to not introduce regressions/undesired results.
Some details from my commit message:
> The main goal here was to make the "Go back" button on the Help page
> smaller. Most of the buttons in the Figma mockup are around 250px, so
> set that as min-width. Use margin:auto for better centering.
> Style: Help page button width

- benefits/static/css/styles.css
This CSS change affects:
- _Every_ button/button-like link (**Get started**, **Continue**, **Check status,** **Back**), in the Main Container (`.container.content .btn-lg`) now has a height of 60px. All of these buttons have a height of 60px with text vertically and horizontally centered.
- This means it does not affect the Español/English button in the Header. (The Español/English button _also_ uses `.btn-lg` class, but this button is 38px high.
| Figma | After | 
| ------ | ------|
| <img width="172" alt="image" src="https://user-images.githubusercontent.com/3673236/164308290-1c26249d-6fb4-4922-9de8-83402af3944c.png"> | <img width="675" alt="image" src="https://user-images.githubusercontent.com/3673236/164308813-d971d2ab-0b27-48bc-8096-8ee49443047b.png"> |
To test this PR:
- Check _all_ …
> Button: Large Button centering/height fixes

- tests/pytest/test_settings.py
Tests that a user cannot access the `/admin` page when `settings.ADMIN` is set to `False`.
> Test: test admin route is not registered

- benefits/locale/es/LC_MESSAGES/django.po
This PR fixes a current bug where `core.pages.agency_index.p[0]/help#about` is being displayed instead of the actual copy on the Agency Index page.
|Current | Fixed   |
|--------|--------|
|<img width="1512" alt="image" src="https://user-images.githubusercontent.com/3673236/164566766-c78f6c4f-5c8e-4f92-baf4-6aff0c729abf.png">|<img width="1511" alt="image" src="https://user-images.githubusercontent.com/3673236/164566793-f993fb9a-a688-471a-b070-b33ec3569257.png">|
> Fix: Spanish copy on agency index

- benefits/core/admin.py
- benefits/core/analytics.py
- benefits/core/context_processors.py
- benefits/core/middleware.py
- benefits/core/recaptcha.py
- benefits/core/session.py
- benefits/eligibility/api.py
- benefits/eligibility/views.py
- benefits/oauth/views.py
- benefits/urls.py
- docs/configuration/README.md
Before this PR, we were importing settings variables directly from our own `benefits.settings` module.
According to Django best practice on [Using settings in Python code](https://docs.djangoproject.com/en/3.2/topics/settings/#using-settings-in-python-code), instead we should import the `django.conf.settings` object and use attributes off of that.
This PR updates everywhere we had imported `benefits.settings` or variables to use the recommended approach.
Also updated our docs guidance around using settings in application code.
> Fix: use recommended settings import approach

- benefits/core/session.py
- benefits/eligibility/views.py
- benefits/enrollment/views.py
- benefits/oauth/urls.py
- benefits/oauth/views.py
- tests/pytest/conftest.py
- tests/pytest/oauth/test_views.py
- tests/pytest/requirements.txt
Closes #368.
Consolidated #464 into this PR.
This PR adds a new route `/oauth/logout` that signs the user out of all 3 environments: Login.gov, the auth server, and the Django app.
We have to store the `id_token` that we get back as part of the `/oauth/authorize` callback, in order to later be able to sign the user out. Because of this, session management was updated to differentiate between the `oauth_token` and the `enrollment_token`.
The sign out flow is:
1. User clicks the sign out button (#428)
2. `/oauth/logout` retrieves the (now stored) OAuth token from user's Django session
3. User's Django session OAuth token is cleared 
4. A redirect URI is generated for `/oauth/post_logout`
5. User is redirected through the auth server's `end_session_endpoint` with their token and the redirect …
> Feat: Implement OAuth/OIDC and app sign out

- pyproject.toml
- tests/pytest/oauth/test_views.py
Closes #476 
Closes #477 
* `authorize_redirect` is called, with a redirect for `/oauth/authorize`
* login status is not updated
* When `authorize_access_token` fails, login status not updated and redirected back to start page
* When `authorize_access_token` succeeds, login status updated and redirect to confirm page
> Tests: OAuth login flow

- benefits/core/templates/core/page.html
- benefits/static/css/styles.css
- tests/cypress/cypress.json
- Desktop header height should always be 80px.
- Desktop footer height should always be 40px. Currently, the Help page and Eligibility Start page footers are not 40px.
- Desktop's main container (that is, anything between the Header and Footer) should now be 100% of the viewport height, minus 120px (80px header + 40px footer).
0. Help Page and Eligibility Start Page's  footers should be 40px now, along with the rest of the app.
| Footer         | Footer     | 
|--------------|-----------|
|<img width="1512" alt="image" src="https://user-images.githubusercontent.com/3673236/164540612-88f47356-000e-4a9d-98cd-13ad79115d57.png">|<img width="1512" alt="image" src="https://user-images.githubusercontent.com/3673236/164540717-a9cb806a-748f-4b2a-911e-eebfad51bbd0.png">|
| Help Page | Eligibility …
> Fix: Align Desktop Header/Container/Footer heights

- .github/workflows/codeql.yml
Per warning in action runs, e.g. https://github.com/cal-itp/benefits/runs/6161384923?check_suite_focus=true#step:3:10
Closes #393
> Fix: add on.push for CodeQL runs

- .github/workflows/labeler-tests.yml
Just a helper visual indication for PR reviewers etc., similar to our other auto-labelers for e.g. `deployment-dev`
> Feat: CI workflow to label PRs that touch tests

- .coveragerc
Broken out from https://github.com/cal-itp/benefits/pull/487.
> fix: ignore migrations from test coverage report

- tests/pytest/run.sh
Otherwise, it's easy to refresh the page and see old results. Broken out of https://github.com/cal-itp/benefits/pull/487.
> fix: clean out old test coverage results

- benefits/core/middleware.py
- benefits/enrollment/views.py
Was getting the warning
```
/home/calitp/app/benefits/enrollment/views.py:62: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
logger.warn(f"card_tokenize_url: {context['payment_processor'].card_tokenize_url}")
```
> fix: replace deprecated logger warning calls

- tests/pytest/conftest.py
It was causing confusion for various members of the team (including me); hopefully this will make it more clear if the path is inspected in a test.
> refactor(tests): make more explicit that the default app_request path is arbitrary

- benefits/core/middleware.py
- tests/pytest/conftest.py
- tests/pytest/core/test_middleware_healthcheck.py
- tests/pytest/core/test_middleware_login_required.py
- tests/pytest/eligibility/test_views.py
- tests/pytest/enrollment/test_views.py
- tests/pytest/oauth/test_views.py
This pull request builds out tests for various views that hit the various middleware, bringing the overall test coverage from [57%](https://github.com/cal-itp/benefits/runs/6179499569?check_suite_focus=true#step:8:90) to [65%](https://github.com/cal-itp/benefits/runs/6184144403?check_suite_focus=true#step:8:102). I didn't touch:
- The analytics-related middleware, since it seems like things around that are changing
- `RateLimit`, since I'm not sure we want to keep that as is: https://github.com/cal-itp/benefits/issues/502
I went with view-level tests rather than ones testing the middleware directly, since that "fed two birds with one scone," exercising the views _and_ the middleware that restrict them. If folks feel strongly about testing narrower slices, I can change them.
> Test: add tests for middleware

- .github/workflows/mkdocs.yml
- docs/.pages
- docs/getting-started/.pages
- docs/tests/.pages
- docs/tests/README.md
Download the coverage report artifact (#499) and send it with the `mkdocs` publish.
The latest coverage report from dev will be available at https://docs.calitp.org/benefits/tests/coverage
> Docs: publish the coverage report with docs site

- benefits/core/analytics.py
- benefits/core/session.py
- tests/pytest/core/test_session.py
Follow-on to #474.
Fixes "default" tests for the 3 user-info session functions:
* `did` (device ID)
* `start` (session start time)
* `uid` (user ID)
Checks that in each case, `session.reset()` is called when no value is initially present, so that a value is always returned.
> Test: default user session values

- benefits/core/templates/core/base.html
Closes #377
#452 took care of sending Amplitude events when executing server-side logic for sign-in and sign-out. 
This PR finishes out the goal of #377 by sending Amplitude events for which help links the user clicks so we can see where they might be getting distracted and/or dropping off. This is done on the client-side so that the event data includes the hash and URL fragment (e.g. #payment-options), which is not available server-side.
- Launch the app
- Navigate through the flow to the `eligibility:start` page
- Open dev tools, and put a breakpoint in the Javascript for `amplitude.getInstance().logEvent('clicked link', {'href'...`
- Click one of the three help links:
- "Learn more about Login.gov"
- "Don't have a bank card?"
- "Unsure if you have a contactless card?"
- In the debugger …
> Feat: anchor link analytics

- benefits/static/css/styles.css
closes #511 
- Check Eligibility Start page in MST Courtesy Cardholder flow
- Check Eligibility Start page in Senior Discount flow by going through Login.gov, entering an invalid/unverified credential, clicking Try Again and going _back_ to Eligibility Start _after_ already being logged in to Login.gov
> fix(css): right-align continue button on eligibility start

- .github/workflows/mkdocs.yml
Following on to #500 and #509, trying to publish the latest `coverage` report to our docs site.
#509 introduced what amounted to a race condition between the `mkdocs` and `pytest` workflows - if `pytest` took too long, `mkdocs` would run and deploy before the `coverage` report was updated.
This PR makes the relationship explicit: `mkdocs` now runs after `pytest` has run and is successful, in addition to running in response to real docs updates.
Read more about triggering with `workflow_run`: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
> Fix: mkdocs runs after Pytest

- benefits/core/context_processors.py
- benefits/core/templates/core/includes/sign-out-link.html
- benefits/eligibility/templates/eligibility/confirm.html
- benefits/eligibility/templates/eligibility/unverified.html
- benefits/eligibility/views.py
- benefits/enrollment/templates/enrollment/index.html
- benefits/enrollment/templates/enrollment/retry.html
- benefits/enrollment/views.py
- benefits/settings.py
- benefits/static/css/styles.css
Closes #428 
- Adds new context processors
- `authentication`: Adds information about authentication requirement and status to context for use in templates
- `auth_provider`: Adds information about auth_provider to context
- Adds a new includes `sign-out-link.html` that shows only if authentication is required and user is signed in
- Adds usage to the pages that need it
- `eligibility:confirm`
- `eligibility` unverified
- `enrollment:index`
- `enrollment:retry`
> Feat: sign out link

- benefits/enrollment/views.py
msgid was changed in #480 to `core.buttons.retry`, but this usage was leftover
> Fix: enrollment retry button msgid

- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
- tests/cypress/specs/ui/eligibility-auth.spec.js
closes part of #522 
* I did not change the driver license
> fix(copy): update copy on eligibility start

- benefits/enrollment/views.py
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
- Adds a success page Title that's separate from Content Title for English and Spanish
- Removes a button link, removes variable for that link
> Fix/copy: Enrollment Index & Success

- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
> Fix: help copy - update Littlepay punctuation and link text

- benefits/core/templates/core/help.html
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
> Fix: help copy - update Login.gov section/links

- docs/.pages
- docs/tests/.pages
It was linking to a non-existent top-level directory.
> Fix: link to coverage report in docs

- benefits/core/templates/core/help.html
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
closes part of #522
~WIP: awaiting confirmation from @vykster if we should continue to link to Cash App / Venmo~
Just going to assume this is the same as the current app. We can change later if needed.
**EDIT**
Added the links presuming we still want this behavior:
> Fix: help copy - update Payment Options

- benefits/eligibility/views.py
From @machikoyasuda in Slack:
> ***Sign out button issue*** When I go through Login.gov, I get to the Eligibility Confirm page and see the Sign out of Login.gov button. Then, I make a mistake on my form (either put in a bad ID number or a bad last name), the page refreshes and shows me my errors. At that point, the Sign out of Login.gov link disappears
> Fix: signout link on Eligibility Confirm resubmission page

- benefits/core/templates/core/includes/form.html
fix https://github.com/cal-itp/benefits/issues/405
Google Recaptcha seems to be removing the `disabled` state from the button HTML (related issue: https://stackoverflow.com/questions/59546714/google-recaptcha-enables-disabled-submit-button#59567003). Instead of disabling the button with HTML, I'm using a Bootstrap CSS class to do it. The CSS class uses `pointer-events: none` (which has high cross-broswer compatibility: https://caniuse.com/pointer-events)
- add `.disabled` class to override recaptcha removing disabled state
> fix(button): 

- .devcontainer/compose.yml
https://stackoverflow.com/a/70957456/358804
Extracted from https://github.com/cal-itp/benefits/pull/398.
> fix: remove deprecated Docker Compose volume option

- tests/pytest/conftest.py
- tests/pytest/requirements.txt
Want to ensure that we're not making any calls to external APIs. Confirmed it worked by sticking in a call to `requests.get()`.
> chore: disable network requests in pytests

- .github/workflows/add-to-project-dependabot.yml
- .github/workflows/add-to-project-issues.yml
Closes #570.
There are two separate workflows:
* One for newly opened or transferred issues
* Another for PRs opened by Dependabot
See the [`add-to-project`](https://github.com/actions/add-to-project#usage) docs for more.
See also [Automating Dependabot with GitHub Actions](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions).
> CI: add issues and Dependabot PRs to Project Board

- benefits/static/css/styles.css
closes #571 
Center the button's label on the Agency Index page, and only that page. 
| **Desktop**         | **Mobile**     |
|--------------|-----------|
| <img width="1512" alt="image" src="https://user-images.githubusercontent.com/3673236/167941380-11a62a45-afab-4078-9b60-991963440926.png"> |<img width="450" alt="image" src="https://user-images.githubusercontent.com/3673236/167941412-d1abb91a-0f1c-44bf-9a4b-488b3d3573de.png">      |
> Desktop: Agency Index - Center the label over button on Agency Index page

- benefits/core/views.py
- tests/pytest/core/test_views.py
Closes #566
- Updates the core app's `index` function to redirect to the agency's index if there is only one active agency.
- Also added a unit test for behavior of homepage with single agency.
- Also launched the app and tested manually.
> Feat: redirect to agency's index if only one agency

- benefits/core/templates/core/page.html
- benefits/core/viewmodels.py
- benefits/static/css/styles.css
closes #535 
- Move image logic from the HTML template and the Page object into CSS only
- Add new updated image display styles for screens under the 992px width breakpoint.
- Image on mobile screens is now set to 240px in height, from the bottom. This allows the hand, the card with the VISA logo, the contactless pay logo on the card reader all to be shown: 
- The button now has 2px solid #2b6597 borders, with a 3px border radius and 10px top and bottom/30px left and right padding, resulting in a button that's 231px by 46px. The button is 20px below the bottom of the image. <img width="476" alt="image" src="https://user-images.githubusercontent.com/3673236/167921623-a699ac31-d4c4-442c-8bb3-5b1a67de32c6.png">
- You must turn off Debug mode or hide the Debug bar, or else the button gets …
> Mobile: Image and Sign Out Link

- benefits/static/css/styles.css
fixes #538 
- remove ordered list number
- make icon smaller
- make links into button with styles
- Center the whole thing
- Left-align text
- What about two-line buttons
> Mobile/Tablet - Eligibility:Start - Link style, spacing

- benefits/locale/es/LC_MESSAGES/django.po
- tests/cypress/specs/ui/enrollment.spec.js
Closes #533 
- Status: All translations are in 
- Open question (to be addressed in a new PR): Should `Cal-ITP Benefits` be styled as `beneficios de Cal-ITP` or `Beneficios de Cal-ITP` or `Cal-ITP Beneficios`?
--
* Need to get into Enrollment pages
*This doesn't have the sign out message
> Fix: Add Spanish copy for all pages

- benefits/core/templates/core/base.html
> Fix: Use 1st sentence of help page for meta description

- benefits/enrollment/views.py
- benefits/static/css/styles.css
closes #565 
closes https://github.com/cal-itp/benefits/issues/513
1. Test MST / Senior flow of getting to enrollment succecss page and then logging out from the success page
2. Test MST / Courtesy Card flow of getting to enrollment success page
> Enrollment Success: Redesign page to have no image

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/deliverable.md
- .github/ISSUE_TEMPLATE/epic-decision-record.md
- .github/ISSUE_TEMPLATE/task.md
- .github/ISSUE_TEMPLATE/user-story.md
closes #604 
Discussed at today's Developer Team meeting.
Adds 5 (!!) more issue templates for the following scenarios:
1. bug report: for anyone to report bugs on the app (to be closed with a corresponding pull request)
2. user story: for product to write user stories for new features
3. task: task is for an individual engineering task (to be closed with a corresponding pull request)
4. deliverable: "deliverable" is our new word for any github issue that's not for a code change. it could be an issue to track work like: user testing, user research, writing planning documents for a meeting. these issues don't end up with a pull request.
5. epic decision record: this is for our big "epic" issues, which track a _group of_ related user stories, tasks and deliverables. epics can also contain …
> Chore: Add GitHub issue templates

- .github/ISSUE_TEMPLATE/epic-decision-record.md
Replace `label` with `labels` so the correct label is applied when using this issue template.
> Fix: typo in labels frontmatter in Epic issue template

- benefits/core/models.py
- benefits/eligibility/views.py
- requirements.txt
- tests/pytest/eligibility/test_views.py
Closes #617 
- First, review [cal-itp/eligibility-api#31](https://github.com/cal-itp/eligibility-api/pull/31)
- Then, on this branch, make sure the `eligibility-api` package is installed by either:
- rebuilding the `client` image and the devcontainer
- OR running `pip install -r requirements.txt` (run `pip uninstall eligibility-api` first if you previously installed it and want to re-install it)
- Run the Pytests at [`tests/pytest/eligibility/test_views.py`](https://github.com/cal-itp/benefits/blob/b48eaa7bca8bac2c7da2567cb67ca7f30982bbe7/tests/pytest/eligibility/test_views.py) to see that eligibility verification still works
> Refactor: remove jwcrypto

- benefits/eligibility/api.py
- benefits/eligibility/views.py
- tests/pytest/conftest.py
- tests/pytest/eligibility/test_api.py
- tests/pytest/eligibility/test_views.py
Simplifies logic in the Eligibility views by wrapping the API Client and request/response parsing into a helper function.
Closes #622
> Refactor: bring back eligibility API helper module

- benefits/static/css/styles.css
closes #632 
- all mobile action buttons are now 72px height.
- login.gov/getting started page buttons remain the same. header Spanish language button remains the same.
- Check buttons on:
- Agency page
- Home page
- Help page
- Form pages
- iPhone SE
- iPad, vertical
> Mobile: All action buttons on mobile are now 72px height.

- bin/init.sh
- docs/configuration/fixtures.md
This is another area that can trip up new devs (and, me...:blush:), especially with all the extra warning messages that can be printed. Then if you have a mismatch in data/migrations and existing schema there can be all kinds of annoying errors.
In development mode, it's nice (e.g. when the devcontainer starts) to have the init script clear out any existing database file before rebuilding the whole thing.
In production, this should be a noop since the database file won't exist yet.
> Chore: init deletes existing db

- docs/deployment/azure.md
- terraform/.gitignore
- terraform/.terraform.lock.hcl
- terraform/README.md
- terraform/main.tf
- terraform/monitor.tf
- terraform/uptime.tf
- terraform/uptime/README.md
- terraform/uptime/main.tf
- terraform/uptime/variables.tf
- terraform/uptime/webtest.xml
Closes https://github.com/cal-itp/benefits/issues/449.
This is a proof of concept to show two things:
- A [URL ping test](https://docs.microsoft.com/en-us/azure/azure-monitor/app/monitor-web-app-availability)
- Use of Terraform for #618 
~~About half~~ A lot of the additions in the pull request are just Terraform boilerplate. Uptime-specific stuff is in `terraform/uptime.tf`. Note this doesn't bring any existing Azure resources into management by Terraform.
If people are 👍 on the approach, I would want to do the following from here:
Feedback welcome!
> Feature: set up uptime monitoring

- docs/deployment/README.md
- docs/deployment/infrastructure.md
- mkdocs.yml
Based on suggestion in https://github.com/cal-itp/benefits/pull/623#pullrequestreview-1002047322, changed the "Azure" page to be more generally about "Infrastructure", and moved the intro paragraph to the top-level Deployment page.
> chore: better integrate infrastructure documentation

- .vscode/settings.json
- benefits/core/views.py
- tests/cypress/specs/ui/eligibility-no-auth.cy.js
- tests/cypress/specs/ui/enrollment.cy.js
- tests/pytest/core/test_views.py
closes #656 
As a senior with a Social Security Number, when I go to benefits.calitp.org, I should get redirected to the Eligibility Start page.
- Applies this new view logic: When there is only 1 agency and 1 verifier, redirect the user to the eligibility start page
You will have to change your database data to reflect a scenario in which there is only 1 agency and 1 verifier. There are 2 ways to do this -
1. Remove `DefTL` agency from the `05_transitagency.json` file
2. For the `ABC` agency, Change `"eligibility_verifiers": [1,2]` to `"eligibility_verifiers": [1]`
3. Run `bin/init.sh` - This should remove your current database, create a new database and run the necessary migrations
4. Go to `localhost:8000`
5. The site should redirect you to `localhost:8000/eligibility/start`
1. Turn on …
> IAL2 Login.gov Flow: Redirect users to Eligibility Start

- .devcontainer/Dockerfile
- .devcontainer/postAttach.sh
- .pre-commit-config.yaml
- docs/tests/README.md
Punchline up front: This **speeds up devcontainer start time by around five minutes** on my machine.
The start time of a devcontainer was becoming a regular annoyance for me, enough so that I was finding myself working outside of it, which kinda defeats the purpose. I spent a bit of time to improve a couple of things that would make a big difference:
- Install pre-commit dependencies at `dev` image build time, which is infrequent/cached
- Don't bother installing Cypress in the devcontainer, since it wasn't being used (and maybe wasn't even working?) in there anyway. @machikoyasuda Can you confirm?
While it doesn't complete _all_ the tasks listed, I'm going to say this closes https://github.com/cal-itp/benefits/issues/495 as being "good enough."
> Chore: Faster devcontainer start

- .devcontainer/Dockerfile
- .vscode/launch.json
Since Cypress was removed from the devcontainer install in #671, we don't need all the node/npm bits in there anymore.
Snuck in another small removal from the `launch.json` file, we had an env override for `CYPRESS_baseUrl` that wasn't actually being used.
> Chore: remove node/npm installation steps in devcontainer

- terraform/storage.tf
Part of #615.
This has been `apply`'d. The corresponding fixture file has been copied from `benefits-config`, and renamed to `fixtures.json`. Opened a separate issue to get the mounting set up: https://github.com/cal-itp/benefits/issues/686
> chore: create configuration containers in Azure

- terraform/app_service.tf
https://docs.microsoft.com/en-us/azure/app-service/deploy-ftp
We aren't using this, so for better security, turn it off.
> fix: disable the FTP service

- benefits/eligibility/views.py
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
- benefits/static/css/styles.css
closes other part of #689 
```
- Touch targets on desktop Help URLs span the page, which can create a misleading or unexpected hover effect
- On mobile, we took out the text link "Learn more about Cal-ITP benefits" entirely, as it links to the same location as the Help button at the bottom
```
> Fix: Eligibility Start - Links

- benefits/oauth/client.py
- benefits/oauth/views.py
- benefits/settings.py
- tests/pytest/oauth/conftest.py
- tests/pytest/oauth/test_client.py
- tests/pytest/oauth/test_redirects.py
- tests/pytest/oauth/test_views.py
Closes #640.
The refactor in #668 make this a lot easier - it created a helper function `benefits.oauth.client.instance()` to get the client instance. This PR makes two changes to that helper:
1. Each returned instance is now distinct; before it was a singleton
2. The helper accepts a `scope` param and adds it to the list of scopes configured in the client's `client_kwargs` attribute
The hardcoded scope (`openid`) in `settings.py` was removed in favor of always adding it in this helper.
> Feat: dynamic OAuth scope from verifier

- benefits/core/templates/core/help.html
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
- tests/cypress/specs/ui/help.cy.js
Closes #705
Updates a body paragraph in "What is Cal-ITP Benefits?" section to say Login.gov will verify age.
Adds a section for "How do I verify my identity on Login.gov?".
Updates made using finalized English copy and any Spanish copy update that was available.
| Before | After |
| ------- | ----- |
| ![705_old_help](https://user-images.githubusercontent.com/25497886/174192563-df2a18e7-2ccc-4117-b522-a04eaaf598f2.png) | ![705_new_help](https://user-images.githubusercontent.com/25497886/174192592-dafba3a3-db0c-45f3-aa18-f2f1996dbc3f.png) |
| Before | After |
| ------- | ----- |
| ![705_old_help_mobile](https://user-images.githubusercontent.com/25497886/174193415-ecd0acfa-2a3f-4439-85f9-6f2e79ffc51a.png) | ![705_new_help_mobile](https://user-images.githubusercontent.com/25497886/174193438- …
> Feat: IAL2 help copy

- benefits/core/templates/core/includes/debug.html
- benefits/static/css/styles.css
closes #716 
- Font size increased to 20px on mobile
- Double-checked no regression on Desktop for links
| Before            | After     |
|--------------|-----------|
|![Screenshot 2022-06-22 at 14-06-38 Transit Benefits Get Started Cal-ITP](https://user-images.githubusercontent.com/3673236/175136150-b15f37d6-1f9d-4785-b591-29e2affb2c81.png)  | ![Screenshot 2022-06-22 at 13-47-43 Transit Benefits Get Started Cal-ITP](https://user-images.githubusercontent.com/3673236/175133230-81885013-fa17-49d6-a922-dba35d701a65.png)    |
Before: Sign Out button would go over the Debug Bar
After: Debug Bar won't affect the Sign Out button position
Before: Enrollment page would have white-space to the right and bottom
After:
> Fix: Fixes for Eligibility Start Link Style, Debug Bar-related improvements

- .github/workflows/tests-ui.yml
Things are changing too much on the front-end with copy, flows, options, etc.
Our [Pytest coverage is over 80%](https://docs.calitp.org/benefits/tests/coverage) and we need to re-think the role of Cypress tests - for now, don't run them to unblock other changes.
We still run the Lighthouse a11y checks (albeit on only 2 pages in the app) - and this is probably an area where we want to focus more of our front-end testing efforts.
> Chore: don't run Cypress tests in CI

- benefits/core/templates/core/help.html
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
closes #730 
These three links should go to the following URLs: https://login.gov/es/, https://login.gov/es/help/, https://login.gov/es/help/verify-your-identity/how-to-verify-your-identity/  And in English mode, it should go to the English version of these URLs.
> Spanish language links

- benefits/logging.py
- benefits/settings.py
- docs/configuration/environment-variables.md
- docs/deployment/infrastructure.md
- requirements.txt
- tests/pytest/test_logging.py
Closes https://github.com/cal-itp/benefits/issues/631. Keeps the logging otherwise the same.
Used the following instructions, to start:
- https://docs.microsoft.com/en-us/azure/azure-monitor/app/opencensus-python#configure-logging-for-django-applications
- https://docs.microsoft.com/en-us/azure/azure-monitor/app/opencensus-python-request#tracking-django-applications
Added tasks for each environment in https://github.com/cal-itp/benefits/pull/734.
> Send logs to Azure Monitor

- terraform/monitor.tf
Seems like we want one corresponding to each (persistent) slot. This has not been `apply`'d.
> Set up test instance of Azure Insights

- benefits/core/middleware.py
- benefits/settings.py
- docs/deployment/infrastructure.md
Builds on https://github.com/cal-itp/benefits/pull/719. Closes #448.
Got exceptions to flow to Insights. The `exceptions` table under `Logs`:
`Failures` screen:
After clicking into an exception:
> Send exceptions to Azure Monitor

- .github/workflows/deploy-dev.yml
Closes https://github.com/cal-itp/benefits/issues/739.
The path filter was potentially making deploys not happen when we would expect them; this will avoid those cases by always deploying.
> feat: deploy dev on all pushes

- terraform/app_service.tf
Follow-up to https://github.com/cal-itp/benefits/pull/737. These seem to be necessary for connecting the App Service instance to Application Insights, after all.
> chore: re-add auto-instrumented variables to deployment slot settings

- benefits/eligibility/templates/eligibility/start.html
- benefits/static/css/styles.css
fixes #726 
Reorganize page's headlines into one h1, one h2, multiple h3 and adjust CSS as necessary
Ensure no regressions in styles between Staging and this PR:
Note: This PR does not attempt to tackle refactoring the way the app's CSS styles H1, H2s. That is work for this future ticket: https://github.com/cal-itp/benefits/issues/751
> fix: Eligibility Start - Add h1, h2, h3

- .devcontainer/devcontainer.json
- .vscode/settings.json
Split out from https://github.com/cal-itp/benefits/pull/669, excluding the use of the new extension.
This does a few things:
- Sets the default formatter to be Prettier, which will also apply it to things like Markdown.
- Formats on save by default, which is fine because formatting HTML is still disabled, protecting the Jinja templates.
- Formats the settings files (with Prettier).
> chore: improve formatting behavior

- docs/deployment/infrastructure.md
Related to https://github.com/cal-itp/benefits/issues/631.
> add documentation on where logs can be found

- benefits/core/viewmodels.py
- benefits/eligibility/views.py
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
This is based off #762. In this case where we're just tweaking copy, it seemed better to go ahead and open this PR with my suggestions as changes.
- Remove second paragraph from `unverified`. It was redundant in the English copy and had an extra line break in the Spanish copy, which was not present in Figma.
(Redundant second paragraph)
- Changed button text to use "core.buttons.return_home" so that it says "Return Home" when in English
- Updated Spanish PO entry to match the [finalized copy](https://docs.google.com/document/d/1Ndai_9Ut6DLU86w6BpkmU23xzG1QF0a0-BeQ3_FWNoQ/edit#bookmark=kix.382mzwubv2r3) for the "core.buttons.return_home" button
- Fixed a bug where switching the language didn't work for instances created from `Button.home()` static method
> Copy: remove second paragraph, update button text, fix default arg bug

- benefits/core/viewmodels.py
- benefits/eligibility/views.py
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
- benefits/static/css/styles.css
closes #759
For /unverified page:
- Update copy
- Make the icon bigger (from 92px to 150px)
- Center all the text
- Remove side image
For the pages *with* the image:
- Make sure the icon stays at 92px
- Make sure the text is not centered
> Fix: Unverified page copy and design

- benefits/oauth/analytics.py
- benefits/oauth/views.py
- tests/pytest/oauth/test_views.py
Closes #644 
Send an event if the user cancels out of identity proofing.
> Feat: analytics for IAL2

- tests/pytest/conftest.py
- tests/pytest/core/test_middleware_login_required.py
- tests/pytest/core/test_models.py
- tests/pytest/core/test_session.py
- tests/pytest/core/test_views.py
- tests/pytest/eligibility/test_verify.py
- tests/pytest/eligibility/test_views.py
- tests/pytest/enrollment/test_api_Client.py
This PR removes the dependency of pytests on our `django.db` database.
Many tests assumed the database existed with particular contents - specific `TransitAgency` configurations, multiple or single `EligibilityVerifier`, etc. Many tests queried the database for particular model instances (e.g. `ABC`).
Instead, this PR introduces a number of `@pytest.fixture` that create test data in the test database and return model instances. These are used throughout the test modules to simplify tests, clarify intent, and entirely separate our _JSON fixtures_ from our pytests.
This is prerequisite work and related to #723.
> Fix database setup for pytests

- benefits/settings.py
- requirements.txt
Closes #283 
This PR sets [`SECURE_CROSS_ORIGIN_OPENER_POLICY`](https://docs.djangoproject.com/en/4.0/ref/middleware/#cross-origin-opener-policy) to `same-origin-allow-popups`, which is the most secure option that still allows the overlay to work.
This setting was [introduced in Django 4.0.x](https://docs.djangoproject.com/en/4.0/releases/4.0/#requests-and-responses) and by default, sets the [`Cross-Origin-Opener-Policy` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Opener-Policy) to `same-origin`, which prevents cross-origin popups from accessing their opener's browsing context. Prior to Django 4.0.x, the header was unset.
If you look through the Javascript of our enrollment overlay, you'll notice that it makes use of …
> Fix: enrollment overlay in Django 4.0.x

- benefits/settings.py
- benefits/urls.py
- docs/README.md
- docs/configuration/README.md
- docs/configuration/environment-variables.md
- docs/configuration/fixtures.md
- docs/configuration/rate-limit.md
Forgot about docs in #793 
Updates links to Django documentation from 3.2 to 4.0. Some minor formatting changes also were applied.
> Docs: update links to Django documentation from 3.2 to 4.0

- terraform/app_service.tf
Test for #773.
This is to confirm that our service connection in the pipeline has sufficient permissions to change the App Service slots. Will be reverted after merge and successful deploy.
> chore: test change to slot

- docs/requirements.txt
- mkdocs.yml
Closes #798.
Closes #801.
The unused `fontawesome_mkdown` extension was causing a local site build issue on some machines.
`mkdocs-material` comes with built-in support for emojis/icons, see https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#configuration
This PR removes the unused extension and configures the site to enable the built-in feature.
Snuck in a small fix for Mermaid diagrams as well.
> Fix: local docs site build

- terraform/.terraform.lock.hcl
- terraform/app_service.tf
- terraform/network.tf
Closes #771 
We're currently getting an error trying to `terraform apply` these changes:
> Error: checking for presence of existing App Service Environment: (Hosting Environment Name "ASE-CDT-PUB-CALITP-P-001" / Resource Group "RG-CDT-PUB-SHRD-W-P-001"): web.AppServiceEnvironmentsClient#Get: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'kegan@compiler.la' with object id '[REDACTED]' does not have authorization to perform action 'Microsoft.Web/hostingEnvironments/read' over scope '/subscriptions/[REDACTED]/resourceGroups/RG-CDT-PUB-SHRD-W-P-001/providers/Microsoft.Web/hostingEnvironments/ASE-CDT-PUB-CALITP-P-001' or the scope is invalid. If access was recently granted, …
> Terraform: override App Service Cipher Suite

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .pre-commit-config.yaml
- .vscode/settings.json
- benefits/core/templates/core/agency_index.html
- benefits/core/templates/core/base.html
- benefits/core/templates/core/help.html
- benefits/core/templates/core/includes/agency-links.html
- benefits/core/templates/core/includes/alert-bar.html
- benefits/core/templates/core/includes/alert.html
- benefits/core/templates/core/includes/button.html
- benefits/core/templates/core/includes/debug.html
- benefits/core/templates/core/includes/form.html
- benefits/core/templates/core/includes/icon-title.html
- benefits/core/templates/core/includes/icon.html
- benefits/core/templates/core/includes/lang-selector.html
- benefits/core/templates/core/includes/nocookies.html
- benefits/core/templates/core/includes/noscript.html
- benefits/core/templates/core/includes/sign-out-link.html
- benefits/core/templates/core/page.html
- benefits/core/templates/core/widgets/radio_select.html
- benefits/core/templates/core/widgets/radio_select_option.html
- benefits/eligibility/templates/eligibility/confirm.html
- benefits/eligibility/templates/eligibility/start.html
- benefits/eligibility/templates/eligibility/unverified.html
- benefits/enrollment/templates/enrollment/index.html
- benefits/enrollment/templates/enrollment/retry.html
- benefits/enrollment/templates/enrollment/success.html
- pyproject.toml
Closes #815.
* Swap `djhtml` for [`djlint`](https://github.com/Riverside-Healthcare/djlint) in `pre-commit` for HTML files
* `prettier` handles CSS files
* [Integrate `djlint` with devcontainer](https://djlint.com/docs/integrations/#visual-studio-code) for linting and formatting
* Lint/format all our HTML files
* Fix spacing (settings below)
* Apply names to all `{% endblock %}` tags e.g. `{% endblock buttons %}`
* Collapse inline tags e.g. `{% if %}...{% endif %}` inside an HTML `class` attribute
* Expand block-level tags
* Use `{% url %}` tag instead of hardcoding app URLs
* Use `{% static %}` tag to load static files (images) instead of hardcoding paths
To match our `prettier` config:
* Indent size 2
* Max line length 127
* Keep blank lines
* Use `.gitignore` (so e.g. local `coverage/` …
> Fix: Django template formatting

- .devcontainer/devcontainer.json
- .vscode/settings.json
At least provides syntax highlighting within the devcontainer.
With a local (host) terraform install, provides format-on-save and additional VS Code commands.
> Devcontainer: add terraform extension

- terraform/app_service.tf
These settings tell the slot which `registry/image:tag` to pull from.
> Terraform: add container registry/image to slots

- .gitignore
- benefits/core/migrations/0002_sample_data.py
- benefits/core/migrations/0003_data_migration_order.py
- benefits/settings.py
- bin/init.sh
- docs/configuration/data.md
- docs/configuration/environment-variables.md
This is a follow-up to #814 and closes #790 
Default behavior (meaning you don't set any new environment variable or anything) is that running `./bin/init.sh` will load in sample data into `django.db`. If you set an environment variable such that `DJANGO_LOAD_SAMPLE_DATA=False`, then it'll skip loading sample data.
You can also provide additional data migrations to be run. You can easily create one by making a copy of `0002_sample_data.py`, giving it a different name but still with the `0002_` prefix, and modifying the code however you want. The migration file `0003_data_migration_order.py` will handle ordering the data migrations.
> Feat: support for optional sample data and additional data migrations

- compose.yml
Minor `compose.yml` update to remove the fixtures volume mount from the `client` service - since we're no longer using fixtures.
> Chore: remove fixtures volume mount

- benefits/eligibility/views.py
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
A part of #776 
This PR cleans up how the `eligibility` `start` view function uses msgids. 
The view was hard-coding some oauth msgids when really those should be coming from the `EligibilityVerifier` model.    
The view also hard-codes some msgids for the links and bullet points, but because those are not configurable, we can at least add some logic to only show them if the verifier uses authentication as eligibility verification since that's what the links and bullet points are about.
> Refactor: eligibility start view msgids

- .coveragerc
- .pre-commit-config.yaml
- pyproject.toml
`pytest-cov` installs `coverage[toml]`, so can load from this file by default.
This reduces the number of config files we need in the repo, and consolidates config information for python tooling.
> Chore: move coverage config to pyproject.toml

- benefits/eligibility/templates/eligibility/start.html
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
One of multiple PRS for #776 
This PR refactors the Eligibility Start template so that the `msgid`s it uses are specifically meant for it and not reused elsewhere.
~These changes build off the workflow introduced in #785.~ This branch was rebased onto the one from #814.
> Refactor: separate msgids for Eligibility Start

- terraform/app_service.tf
I'm not sure if this is right / will work.
We have an [`azurerm_linux_web_app`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_web_app) which I think is considered an "App Service".
[`app_service_custom_hostname_binding`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service_custom_hostname_binding) expects an App Service name.
So deploys will work with CI (already configured in Azure)
Adding our new `DJANGO_LOAD_SAMPLE_DATA` and `DJANGO_MIGRATIONS_DIR` settings (for data migrations).
> Feat: terraform production configuration

- benefits/oauth/views.py
- tests/pytest/oauth/test_views.py
> Fix: auth scope check when userinfo is present, but claim is not

- .github/ISSUE_TEMPLATE/release.yml
- docs/deployment/release.md
This PR introduces a new Issue Template using GitHub's [Issue forms syntax](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms).
We want to be able to track the manual steps, and give more context into the folks responsible for the release. The form asks for a few items up front, including the `Release manager` and `version`.
The form also encodes the steps found on the docs page: https://docs.calitp.org/benefits/deployment/release/ into a checklist that can be used to guide the release process. The release is complete when the checklist is finished, and the tracking issue can then be closed.
> Feat: issue template for managing a release

- terraform/azure-pipelines.yml
Avoids race condition happening between pipeline runs.
> chore(pipeline): wait for Terraform lock to be released

- docs/use-cases/README.md
- docs/use-cases/seniors.md
- mkdocs.yml
#877 
This PR does two things:
1. Add a Seniors page for Use cases
2. Enables integrated navigation for better readability https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#__tabbed_6_1
> Docs: Use cases for Seniors

- .devcontainer/server/.env.server
- .devcontainer/server/settings.py
- benefits/core/migrations/0002_sample_data.py
- bin/build.sh
- compose.yml
Closes #880.
Update to use the new settings format. 
The local eligibility server now works within the devcontainer and locally with:
```bash
docker compose up server
```
Added a line to the `bin/build.sh` helper script to pull the latest `server` image from GHCR.
The following should give a verification success:
1. Set `DJANGO_LOAD_SAMPLE_DATA=true`, remove any custom sample data migrations
2. Open the devcontainer with this branch
3. F5 to run the Benefits app
4. Configuration: `ABC` with `Courtesy Cards`
5. User: `B2345678, Hernandez`
Notice output in the `server` Docker logs:
```console
+ bin/init.sh
+ python setup.py
+ nginx
+ python -m gunicorn -c /home/calitp/run/gunicorn.conf.py eligibility_server.app:app
[2022-09-01 23:56:09 +0000] [11] [INFO] Starting gunicorn 20.1.0
[2022-09-01 …
```
> Fix: local eligibility server

- benefits/enrollment/analytics.py
- benefits/enrollment/views.py
- tests/pytest/enrollment/test_views.py
closes #890 
Passes `eligibility.group_id` as `payment_group` into Amplitude for successful enrollment event
> feat(analytics): return Group ID with Returned Success

- benefits/eligibility/analytics.py
- benefits/eligibility/verify.py
- benefits/eligibility/views.py
- tests/pytest/eligibility/test_verify.py
Closes #874 
* On `eligibility:start`, send the requested types
* On `eligibility:success`, send the verified types
* On `eligibility:error` or `eligibility:fail`, send the requested types
> Feat: send eligibility type with eligibility events

- benefits/core/analytics.py
Part of #871, updates the event property in the app code.
Once in QA, we can update the tracking plan in Amplitude.
> Analytics: rename transit agency property

- benefits/core/viewmodels.py
- tests/pytest/core/test_viewmodels.py
Closes #913 
Added unit tests.
Fixed the bug by using `gettext_lazy` so that it's ok to set default arguments.
> Fix: error page translations

- .vscode/launch.json
- benefits/settings.py
Yes, really!
This PR adds a new VS Code *Run and Debug* configuration that:
* Launches the app with `DJANGO_DEBUG=False`
* Supports hitting breakpoints in the code
This is accomplished with a small override on the static files setting, which is only used for this debug config.
Useful for seeing and debugging error pages etc. more like how users see them.
> Devcontainer: debug in non-debug mode

- benefits/core/analytics.py
- tests/pytest/conftest.py
Closes #875
I noticed that `transit_agency` is also being sent as a user property, so I did the same with `eligibility_verifier`.
> Feat: track verifier in all analytic events

- benefits/core/middleware.py
- benefits/core/viewmodels.py
- benefits/core/views.py
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
- benefits/templates/200_user_error.html
- tests/pytest/core/test_viewmodels.py
- tests/pytest/eligibility/test_views.py
- tests/pytest/enrollment/test_views.py
Closes #914 (and closes #757 ?)
| Scenario | Before | After |
| --- | --- | --- |
| Navigate to a page earlier than you should | ![image](https://user-images.githubusercontent.com/25497886/191348910-a0bbd9ff-c50e-4658-a15f-a1af09af50b7.png) | ![image](https://user-images.githubusercontent.com/25497886/191349269-3989f90b-0078-4164-b07f-8831dac69ce2.png) |
| Page not found (404) | ![image](https://user-images.githubusercontent.com/25497886/191349025-973371e4-dd0b-4b38-9d04-30ea3c2ede3d.png) | ![image](https://user-images.githubusercontent.com/25497886/191349227-08b0a82e-d6ca-4f20-8305-c87db30fb30d.png) |
1. Launch benefits via the VS Code debugger (choose config with `Debug=False`) <img src="https://user-images.githubusercontent.com/25497886/191577383-f555a995-a11d-4bb1-957f-b8646a19110e.png …
> Refactor: error page layout and wording

- benefits/core/viewmodels.py
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
- tests/pytest/core/test_viewmodels.py
Closes #916 
Builds off changes from #914.
| Before | After | 
| --- | --- |
| ![image](https://user-images.githubusercontent.com/25497886/191375115-54f4ad55-b8e5-4acf-9f19-3c396c6dfa5e.png) | ![image](https://user-images.githubusercontent.com/25497886/191375088-dc2e37a0-f09e-4832-97f2-5f9e834039c4.png) |
> Refactor: 500 page

- benefits/core/templates/core/base.html
- benefits/core/templates/core/page.html
- benefits/core/viewmodels.py
- benefits/core/views.py
- benefits/eligibility/templates/eligibility/start.html
- benefits/eligibility/views.py
- benefits/enrollment/views.py
- benefits/static/css/styles.css
closes #933 
- Make all views with the Page view model use the one-column layout by setting `noimage` to `True`.
- Deletes CSS style code for `eligibility/start` page design (shortened image on top)
- `main-primary` class and css
- `one-column-image` class and css
- `with-image` (and `col-lg-6.image` class and css and jquery
- `noimage` from Page class and container template
- Test in Debug=False mode: Go through the whole flow in English/Spanish on Desktop and Mobile
- Ensure no regressions on /help
- Ensure no regressions on error pages: 404, 500
- http://localhost:11369/
- http://localhost:11369/eligibility/start
- http://localhost:11369/eligibility/
- http://localhost:11369/eligibility/confirm
- http://localhost:11369/enrollment/
- http://localhost:11369/enrollment/success
> One column everything

- benefits/core/templates/core/base.html
- benefits/settings.py
Closes #777
| Page | Before (mobile) | After (mobile) | Before (desktop) | After (desktop) | Notes |
| ----- | ------- | ------ | ----- | ---- | --- |
| `/eligibility/start` | ![image](https://user-images.githubusercontent.com/1783439/191872392-3a3464b9-2d68-426f-9426-8657eee30d64.png) | ![image](https://user-images.githubusercontent.com/1783439/191872443-4c34e589-0030-4305-a70f-6c66395675a9.png) | ![image](https://user-images.githubusercontent.com/1783439/191872631-fcac9f32-ca2c-4041-9d49-b59f401c9217.png) | ![image](https://user-images.githubusercontent.com/1783439/191872662-3d166908-370c-44f4-a69a-1bcf8256e6a2.png) | Increased gutter around icon/navbar on mobile |
| `/enrollment` | ![image](https://user-images.githubusercontent.com/1783439/191873184-19fa86ec-fc12-44a6-a78b-45a1ced7ebdd. …
> Chore: update State Template

- benefits/core/migrations/0002_sample_data.py
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
- bin/makemessages.sh
Following up to #958 - we actually don't need some of the sample data anymore. Also make the sample data we do need more closely align with production data for easier testing.
Part of #776
> Clean up sample data

- benefits/core/middleware.py
- benefits/core/migrations/0001_initial.py
- benefits/core/migrations/0002_sample_data.py
- benefits/core/models.py
- benefits/core/templates/core/agency_index.html
- benefits/core/templates/core/help.html
- benefits/core/templates/core/page.html
- benefits/core/viewmodels.py
- benefits/core/views.py
- benefits/eligibility/views.py
- benefits/enrollment/views.py
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
- tests/pytest/conftest.py
- tests/pytest/core/test_viewmodels.py
- tests/pytest/eligibility/test_views.py
Closes #962 
Covers some intent from #776
> Chore: rename content_title to headline

- benefits/core/templates/core/base.html
- benefits/core/templates/core/widgets/radio_select_option.html
- benefits/static/css/styles.css
part of #971
- Set body `<p>` size to 18px for all browser widths/sizes
- Goes through the whole app and makes sure the `<p>` elements are set as such
- Does not yet add a set margin/padding-top/bottom to all `<p>` yet. To come in future PRs.
- Set standard colors, underlines for `<a>` links that are not `.btn`s
All of the un-bolded paragraphs in these screenshots are proper `<p>`s:
> Refactor: CSS Variables - Paragraph style and links

- benefits/core/views.py
- tests/pytest/core/test_views.py
Closes #976... Although I realized in doing this that, it doesn't actually matter? We'll have a single agency with multiple verifiers, so this check would have failed anyway.
Oh well, it's dead code, so fine to remove.
> Refactor: remove agency index pass-thru

- benefits/core/templates/core/agency_index.html
- benefits/core/templates/core/includes/form.html
- benefits/core/templates/core/widgets/radio_select_option.html
- benefits/eligibility/templates/eligibility/start.html
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/static/css/styles.css
closes #971 
- Add styles for all `h1`, `h2`, `h3` and back-up CSS classes for `h2`, `h3`
- Set up responsive CSS variables for `h1`: `h1` changes font-size when the screen width gets wider
- Write the font styles in mobile-first mode: Meaning, create media queries for the wider screen widths and set the default to the mobile width
- Delete CSS styles that were declaring font sizes that are now taken care of with the proper h1, h2, h3 declaration
- Delete all margins/padding from `container.content`. Set all margin/padding on `container.content` to 0.
- Adds `padding-top` of 70px to H1
- I set `body` to 18px, which is 1.125em. That's calculated with: 18/16=1.125.
- I used the same formula to get the em sizes for the h1, h2 and h3. 
- Margin is set to zero for all headlines
- `<h1>`: Font …
> CSS Variables: Responsive headlines

- .github/workflows/codeql.yml
Avoids running this long-running job on _every commit_ for pure front-end HTML/CSS, language file updates, and other non-code scenarios
> Chore: only run CodeQL for javascript/python

- .github/workflows/codeql.yml
Following up from #1018, adding filters to the `on.pull_request` event.
> Chore: only run CodeQL for .js/.py on pull_request

- benefits/core/templates/core/base.html
- benefits/static/css/styles.css
closes #974 
- Fixes: Fixes the current issue where on Desktop, the footer is not neatly at the bottom of the page on first load for pages that don't fill up the full viewport height.
- Redesigns: The footer height is now 50px on Desktop. The footer is slightly taller now on Desktop.
- Fixes: The type (leter-spacing, font-weight) for the footer was off. Now it's not.
- Deletes all old CSS code that tried to place the footer.
- Moves around CSS styles into categories and comments them.
- Mobile: Footer should have no regressions
- Desktop: Go through short pages (agency index) - Footer should be at the bottom. 
- Desktop: Go through long pages (help, eligibility start) - Footer should have no regressions.
- Test the app in Private mode or a different browser to test the `visited` color …
> CSS Variables: Refactor footer sizing and alignment

- benefits/core/templates/core/base.html
Closes #961 
This PR defines a grid on `base.html` with blocks that other templates can "fill in". If a page wants to completely ignore the grid, it can do so by overriding the `main_content` block, but it should only do this if it truly is completely different from all other pages.
- #1009
- Port over templates that contain forms which need to render their own button
- Implement CSS for spacing between sections according to 8px-based design system
- Add support for error pages and port over
- See if Help page can use the grid
- Implement CSS for making buttons have `width: 100%`
<details>
**Agency Index**
**Verifier Selection**
**CC Eligibility Start**
**Login.gov Eligibility Start**
**CC Eligibility Confirm**
**CC Enrollment Connect Card**
**CC Eligibility Unverified**
**Login.gov …
> Refactor: base grid

- docs/use-cases/courtesy-cards.md
As part of https://github.com/cal-itp/eligibility-server/issues/158, I wanted to put together a high-level architecture diagram, so figured that was a good excuse to start a Use Case page. Going to drop a screenshot in that writeup; no strong feelings about whether we merge this now or wait until we launch.
> add Use Case around Courtesy Cards

- benefits/core/templates/core/includes/previous-page-link.html
- benefits/core/templates/core/includes/sign-out-link.html
- benefits/enrollment/views.py
- benefits/static/css/styles.css
closes #920 
- Fixes the #920 mobile bug by setting the Sign Out button at a static height
- Creates a generic `nav-button-row` class with a height of `70px`, that both Previous Page and Sign Out button templates can use. This row is an absolutely-positioned div that starts at the bottom of the Header and does not affect H1 height/positioning.
- Positions the `Sign Out Button` using flex-box (vertically aligned, justified to the end), rather than setting a pixel padding top
- This PR also removes the padding left/right on the Header on mobile, so the Cal-ITP logo is closer to aligning with the buttons.
- This PR currently adds a few `!important` font declarations because the Sign Out button styles don't have underlines like the style guide's regular links do. Could use refactoring in the …
> Fix: Sign out row bug

- benefits/core/templates/core/includes/media-list.html
- benefits/eligibility/templates/eligibility/start.html
- benefits/static/css/styles.css
fixes #1021 
This time, this PR only adds padding logic to the Media List.
- Fixes the lack of padding between paragraphs in a Media Item. There are several Media Items that now have more than one paragraph. Check Enrollment and Enrollment Success.
- Fixes the lack of padding between an H1 and a Media List. This applies to Media Lists that DO NOT have a Media Title. The Eligibility Start has its own special Media Title, whereas, Enrollment and Enrollment Success do not.
- Adds 1 CSS declaration/style
- Adds comments to explain how and where this is used
- `+` Adjacent sibling combinator https://developer.mozilla.org/en-US/docs/Web/CSS/Adjacent_sibling_combinator
- `:not` https://developer.mozilla.org/en-US/docs/Web/CSS/:not
- `:first-of-type` …
> Fixes: Media List spacing

- benefits/core/templates/core/includes/media-list.html
closes #1047
- It uses `mx-0` instead of `m-0` so that the `margin-bottom: 64px;` on Media List still works. 
- The spacing between the bottom of the last Icon and the first Button should be 64px on both Desktop and Mobile
eligibility/start
enrollment
enrollment/success (there is no button here, so there's no visual difference. ensure no regressions here)
> Fix: Allow margin-bottom for media-list

- benefits/eligibility/templates/eligibility/start.html
fixes #1050 
On mobile, two left screens should now have the same padding between the button and the help text, just like Eligibility Index.
> Fix: Eligibility Start - Mobile: Add padding top between help text and button

- benefits/enrollment/templates/enrollment/index.html
- benefits/static/css/styles.css
fixes #1049 
- Use `pb-lg-8 pb-4` to add 24px padding on Mobile, 64px padding on Desktop between the H1 and the Media List on Enrollment Index
> Fix: Enrollment Index - Add H1 padding

- bin/build.sh
Fixes https://github.com/cal-itp/benefits/issues/989.
@machikoyasuda Mind confirming this solves the issue for you, without having to [disable BuildKit in the settings](https://github.com/docker/compose/issues/8449#issuecomment-1017542165)?
> add workaround for BuildKit issue on Apple M1 hardware

- benefits/core/templates/core/widgets/verifier_radio_select.html
- benefits/core/templates/core/widgets/verifier_radio_select_option.html
- benefits/static/css/styles.css
fixes #1046 
- Change the element make up of the radio button: The `label` now has two `span`s in it, (rather than one `paragraph`), to be HTML5 validator compliant.
- Change how the elements are positioned and aligned. Currently, the radio button is positioned with relative positioning. Now, it uses flexbox: The parent div that holds the Radio Button and the Label parent is now displayed with flex, with a `gap` of `var(--radio-input-gap)`, set as `40px` on Mobile and `15px` on Desktop.
A margin of 3px top/bottom is given to the Radio Button (24px button + 6px total margin = 30px), so that it aligns with the first row of text on the Label (30px high when label is 1 one line):
```css
/* Forms: Radio Buttons */
:root {
--radio-button-size: 24px;
--radio-input-color: var(--standout-color); …
```
> Fix: Radio button positioning, elements

- benefits/settings.py
It is not a valid Content Security Policy to specific both 'none' and a list of other domains in the frame-src directive.
Closes #1066, also related to #935
> Fix: overwrite frame-src when needed

- benefits/core/templates/core/help.html
- benefits/core/templates/core/includes/agency-links.html
- benefits/core/templates/core/includes/icon-title.html
- benefits/core/templates/core/page.html
- benefits/eligibility/templates/eligibility/unverified.html
- benefits/eligibility/views.py
- benefits/enrollment/templates/enrollment/retry.html
- benefits/static/css/styles.css
- benefits/templates/200_user_error.html
- benefits/templates/400.html
- benefits/templates/404.html
- benefits/templates/500.html
fixes #972 
fixes #512 
- Use `base.html` for Help, 200, 400, 404, 500, Unverified (eligibility/unverified), Retry (enrollment/retry)
- Agency Links include: Removes the Back button from this includes
- Removes Agency Links include from Page
- Removes `with-agency-links` CSS logic
- For Agency Links, it does do everything in this ticket #512 - but further changes / future ticket is necessary to remove these lines: https://github.com/cal-itp/benefits/pull/1042/files#diff-1a4430de237c046c679071ef0d2a5b267007651b8fa1c42e755f0a1cea4d469cR2 https://github.com/cal-itp/benefits/pull/1042/files#diff-32d0e53bd73778cc6c0437f522dd3269a366d343d321f0d9eee21d3ec3d4d166R20 (Probably needs a ticket to refactor the Page view model to make it easier to pass in the agency links differently from a Back …
> Fixes: Buttons on Help, 200, 400, 404, 500, Unverified, Retry

- benefits/core/context_processors.py
- benefits/core/middleware.py
- benefits/core/recaptcha.py
- benefits/core/templates/core/base.html
- benefits/core/templates/core/includes/form.html
- benefits/eligibility/forms.py
- benefits/eligibility/views.py
- benefits/enrollment/forms.py
- benefits/settings.py
- tests/pytest/eligibility/test_views.py
Fixes #1068 
Based on an answer to this SO post: https://stackoverflow.com/q/41665935/453168
This is the main issue being solved. reCAPTCHA v3 supports two options:
* [Automatically bind the challenge to a button](https://developers.google.com/recaptcha/docs/v3#automatically_bind_the_challenge_to_a_button) (existing implementation)
* [Programmatically invoke the challenge](https://developers.google.com/recaptcha/docs/v3#programmatically_invoke_the_challenge) (new implementation in this PR)
Using a programmatic challenge allows the browser's HTML5 form validation a chance to kick-in before reCAPTCHA's checks,
which isn't possible with the challenge button auto-bind.
Before we used a [Django context processor](https://docs.djangoproject.com/en/4.1/ref/templates/api/#writing-your-own-context- …
> Fix: reCAPTCHA + HTML5 form validation

- benefits/static/css/styles.css
related to #778
- Test the app in 200% on Chrome, Firefox, Safari on Desktop - Everything should be clickable/not blocked
- Test the app in 200% on mobile browsers - Everything should be clickable/not blocked
- @angela-tran What other kind of testing should we be doing for this check?
Reference: https://dev-benefits.calitp.org/help
> Fix: Use rem calculation for 18px font

- benefits/core/migrations/0001_initial.py
- benefits/core/migrations/0002_sample_data.py
- benefits/core/models.py
- benefits/eligibility/forms.py
closes #1060 
- Allow the user to use numeric keyboard for the sub input on mobile
- Add a 5-character max length for the sub input
- Adds `form_input_mode` (String), `form_max_length` (Integer)
- Form input mode must be one of these strings: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode#values
- Max length: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/maxlength
- Sets `form_inputmode` to `numeric` and `form_max_length` to 5 for the MST_CC sample data eligibility verifier
- Test that the rest of the forms don't have any regressions
- Use iOS Simulator (on XCode on Mac) (or any other Windows tool?) to see if the numeric input opens on the sub field
- Test that the regex validation still works
- Regex still works:
- iOS keyboard: Numeric for …
> Feat: Add numeric keyboard/maxlength 5 to sub input

- benefits/core/templates/core/base.html
- benefits/core/templates/core/help.html
- pyproject.toml
closes #935 
- Adds image dimensions to HTML as numbers, not pixels. Pixels is wrong.
- Changes the lang selector from a span to a div. It should not be a span.
- Adds back 2 linter rules that we are not 100% compliant with.
- Should address all ERROR level feedback from HTML5 validator: https://validator.w3.org/nu/?doc=https%3A%2F%2Fdev-benefits.calitp.org%2Fmst
- Should address/attempt to address all Issues on Google Chrome DevTools: https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1665691993150-92376.report.html
> Audit: Run the site through Lighthouse, HTML5 Validator

- benefits/static/css/styles.css
closes #778 
I had forgotten one line of CSS in yesterday's PR: https://github.com/cal-itp/benefits/pull/1062
When the browser's default font size is set to 32px:
| Before     | After     |
| --------  | -------- |
| <img width="1512" alt="image" src="https://user-images.githubusercontent.com/3673236/197831785-233412ab-245f-4bda-8313-cf28b260e64e.png">  | <img width="1512" alt="image" src="https://user-images.githubusercontent.com/3673236/197831807-6e93c970-efae-4170-a1f2-f450c09c45e9.png"> |
| 12px     | calc(12rem / 16)     |
> fix(css): use rem for 12px font size

- benefits/core/analytics.py
- benefits/core/models.py
- benefits/eligibility/analytics.py
- benefits/eligibility/verify.py
- benefits/eligibility/views.py
- tests/pytest/core/test_analytics.py
- tests/pytest/core/test_models.py
- tests/pytest/eligibility/test_analytics.py
- tests/pytest/eligibility/test_verify.py
- tests/pytest/eligibility/test_views.py
Closes #342 
Closes #926
This event is sent when the user submits the form on `/eligibility/index` page (the "benefit selection" form). It includes an event property `eligibility_verifier` identifying which was selected.
**Note** the event is _not sent_ when there is only a single `EligibilityVerifier` configured in the app. In this case, the user is never presented with the selection form. This is an unlikely scenario given that we are launching the new events with the Courtesy Card feature and alongside the existing Older Adults pathway.
This PR adds the `eligibility_types` event property (a list of zero or more type names) for _all analytics events_ by adding it to the base `core.analytics.Event` class. The value is initially pulled from the user's session.
Events using the …
> Improvements to Eligibility events

- terraform/monitor.tf
- terraform/uptime.tf
Split out from https://github.com/cal-itp/benefits/pull/1074.
"dev" gets used as an environment name, and the team is more regularly referred to as "Engineering" anyway. Just a refactor.
> rename the email resource

- terraform/app_service.tf
These were set in the Azure portal. We just need to update Terraform to match.
> Chore(terraform): allow configuring recaptcha for separate slots

- terraform/app_service.tf
We were getting noise in our `terraform plan` due to Azure fighting with Terraform about what order this array should be in. This should help.
> chore(Terraform): sort app service settings

- terraform/app_service.tf
It was happening on dev and test as of https://github.com/cal-itp/benefits/pull/821; this adds it to production.
> manage production storage account binding in Terraform

- benefits/static/css/styles.css
Two requests from @srhhnry 
1. Make Agency Index page show more of the background image on very small phones (iPhone SE): Increased the minimum height of the container to show more image for mobile only:
Compared with on Dev
> Agency Index: Mobile edit from Design

- docs/use-cases/courtesy-cards.md
Include [`hashfields`](/cal-itp/hashfields) and the SQL Server to show how data flows to Azure
> Docs: update Courtesy Card diagram

- docs/deployment/infrastructure.md
Wanted to make sure we had a written understanding of the DevSecOps team's desired naming conventions for use with new resources. This just writes it down; we will work to match them in https://github.com/cal-itp/benefits/issues/1077.
> chore: document DevSecOps Azure naming conventions

- benefits/static/css/styles.css
closes #1079 
- For specific UI components, convert the pixel measurements to rems, using `calc(##rem / 16)`
- Radio button component: Mobile distance between radio button text has been reduced from 40px to 24px.
- Components that are not converted: Button measurements that control button height, button width. Button font size _does_ use rems. Button width will remain controlled by Bootstrap column percentages. Button heights will remain static pixels. 
- Components that are not converted: Footer height, Header height are not converted to rem. Rationale: There is possible upcoming Header style changes. The Footer/Header heights are fine for now as the content within the footer/header are not getting blocked or have any other visual/user interaction issues.
- Change browser font size to 32 …
> Make the app work at 200% zoom/double the font size

- .github/dependabot.yml
- .pre-commit-config.yaml
Two small chores to improve the DevX:
* Closes #1059 to streamline the commit process
* Closes #1078 to keep the PR noise down
> Chore: Improve developer experience

- benefits/core/templates/core/includes/form.html
> Fix: custom submitting event for form button effects

- benefits/core/templates/core/base.html
- benefits/settings.py
Closes #1113 
We weren't actually using anything from the `cagov.core.js` JavaScript from the CA State Template. This PR removes our reference to that file to stop the flood of JS console errors.
Instead we reference Bootstrap directly via CDN, as we do make use of Bootstrap features and likely will use more in future iterations.
Also updates jQuery:
* To use the same CDN we use for Bootstrap, simplifying the Content Security Policy (CSP)
* From `3.6.0` to `3.6.1` -- minor update with bugfixes
Tested thoroughly with all flows with reCAPTCHA enabled:
* CC verified + enrollment
* CC unverified
* Login verified + enrollment [+ sign out]
* Login unverified [+ sign out]
> Fix: replace State Template JS with Bootstrap

- .devcontainer/server/settings.py
- .github/workflows/tests-feature.yml
- benefits/core/migrations/0002_sample_data.py
- compose.yml
This PR updates Benefits to use eligibility-server's `dev` image and branch.
See cal-itp/eligibility-server#169
> Chore: eligibility-server dev image and branch

- .devcontainer/server/settings.py
The `main` branch of `eligibility-server` was deleted in cal-itp/eligibility-server#186. 
#1122 missed these references.
> Fix: sample server key files

- .vscode/settings.json
- terraform/azure-pipelines.yml
Split out from https://github.com/cal-itp/benefits/pull/1074. Part of #803.
While we aren't currently using any variables in our pipeline, when we've introduced them in the past and not had them set in the pipeline, runs end up hanging until they time out. This will avoid that problem going forward.
> chore(pipeline): don't wait for input to Terraform

- terraform/app_service.tf
Noticed them in [this pipeline run](https://calenterprise.visualstudio.com/CDT.OET.CAL-ITP/_build/results?buildId=37917&view=logs&j=e2b2897c-f736-5615-5c9c-c20ddcd4aa73&t=2ab79bdb-a159-573f-a6a0-2465f94c501e&l=78).
> fix(Terraform): add missing sticky settings

- docs/deployment/infrastructure.md
- terraform/monitor.tf
Split out from https://github.com/cal-itp/benefits/pull/1074.
> docs(infrastructure): document missing environment setup steps

- docs/deployment/infrastructure.md
- terraform/app_service.tf
- terraform/key_vault.tf
Closes #704.
Per DevSecOps email 10/27/22:
> Front Door TLS/SSL offload terminates the TLS connection … connections to the backend happen over the public IP
I also removed the bindings from all slots and they continued to work. Therefore, the wildcard certificate isn't actually used by App Service.
> chore(terraform): remove certificate binding

- .devcontainer/devcontainer.json
- .vscode/settings.json
Closes #341.
This extension provides a basic GUI into the Django database for debugging purposes:
> Feat: add sqlite-viewer extension to devcontainer

- .gitignore
- docs/deployment/infrastructure.md
- docs/deployment/troubleshooting.md
- docs/deployment/workflows.md
- terraform/README.md
- terraform/app_service.tf
- terraform/azure-pipelines.yml
- terraform/environment.tf
- terraform/init.sh
- terraform/key_vault.tf
- terraform/main.tf
- terraform/monitor.tf
- terraform/network.tf
- terraform/pipeline/deploy.yml
- terraform/pipeline/workspace.py
- terraform/storage.tf
- terraform/uptime.tf
Closes #830. Running list of TODOs:
- Our permissions are limited on Key Vaults so have been trying to work around that
> Error: retrieving Subnet: (Name "SNET-CDT-PUB-CALITP-D-001" / Virtual Network Name "VNET-CDT-PUB-SHRD-W-D-001" / Resource Group "RG-CDT-PUB-SHRD-W-D-001"): network.SubnetsClient#Get: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'live.com#aidan@compiler.la' with object id \[REDACTED\] does not have authorization to perform action 'Microsoft.Network/virtualNetworks/subnets/read' over scope '/subscriptions/\[REDACTED\]/resourceGroups/RG-CDT-PUB-SHRD-W-D-001/providers/Microsoft.Network/virtualNetworks/VNET-CDT-PUB-SHRD-W-D-001/subnets/SNET-CDT-PUB-CALITP- …
> separate infrastructure environments

- docs/deployment/troubleshooting.md
- terraform/output.tf
Will make it easier to copy the values into the Eligibility Server pipeline configuration.
> chore(Terraform): output the outbound IP ranges

- .github/workflows/tests-pytest.yml
#1174 is stuck waiting on our required `pytest` check. 
The workflow needs to have `pull_request` as a trigger for it to run on pull requests from forks (see nasa/cFS#169 for more details).
> Chore: add pull_request trigger to pytest workflow

- .github/workflows/check-api.yml
Was looking at https://github.com/cal-itp/benefits/issues/832#issuecomment-1323080591 after [the Payments Data team also came up with the failure scenario](https://docs.google.com/spreadsheets/d/1f1-fM7wJvxCUWvgzaq02Cyr_kPb5ubfCS64wnhZ5wWk/edit#gid=584616034) of the Littlepay API being down, and I realized this would be easy to resolve.
> fix(CI): send API check failure notifications to Slack

- benefits/eligibility/views.py
- tests/pytest/eligibility/test_views.py
Closes #1200 
Unit test was updated and passes. To test in the browser, update your sample data so that `mst_agency` only has one verifier.
> Chore: always show the user the eligibility index

- benefits/core/migrations/0002_sample_data.py
Related to #1163 
This PR modifies the sample data migration file to look for environment variables for sensitive values, falling back to defaults if an environment variable is not defined. 
This is to help move us towards actually using this file for our deployment process. Note that these changes do not break any of the current set up in Azure (since it's not using the sample data) nor does it break local dev environments (no `.env` file required).
As an example, you could fill this out to specify real values and add to a `.env` file:
```
AUTH_PROVIDER_CLIENT_NAME=
AUTH_PROVIDER_CLIENT_ID=
AUTH_PROVIDER_AUTHORITY=
AUTH_PROVIDER_SCOPE=
AUTH_PROVIDER_CLAIM=
```
Run
```bash
set -a
source .env
./bin/init.sh
``` 
and you should then be able to go through the Login.gov flow without changing …
> Refactor: add support for env variables in data migration

- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
Feedback from the demo yesterday was to change "SacRT bus" to "SacRT public transportation" and to check Spanish translations for new copy changes.
Paired with @srhhnry to make these changes and close #1210.
> Update SacRT copy, and add Spanish translations

- benefits/core/views.py
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
> Refactor: agency index msgid

- benefits/static/css/styles.css
Closes #1219 
This PR sets a max-width and min-height for cards shown on the agency selector modal. I also fixed some units to be `rem`-based.
| Desktop | Mobile |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/25497886/215583903-d37b2ccd-8d6e-4c7d-8997-d86e46b6af06.png) | ![image](https://user-images.githubusercontent.com/25497886/215583839-78ed8555-d35e-4053-a77a-4aa0040c9924.png) |
| Desktop | Mobile |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/25497886/215583990-ade5a588-2bdf-46c8-b5e2-f5bf2c91d1c4.png) | ![image](https://user-images.githubusercontent.com/25497886/215584067-16c57032-39f1-476f-af3e-d63d1ecb114b.png) |
| Desktop | Mobile |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/25497886/215584361-9f7a7b78-aac7-431a-8 …
> Fix: agency selector with n cards

- benefits/eligibility/analytics.py
- tests/pytest/eligibility/test_analytics.py
Closes #1228 
Changes the base `EligibilityEvent` to always set the `user_properties` with new `eligibility_types`, in addition to the `event_properties`.
Updated the tests as well.
See https://github.com/cal-itp/benefits/issues/1228#issuecomment-1411075074 for resolution on the other (OAuth) event issue.
> Fix: eligibility types in events

- docs/deployment/infrastructure.md
Noticed this while looking at the docs. I _think_ this brings it up to date.
> fix(docs): add missing system interconnections to architecture diagram

- docs/configuration/.pages
- docs/configuration/data.md
- docs/configuration/transit-agency.md
Closes #309 
This PR adds technical documentation on the steps needed to add a new transit agency to Benefits.
> Docs: configuring a new transit agency

- docs/deployment/infrastructure.md
Closes https://github.com/cal-itp/benefits/issues/1237.
Open to ideas for naming/describing things differently. The automatic layout from Mermaid isn't _great_; unfortunately have very limited control.
> chore(docs): show what data is exchanged/stored where

- .devcontainer/devcontainer.json
Was getting this warning:
View the change [ignoring whitespace](https://github.com/cal-itp/benefits/pull/1257/files?diff=unified&w=1).
> fix(devcontainer): use new VSCode settings/extensions configuration format

- docs/configuration/environment-variables.md
- docs/deployment/infrastructure.md
- docs/deployment/troubleshooting.md
Closes https://github.com/cal-itp/benefits/issues/1191.
> copy in information that came up in the failure screnarios

- appcontainer/requirements.txt
- benefits/core/middleware.py
- benefits/settings.py
Fixes https://github.com/cal-itp/benefits/issues/861.
I had initially thought there was an issue with OpenCensus compatibility overall, but it appears the (remaining) problem was with our custom middleware. Set the `APPLICATIONINSIGHTS_CONNECTION_STRING` locally and was able to see errors show up in Azure:
> fix Azure exception handling

- benefits/static/css/styles.css
fix #1213 
- For the landing page on mobile, set the height of the main container to 100vh - 80px (header height). 
- The footer should be the only thing "under" the scroll now on mobile
> Fix: Landing Page - Decrease main container height on mobile

- appcontainer/requirements.txt
- benefits/sentry.py
- benefits/settings.py
- benefits/urls.py
- docs/configuration/environment-variables.md
- docs/deployment/troubleshooting.md
Part of #1258. Closes https://github.com/cal-itp/benefits/issues/733.
Adds Sentry error and performance monitoring. [Sample Issue captured by Sentry.](https://sentry.calitp.org/organizations/sentry/issues/39931/)
Doesn't touch the Azure Monitor integration.
> chore: set up Sentry

- benefits/sentry.py
I guess I didn't test this case, where `git` is available but we're not in a repository, which is the case in App Service.
> fix(Sentry): handle cases where Git is available but we're not in a repository

- .github/workflows/tests-ui.yml
Discovered this was possible as part of https://github.com/cal-itp/benefits/pull/1263.
> chore(CI): simplify starting client for UI tests

- docs/README.md
I did so for #1256, and while the original intention wasn't to use that content for the docs, figured we might as well. The Benefits site itself could be a good eventual home for a plain language version, as noted in https://github.com/cal-itp/benefits/issues/1273#issuecomment-1430430202; I think this version is a good level of technical for the Home section of the docs.
> docs: add security overview

- .gitignore
- benefits/sentry.py
- tests/pytest/test_sentry.py
As requested in https://github.com/cal-itp/benefits/pull/1275#pullrequestreview-1299947900. Given that code calls out to the `git` executable and filesystem so much, a lot needs to be mocked, so not sure these tests add a lot of value 🤷 Coverage:
Generated with
```sh
pytest --cov=benefits --cov-report=html tests/pytest/test_sentry.py
open htmlcov/index.html
```
> add tests for Sentry revision code

- .github/dependabot.yml
- .github/workflows/tests-feature.yml
- benefits/core/migrations/0002_sample_data.py
- benefits/core/migrations/sample_agency.json
- benefits/settings.py
- docs/tests/README.md
- tests/cypress/fixtures/README.md
- tests/cypress/fixtures/transit-agencies.js
- tests/cypress/fixtures/users.json
- tests/cypress/package-lock.json
- tests/cypress/package.json
- tests/cypress/specs/feature/eligibility.cy.js
- tests/cypress/specs/feature/rate-limit.cy.js
Fixes https://github.com/cal-itp/benefits/issues/340.
Gets the feature tests working again, and sets them to run on every `push` in CI.
> fix feature tests

- benefits/core/middleware.py
- benefits/settings.py
- docs/configuration/environment-variables.md
- tests/pytest/core/test_middleware_healthcheck_user_agent.py
The unit test no longer needs to set up TransitAgencies for the index view anymore.
> Fix: adapt test for healthcheck user agents

- docs/configuration/environment-variables.md
While updating documentation for #1242, I noticed some broken links and that a call-out was not formatted correctly.
| Description | Screenshot |
| --- | --- |
| Broken Links | ![image](https://user-images.githubusercontent.com/25497886/220697763-fcd72c1d-3fb1-4b49-b4d9-8936f246d215.png) |
| Incorrectly formatted call-out | ![image](https://user-images.githubusercontent.com/25497886/220697870-e907fbe6-570d-455c-acb8-2759b14ca526.png) |
This PR fixes those two issues.
> Fix: small issues on environment variable docs

- .github/ISSUE_TEMPLATE/incident-response.md
Closes #833.
I kept it somewhat minimal, leaving out formalities such as the [assigning of roles](https://handbook.login.gov/articles/secops-incident-response-guide.html#initiate). I also tried to keep instructions in the issue and short, rather than creating yet another page that needs to be read.
> chore: add incident response checklist

- benefits/core/migrations/0002_sample_data.py
- docs/deployment/.pages
- docs/deployment/secrets.md
- terraform/secrets/README.md
- terraform/secrets/file.sh
- terraform/secrets/value.sh
Closes #1242 
Secret values from our `dev`, `test`, and `prod` data migrations have been added to their respective Key Vaults in Azure.
From [Azure docs](https://learn.microsoft.com/en-us/azure/key-vault/secrets/quick-create-portal#add-a-secret-to-key-vault):
> The secret name must be unique within a Key Vault. The name must be a 1-127 character string, starting with a letter and containing only 0-9, a-z, A-Z, and -.
So the naming convention I used is to take the environment variable name, replace `_` with `-`, and make all characters lowercase.
Our sample data migration file was missing a few environment variables that we need for values in our real data migrations, so I added them in this PR.
I also added documentation on how to set secrets in Key Vault and some helper scripts for …
> Feat: set Key Vault values

- terraform/.terraform.lock.hcl
- terraform/key_vault.tf
For some reason, this is enabled on the resource in Azure but was not represented in Terraform. That caused the recent pipeline build to fail.
This PR also updates the Terraform lock file.
> Fix: represent Key Vault purge protection in Terraform

- docs/deployment/infrastructure.md
- docs/deployment/secrets.md
- docs/getting-started/README.md
- terraform/app_service.tf
- terraform/environment.tf
- terraform/secrets/read.sh
Closes #1116 and closes #1241
This PR specifies our app settings as code. Settings with secret values make use of Azure Key Vault references.
All data migration secrets have been added to the Key Vaults for `dev`, `test`, and `prod`.
The settings that used to be manually configured on our app services (e.g. Django settings, Azure Docker settings, etc.) have been added to the `dev` Key Vault.
> Feat: specify app settings as code

- docs/deployment/release.md
Best practice is to only push a single tag, and not all tags.
> Docs: update steps for pushing tags

- terraform/app_service.tf
Part of #1244 
This PR removes the file mount path from the App Service.
I checked over documentation, and it does not contain any mention of the blob container or file mount path anywhere.
> Refactor: delete now unneeded Azure file mount

- docs/configuration/README.md
Closes #1245 
This PR adds a line to the Configuration README so that the link between secrets and configuration is more obvious.
Not much change was needed here because the documentation updates from #1294 and #1311 cover the new workflow thoroughly.
Let me know though if there is anything that we want more documentation on.
> Docs: configuration data uses env vars/secrets

- benefits/sentry.py
Closes #1340 
This PR configures a custom denylist on our `EventScrubber`, with `sub` and `name` as the additional entries.
> Fix: configure Sentry denylist

- docs/use-cases/courtesy-cards.md
I noticed the internal link to the Deployment: Infrastructure page is broken on the Courtesy Card use case page https://docs.calitp.org/benefits/use-cases/courtesy-cards/
Link should go tohttps://docs.calitp.org/benefits/deployment/infrastructure/#architecture instead of https://docs.calitp.org/benefits/use-cases/deployment/infrastructure/#architecture
> fix(url): fix broken link in docs

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/requirements.txt
- .dockerignore
- .github/dependabot.yml
- .github/workflows/labeler-deploy-dev.yml
- .github/workflows/tests-pytest.yml
- appcontainer/Dockerfile
- appcontainer/requirements.txt
- pyproject.toml
- tests/pytest/requirements.txt
> Refactor: move dependencies and metadata to pyproject.toml

- benefits/core/templates/core/base.html
- benefits/core/templates/core/includes/analytics.html
- benefits/core/templates/core/includes/form.html
- benefits/enrollment/templates/enrollment/index.html
- benefits/sentry.py
- benefits/settings.py
- docs/configuration/content-security-policy.md
- docs/configuration/environment-variables.md
- terraform/app_service.tf
Closes #212 
Also adds a new environment variable to configure the CSP `report-uri` [Report Directive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy#reporting_directives).
_Note: `report-uri` is being deprecated in favor of `report-to`, but the latter lacks full browser support at this time. See above MDN link for more._
This can be used to send CSP violation reports to Sentry, which has out of the box support for [Security Policy Reporting](https://docs.sentry.io/product/security-policy-reporting/).
> Feat: Implement strict Content Security Policy

- benefits/settings.py
Accidentally removed as part of #1358, but this is needed for payment processor overlay window.
According to https://csp.withgoogle.com/, the more critical piece of strict CSP is `script-src`, which disallowed `unsafe-inline` as part of #1358.
> Fix: allow unsafe-inline for style-src

- benefits/sentry.py
- docs/configuration/environment-variables.md
- terraform/app_service.tf
- tests/pytest/test_sentry.py
Related to #1359 and this [Slack thread](https://cal-itp.slack.com/archives/C044UUY78TB/p1681423801273219), more work to reduce unnecessary traffic we send to Sentry.
This PR introduces an environment-specific configuration for the Sentry [`traces_sample_rate`](https://docs.sentry.io/platforms/python/configuration/sampling/#configuring-the-transaction-sample-rate) setting using our standard environment variable / key vault pattern.
The new default is `0.0`, so this has to be turned on explicitly. Before we were hard-coding to `1.0` (i.e. send 100% of transactions) in all environments.
This is temporarily on top of #1358 because that PR also introduced a new Sentry config, though otherwise unrelated.
> Fix: Configurable traces sampling rate for Sentry

- appcontainer/nginx.conf
- tests/cypress/specs/scrapers.cy.js
Follow up to #1359 - these paths were missed in local and `dev` QA!
> Fix: relax the 404 filter

- terraform/storage.tf
I missed this code when doing https://github.com/cal-itp/benefits/issues/1244. This container was used to hold configuration (data migration) file and is no longer needed.
> Chore: delete unneeded storage container

- .github/ISSUE_TEMPLATE/release.yml
- docs/deployment/release.md
Closes #1333 
Closes #1284
This PR updates the release issue template to include steps for ensuring secrets are up to date when releasing / deploying the Benefits app. 
To simplify the flow of steps, we split the checklist out into two checklists, one for each type of release (Regular and Hotfix).
This PR also updates documentation on "Making a release" to reflect our hotfix checklist.
> Chore: update release template

- benefits/core/templates/core/help.html
- benefits/core/templates/core/includes/agency-links.html
- benefits/core/viewmodels.py
- benefits/core/views.py
- benefits/eligibility/templates/eligibility/unverified.html
- benefits/eligibility/views.py
- benefits/enrollment/templates/enrollment/retry.html
- benefits/enrollment/views.py
Closes #1054 
This PR implements the proposed solution on the ticket so that for the three pages that show agency links (help, unverified, and retry):
- we remove the [`{% if "agency" in agency_button.classes %}`](https://github.com/cal-itp/benefits/pull/1042/files#diff-1a4430de237c046c679071ef0d2a5b267007651b8fa1c42e755f0a1cea4d469cR2) check
- we remove the [`{% if "btn-primary" in back_button.classes %}`](https://github.com/cal-itp/benefits/pull/1042/files#diff-32d0e53bd73778cc6c0437f522dd3269a366d343d321f0d9eee21d3ec3d4d166R20) check
`/help` and `/unverified` are easy to test by going through the flow (use Courtesy Card with ineligible user credentials).
To test the `/enrollment/retry` view, you can modify the code as follows. Then, make sure to populate an agency in your session …
> Refactor: agency links context

- pyproject.toml
See https://github.com/cal-itp/eligibility-api/releases/tag/2023.06.01
Related to https://github.com/cal-itp/eligibility-server/pull/263
> Chore: update to latest eligibility-api

- bin/makemigrations.sh
Closes #1437 
Modifies the formatting command so that it only applies to Python files.
> Fix: migrations formatting

- benefits/core/migrations/0002_data.py
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
fix #1463 
- Corrects the `enrollment_success_confirm_item_details` value for Veteran's EligibilityVerifier
- Uses Enrollment Success copy _from what is on Production and already translated - ***not*** what is on Figma currently_ for the time being. Updating the Enrollment Success copy with the new variables is not part of this ticket.
> Fix: Veterans - Enrollment Success: Add msgid for Veterans copy

- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
- benefits/static/css/styles.css
- tests/cypress/plugins/helpers.js
- tests/cypress/specs/help.cy.js
#1483 
There have been app-wide changes to how buttons are capitalized or not. This PR intends to make all those changes in 1 PR (but no wording changes).
- Removes CSS logic for button text capitalization. The capitalization must be correct in the `django.po` file. The reason for this is because _some_ buttons are capitalized, but not all. So there is no 1 style that can be applied to all buttons.
- Updates `django.po` file with all new capitalization in English and Spanish.
- `Return Home`|| `Regresar a la Página Principal` for 404, 400, 500 pages 
- `Get Started` (`Empezar`, stays the same for Es) for Agency Index page
- `Go Back` || `Regresar a la Página Principal` for Help page
- `Choose your Provider` `Elija su Proveedor` for Index page
- `Choose this Benefit` `Elija este Beneficio` …
> Buttons: Use copy for button capitalization, not CSS

- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
> Copy: Eligibility Confirm - Courtesy Card flow form

- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
noticed this bug on dev:
the fix:
> Fix: Remove extra asterisks

- benefits/core/context_processors.py
- benefits/core/middleware.py
- benefits/core/templates/core/help.html
- benefits/core/templates/core/includes/button--home.html
- benefits/core/viewmodels.py
- benefits/core/views.py
- benefits/eligibility/templates/eligibility/unverified.html
- benefits/eligibility/views.py
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
- benefits/settings.py
- benefits/templates/200_user_error.html
- benefits/templates/400.html
- benefits/templates/404.html
- benefits/templates/500.html
Part of #1520
The `eligibility:unverified` view uses the _home button_ construct. This also shows up in the `core:help` view as well as in most error pages in `core`.
This PR moves the content to an include, with some added context for the user's current `session.origin` via a new `context_processor`. 
The include is used explicitly where it is needed in templates, removing the need for the `Button.home()` viewmodel helper.
> Refactor: home button

- benefits/core/context_processors.py
- benefits/core/templates/core/help.html
- benefits/core/templates/core/includes/agency-links.html
- benefits/core/viewmodels.py
- benefits/core/views.py
- benefits/eligibility/templates/eligibility/unverified.html
- benefits/eligibility/views.py
- benefits/enrollment/templates/enrollment/retry.html
- benefits/enrollment/views.py
- benefits/settings.py
- tests/pytest/core/test_views.py
Part of #1520
The `eligibility:unverified` view uses the _agency links_ construct. They also show up in two other views: 
* `core:help`
* `enrollment:retry`
In `eligibility` and `enrollment`, we assume an agency has been selected by the user. 
For `core:help`, the user may navigate there before selecting an agency, so we show all "agency links" for active agencies.
This PR moves the variation and content to a new template field: `TransitAgency.links_template`, referencing an `includes` file specific for the agency. The include is used explicitly where it is needed in templates.
This PR removes unused `TransitAgency` fields as well as deleting the `Button.agency_contact_links()` viewmodel helper.
> Refactor: agency links

- benefits/core/migrations/0001_initial.py
- benefits/core/migrations/0002_data.py
- benefits/core/models.py
- benefits/eligibility/templates/eligibility/unverified.html
- benefits/eligibility/views.py
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
- tests/pytest/conftest.py
Closes #1449
Closes #1520 
|  |  |
|-|-|
| Desktop | ![image](https://github.com/cal-itp/benefits/assets/1783439/bb186de8-3650-46d7-b1d8-44fe3c3cc50f) |
| Mobile | ![image](https://github.com/cal-itp/benefits/assets/1783439/3560349e-0f5a-47b9-a2cc-6860feb04da4) |
|  |  |
|-|-|
| Desktop | ![image](https://github.com/cal-itp/benefits/assets/1783439/aa259e3d-9ff0-4aca-9ced-33fbc6f10f48) |
| Mobile | ![image](https://github.com/cal-itp/benefits/assets/1783439/145505b9-5b54-43cc-948d-9c3da7628cbb) |
|  |  |
|-|-|
| Desktop | ![image](https://github.com/cal-itp/benefits/assets/1783439/b3317ebe-6c3d-4563-b6b9-75c2d7fc3699) |
| Mobile | ![image](https://github.com/cal-itp/benefits/assets/1783439/f2101787-f371-46a0-b6dc-99b299042e0c) |
> Refactor: Eligibility unverified page

- benefits/core/templates/core/base.html
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
- benefits/static/css/styles.css
- benefits/static/img/external-link.svg
Closes #1471 
Also closes #1478 , closes #1484 
This PR assumes that all external links have an attribute of `target="_blank"` and adds an icon after the link.
> Feat: external link icon

- benefits/core/context_processors.py
- benefits/core/templates/core/includes/modal--agency-selector.html
- benefits/core/templates/core/index.html
- benefits/core/viewmodels.py
- benefits/core/views.py
> Refactor: remove Transit Agency viewmodel

- benefits/enrollment/templates/enrollment/success.html
- benefits/oauth/analytics.py
- benefits/oauth/middleware.py
- benefits/oauth/views.py
- tests/pytest/core/test_middleware_login_required.py
- tests/pytest/core/test_middleware_verifier_required.py
- tests/pytest/oauth/test_analytics.py
- tests/pytest/oauth/test_middleware_authverifier_required.py
- tests/pytest/oauth/test_views.py
Closes #1535 
Makes all views in `benefits.oauth` require an `EligibilityVerifier` in the session with an `AuthProvider` that supports claims verification. 
This was an implicit assumption before, this PR makes it explicit via a middleware. Added tests to capture these assumptions as well.
> Fix: OAuth session checks and events

- benefits/core/templates/core/widgets/verifier-radio-select.html
part of #1545 
I'm gonna do all the small fixes in #1545 in separate PR's for ease of review/merge.
> Elig Index: Remove required asterisks

- benefits/core/templates/core/base.html
- benefits/core/templates/core/includes/form.html
- benefits/eligibility/forms.py
- benefits/eligibility/templates/eligibility/index.html
- benefits/eligibility/templates/eligibility/start--mst-courtesy-card.html
- benefits/eligibility/templates/eligibility/start--senior.html
- benefits/eligibility/templates/eligibility/start--veteran.html
- benefits/eligibility/templates/eligibility/start.html
- benefits/enrollment/templates/enrollment/index.html
- benefits/static/css/styles.css
closes #1548 
- Desktop: Container width for most* pages is now `col-lg-8`, not `col-lg-10`. Index page, Agency Index page and Enrollment Success is an outlier and is not part of this. No changes necessary for 404/400/500 pages. Also one page has a `col-lg-6` H1 wrapper container instead. Because some pages _are_ actually different from others, I recommend *not* codifying the `col-lg-8` width into the `base.html` itself.
- Desktop: Media Item grid gap is now lower to 24px. 
- Mobile: Should have no changes
> Fixes: CSS column alignment

- benefits/eligibility/templates/eligibility/includes/modal--contactless.html
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
Part of #1475 
Noticed this while working on Help page
> Fix: add missing sentence to contactless cards modal

- benefits/static/css/styles.css
fixes #1553 
This PR only deals with the _color_ Login.gov icon (on Elig Index and Enrollment Success), and the question mark next to the Login.gov icon on Elig Index
The issues:
- Sizing - ? should be 22x22, on both Desktop and Mobile
- Sizing - the color Login.gov is a bit smaller than the white one, at 120x16.
- There doesn't need to be the margin of 2px between the Login.gov button and the question mark (and any text).
> Fix: Question mark and color Login.gov sizing alignment

- benefits/core/templates/core/widgets/verifier-radio-select.html
closes #1545 
The alignment logic:
- Desktop and Tablet: The radio buttons have a 1 column offset (`offset-lg-1`)
- Mobile: The radio buttons have a padding-left of 16px (`ps-3`), and no offset.
> Fix: Eligibility Index - Radio button alignment 

- benefits/core/templates/core/landing.html
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
- benefits/static/css/styles.css
fixes #1418 
This PR takes a different approach from the previous PR - and avoids a lot of complications in new HTML, changing the debug bar, changing templates, etc.
Instead of changing the CSS structure, this PR simply adds an empty `span` tag with `role="img"` and `aria-label` with the alt tag, as suggested here: https://www.davidmacd.com/blog/alternate-text-for-css-background-images.html
> Fix: Add alt text to index, agency index background image

- benefits/static/css/styles.css
> Index/Agency-Index: Add rounded corners to mobile box

- benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--senior.html
- benefits/eligibility/templates/eligibility/includes/modal--senior-help.html
- benefits/eligibility/templates/eligibility/includes/modal--senior-start-help.html
- benefits/eligibility/templates/eligibility/includes/selection-label--senior.html
fix #1575 
This PR ensures that the 2 Login.gov modals match the design in Figma and also match the design of the 2 other modals (Contactless pay and Littlepay) in padding, margin and spacing.
- Use `modal-info` includes for both Login.gov modals. (Side note: Why are 2 modal includes necessary? Because spacing and margins are different in seemingly small but noticeable ways between the Transit Provider Selection modal and the rest of the modals. The X icons aren't even the same. The header top padding height is totally different. The titles are differently aligned - to name a few.)
- Reduces the space between the Header text and the X to 36px.
- Reduces space between paragraphs
> Fix: Desktop - Login.gov modal alignment

- benefits/static/css/styles.css
fix #1577 
- Design instructions are coming from here and reflected in Figma Style Guide: https://github.com/cal-itp/benefits/issues/1423#issuecomment-1601567969
- 4 updated colors: `primary`, `hover`, `footer-link-hover`, `footer-link-visited`
Used to be purple. Now it's a different shade of dark blue (`#0062ff`)
The color for :hover and :visited used to be the same. Now, only the visited is purple.
Regular link hover is slightly darker.
Primary color is now darker. It's most noticable in the nav:
> Add new primary color, hover color, footer hover color, footer visited color

- benefits/core/templates/core/help.html
> Help: Align desktop width to 8-col

- benefits/core/templates/core/includes/modal-info.html
- benefits/eligibility/templates/eligibility/includes/modal--contactless.html
- benefits/eligibility/templates/eligibility/includes/modal--senior-help.html
- benefits/eligibility/templates/eligibility/includes/modal--senior-start-help.html
- benefits/enrollment/templates/enrollment/includes/modal--littlepay.html
- benefits/static/css/styles.css
fix #1593 
- The informational modals have too much margin-top and margin-left and margin-right. This PR brings the text up by 36px so it's aligned with the X, and makes adjustments necessary for that.
- The overall effect of getting all the margins right is that modals on mobile fit more text on the screen, and theoretically, are shorter now.
- Run thru the app in mobile and open _every_ informational modal (2 login.gov, 1 contactless pay, 1 littlepay)
I wrote these out to help me get the alignment right.
- The height of the entire header section: 36px
- Space between the edge and the begining of the text: 32px
- The distance between the edge and the top of the X/the begining of header text: 16px
- Space between the edge and the begining of the text: 16px
- I added the `z-index` …
> Modals: Mobile - Get alignment right

- benefits/eligibility/templates/eligibility/start--mst-courtesy-card.html
- benefits/eligibility/templates/eligibility/start--senior.html
- benefits/eligibility/templates/eligibility/start--veteran.html
- benefits/eligibility/templates/eligibility/start.html
- benefits/static/css/styles.css
fix #1574 
At this specific range of widths (1279px - 992px), the Login.gov button breaks into 2 lines in a way that is not part of the design.
The button should only exist in 2 designs, as shown on Figma:
- Make sure the Login.gov button only shows up in those 2 ways
- Ensure the 2 Login.gov buttons are the correct dimensions
- Modify the `start.html` so that I can adjust the columns for the `start--seniors` includes only, but keep the rest the same.
- Widened the container from `col-3` to `col-4` to allow for the button to remain at width: 289px as the window scales down from 1279px to the maximum of 992px. Add flex-box classes and a max-width declaration so that the button stays at the proper width and also is right-aligned. This widening is a one-off for _this includes with the …
> Fix: Login.gov button width on Tablet

- benefits/core/middleware.py
- tests/pytest/core/test_middleware_changed_language_event.py
> Fix: language event middleware

- benefits/static/css/styles.css
fixes #1573 
Line-height should always be a unitless value. https://developer.mozilla.org/en-US/docs/Web/CSS/line-height#values Do not use rems, pixels for line-height.
- Applies new line-height to h1, h2, h3, h4
- H1-H3 are 1.3
- H4 is 1.2
- These values are the same across Desktop and Mobile.
1. Confirm on Figma that H1, H2, H3, H4 now have _different_ line-height values from the standard body line height.
2. Confirm that the `--bs-body-line-height` variable is correct, set at 1.5, and applied to all the places it should.
3. Create a new variable: `--heading-line-height` of value 1.3.
4. Create a new variable: `--h4-line-height` of value 1.2. H4 is only used in _one spot_ in the whole app, and that is for the Agency Selector modal, specifically, the name of the transit agency. The 1.2 …
> Fix: Line-height across the app for H1, H2, H3, H4

- benefits/static/css/styles.css
fix #1618 
- `#agency-selector` ID doesn't exist anymore
- replace with new ID, `#modal--agency-selector`
> Agency Selector Modal: Fix padding regression

- benefits/locale/en/LC_MESSAGES/django.po
Closes #1581 
Part of #1571
Note this _does not contain_ SBMTD strings, those will come as part of work later in the sprint.
> Chore: update English agency-specific copy

- benefits/core/templates/core/landing.html
fix #1580 
Fixes small padding issue on Landing Pages (Index and Agency Index):
- Desktop: H1 and H2 are flush with the container (vertically aligned with Cal-ITP logo)
- Desktop: Distance between H1 and H2 increased to 48px
> Landing Pages: Fix text padding

- benefits/core/templates/core/help.html
- benefits/static/css/styles.css
fix #1615 
1. Headline: Center the headline on mobile
2. The questions are now 20px font size. Create and use a utility class for this.
3. Padding: Reduce padding between question and first graf. Reduce padding between grafs. Create and use a utility class for this. 
4. No changes for Desktop mode.
> Help: Mobile - Type fixes

- benefits/core/templates/core/includes/modal-trigger-link.html
- benefits/core/templates/core/includes/modal-trigger.html
- benefits/core/templates/core/index.html
- benefits/eligibility/templates/eligibility/includes/media-item--bankcardcheck--start.html
- benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--senior.html
- benefits/eligibility/templates/eligibility/includes/selection-label--senior.html
- benefits/enrollment/templates/enrollment/includes/media-item--bankcardcheck--index.html
closes #1605 
- Changes the last remaining 2 modal triggers to be links. This allows for Amplitude tracking.
- Remove now un-used `modal-trigger` button includes
- Makes changes `modal-trigger` includes:
1. `id` is now `modal`
2. `id` is now the CSS id
3. `period` (boolean) - when True, append `.` after link. when False, skip.
4. `login` (boolean) - when True, add the `<span>....` necessary for the Login.gov button fallback images
Confirmed: #1526 _still_ occurs, even after refactor.
> Refactor: All modal triggers are now links, not buttons

- benefits/core/templates/core/includes/modal--agency-selector.html
- benefits/core/templates/core/landing.html
- benefits/eligibility/templates/eligibility/start.html
- benefits/static/css/styles.css
closes #1600 
Status: Rebased and Ready for Review
- Remove the old letter-spacing variable, and add letter-spacing percentage variables
- Use CSS calc to calculate letter-spacing: the font-size in rem * the letter-spacing percentage
- Use the type set by the most basic element (like `h1`, `h3`) - prefer to not add class or component-level overrides when the type is using the same styles as the already-styled basic elements.
The browser developer tools shows letter-spacing in pixels. Make sure your Figma is in Dev Mode, with display set to Pixels, so you can compare the Figma's pixels to the browser's pixels.
**Desktop**|**Mobile**
:-----:|:-----:
1.75px | 0.72px
**Desktop**|**Mobile**
:-----:|:-----: 
0.72px | 0.72px 
**Desktop**|**Mobile**
:-----:|:-----:
0.72px | 0.9px …
> Letter-spacing

- benefits/core/templates/core/landing.html
fix #1637 
- On Desktop for the agency index/index pages, the container with the text/buttons are centered vertically. This PR adds another 72px of combined margin and padding-top to the container to bring the text down more.
> Landing Page: Desktop - Add 72px extra padding/margin top

- benefits/enrollment/templates/enrollment/success.html
fix #1638 
- Remove `offset-lg-1`
- Change `col-lg-6` to `col-lg-7`
- No changes to mobile
> Enrollment Success: Desktop - Bring text/img closer together

- benefits/static/css/styles.css
fix #1635 
This fix came from @srhhnry's #1582 
- Previously, button background color (and 2px border color of the same color) was coming from CA State Web Template. Now we're overriding the CA State Web Template and declaring it in the CSS itself.
- Add the hover color to button as well
- All CTAs with blue background
- Doesn't affect the button in `disabled` state
> Fix: Button uses primary-color for background

- benefits/core/templates/core/includes/modal--agency-selector.html
- benefits/static/css/styles.css
fix #1648 
I think this came out of a bad merge conflict resolve. Not sure.
- Remove unneeded class
- Use H4 from base element style instead
Compare with what's on dev:
> Fix: Agency Selector h4 bug 

- benefits/core/templates/core/base.html
- benefits/static/css/styles.css
fixes #1636 
- Creates an entirely separate mobile-only footer
- Toggle footer display at mobile/desktop width
- Ensure no Desktop regressions
- 3 different divs. Cannot be encapsulated into 1 parent div... doesn't work. The parent div has to be the `<footer class="navbar"` (which acts like a `row`, and is what the `<header>` uses). We want the footer link widths to be the same as that of the `<header>`. 
- 2 divs with the 2 different links are `container` width, to get that `container` scaling
- 1 div is `container-fluid` width with `p-0`, so that the horizontal white line can be 100% width of the desktop
- Removes all manual padding/margin that was previously positioning the mobile footer link, so the focus ring looks correct.
I temporarily hid the `main` container from this view, so …
> Refactor: Footer - Re-do mobile footer alignment

- benefits/core/templates/core/base.html
- benefits/static/css/styles.css
closes #1388 
requires #1387 and #1613 
- Style the Skip Nav into a full-width div with yellow background
- Works like the Skip Nav here https://www.gov.uk/
- When testing, do not have the developer console tool window open. The focus won't work.
- On Desktop: Go to any page, like http://localhost:8000/mst
- Click <kbd>Tab</kbd> on keyboard
- Once the skip nav appears, click <kbd>Enter</kdb>
- Click  <kbd>Tab</kbd> again. You'll now be in the `#main-content` div and probably focused on a Call to Action button. You'll have skipped the `Español` button. You don't skip the `Previous Page` button though.
- Skip Navs are generally Desktop features b/c it's for users using a keyboard, but it works fine on Mobile too.
- Works _better_ if you hide the Dev Mode bar. Hide it by adding `d-none` in …
> Feat: Skip Nav

- benefits/core/templates/core/includes/button--index.html
- benefits/eligibility/templates/eligibility/unverified.html
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
- benefits/templates/200-user-error.html
- benefits/templates/400.html
- benefits/templates/500.html
- benefits/templates/error.html
Closes #1650 
This PR makes the `Return Home` button on Eligibility Unverified (and `Start Here` on 200 User Error) take the user back to the index page, allowing for a correction of Transit Agency and/or Eligibility Type.
Also fixed a small typo in a few error page titles.
> Fix: return home button

- benefits/static/css/styles.css
fixes #1659 
- Explicitly set the `.card`'s focus ring's `outline-offset` to 0, to override Chrome's default browser CSS
- `.card`'s focus ring should be flush against the card, without any space in between:
Chrome's browser adds this CSS to all websites:
```css
a:-webkit-any-link:focus-visible {
outline-offset: 1px;
}
```
Firefox and Safari do not set an `outline-offset` at all, so it defaults to `initial`, which is 0. I had only tested in Firefox and Safari, so I didn't notice that Chrome _does_ add an 1px offset.
This PR takes care of that browser difference.
> Fix: Focus ring on Card on Google Chrome

- benefits/core/templates/core/includes/icon.html
- benefits/core/templates/core/logged-out.html
- benefits/eligibility/templates/eligibility/includes/media-item--bankcardcheck--start.html
- benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck.html
- benefits/eligibility/templates/eligibility/includes/modal--contactless.html
- benefits/eligibility/templates/eligibility/unverified.html
- benefits/enrollment/templates/enrollment/includes/media-item--bankcardcheck--index.html
- benefits/enrollment/templates/enrollment/retry.html
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
- benefits/templates/error.html
closes #1651 
- Add `alt=""` to the `icon` includes. Remove alt validation
- Remove alt tag copy and call from happy bus, sad bus, contactless pay icons, id card icons
> Fix: Remove alt tag from decorative icons

- benefits/static/css/styles.css
closes #1661 
This was bothering me a lot 😓 and I finally looked up a solid, easy solution w/o any drawbacks. Currently, when using the Skip Nav to get to `#main-content` and then continuing to use the keyboard for navigation, the site will scroll you back _up_ the page when you go from `#main-content` to `Previous Page`. It creates a jarring user experience, where the page goes down, and then back up. This PR fixes it by adding a `scroll-padding-top` that's greater than the height of the nav (80px), so the screen doesn't move back up. This solution also doesn't affect anything else (like the footer position, main container height, etc).
| Before     | After     |
| --------  | -------- |
|  ![broken](https://github.com/cal-itp/benefits/assets/3673236/1e52e757-1675-4c9c-9d53-328a933cd704)| …
> Fix: Skip Nav - Remove skip nav page jank

- tests/cypress/plugins/helpers.js
closes #1443 
This code, a `selectCourtesyCard` test helper method, was previously quite brittle, and would break if any new Eligibility Verifiers were added - b/c the code was going by order of verifiers -- which can change -- and not actually looking for the radio input label that says "Courtesy Cards." This method broke when we added the Veterans verifier: https://github.com/cal-itp/benefits/pull/1436/files#diff-d8c366d9dffb4c84efb0c81d20aae1435d1a10f57a019a62d8131839878b194e
This PR refactors this method by having Cypress actually look for elements to click by copy, so it will not break when we add new verifiers.
> Refactor Cypress helper

- benefits/core/templates/core/base.html
- benefits/core/templates/core/includes/form.html
closes #1672 
The new Figma designs eliminated the text preceding CTAs on all pages of the site, like these:
This PR removes the `help_text` (used on the Eligibility form CTA, https://github.com/cal-itp/benefits/commit/a8a6c63a4d4025be561fd535d6f31d51633b9236) and the `call-to-action-text` (used on Eligibility Start) from the templates. It also removes the CSS classes that were necessary to get the mobile version to flip order from the Desktop mode.
> Refactor: Remove unnecessary template code

- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
closes #1710 
Payment partner in Spanish is `socio de pagos`, not `socio de pago`.
> Fix: Add one S

- benefits/__init__.py
- pyproject.toml
- tests/pytest/test_version.py
Standardizing on managing the version string in the `pyproject.toml` across Benefits projects.
See also cal-itp/eligibility-server#325
1. Checkout this branch
2. Rebuild app and devcontainer without caching `docker compose build --no-cache client` then the same for `dev`
3. Run `docker compose run --entrypoint bash client` to attach to a client container
4. Confirm `pip freeze` shows output similar to (look for the line mentioning `benefits`):
```console
$ docker compose run --entrypoint bash client
calitp@afef4102469a:~/app$ pip freeze
asgiref==3.7.2
Authlib==1.2.1
-e /home/calitp/app
certifi==2023.7.22
cffi==1.15.1
...
```
5. Launch devcontainer
6. Confirm all tests pass
> Chore: version management

- compose.yml
closes #1730 
When I run `docker compose run --entrypoint bash client` on my machine now, with this PR, I'm able to get to bash properly.
> Docker: Revert platform change

- .github/workflows/tests-pytest.yml
- pyproject.toml
- tests/pytest/core/test_models.py
- tests/pytest/eligibility/test_views.py
- tests/pytest/run.sh
See https://github.com/cal-itp/littlepay/pull/8#issuecomment-1709280695 for an example.
> Tests: add coverage comments to PRs

- .github/workflows/deploy.yml
Runs ~`pip freeze`~ `pipdeptree` and puts the results in `benefits/static/requirements.txt` before building and publishing the app image.
Similar to having the `sha.txt`, this will help confirm changes and debug issues with Python package updates.
I [ran the Deploy Action manually](https://github.com/cal-itp/benefits/actions/runs/6241134138/job/16942713064#step:4:6) for this branch to produce an image using the updated workflow, you can see in the logs the results of the updates.
That image is here: https://github.com/cal-itp/benefits/pkgs/container/benefits/129491917?tag=pip-freeze
To test that this works, pull the image locally:
```console
$ docker pull ghcr.io/cal-itp/benefits:pip-freeze
pip-freeze: Pulling from cal-itp/benefits
Digest: …
```
> Chore: add pip metadata file to app container

- benefits/static/css/styles.css
> fix: do not show scrollbar when not necessary

- benefits/settings.py
- bin/init.sh
- docs/configuration/environment-variables.md
- terraform/app_service.tf
Closes #1763 
In your local `.env` file, try different values for the environment variables.
_Note the `DJANGO_DB_DIR` must already exist!_ 
E.g. to create the database file in a local (to your repo) directory called `db`:
```bash
mkdir db
```
Then set the environment variable and reload your devcontainer:
```env
DJANGO_DB_DIR=./db
```
Verify `bin/init.sh` output:
```console
$ DJANGO_DB_DIR=./db bin/init.sh 
+ [[ true = true ]]
+ DB_DIR=./db
+ DB_FILE=./db/django.db
+ rm -f ./db/django.db
+ python manage.py migrate
Operations to perform:
Apply all migrations: core, sessions
Running migrations:
Applying core.0001_initial... OK
Applying core.0002_data... OK
Applying sessions.0001_initial... OK
```
Set `DJANGO_DB_RESET` to `false` to keep the database between restarts/reinits:
```env …
```
> Feat: parameterize Django database path/deletion

- bin/init.sh
- docs/configuration/environment-variables.md
- terraform/app_service.tf
Closes #1776 
In your `.env` file, add the new environment variables:
```env
DJANGO_SUPERUSER_EMAIL=you@example.com
DJANGO_SUPERUSER_PASSWORD=password
DJANGO_SUPERUSER_USERNAME=username
DJANGO_ADMIN=true
```
Rebuild and reopen the devcontainer.
Confirm in the init output that the admin/user migrations are run and superuser is created.
Launch the app with `F5`, and visit `localhost:PORT/admin` in your browser. Confirm you can login with the username/password above.
> Feat: Unattended superuser creation

- appcontainer/nginx.conf
See recent Sentry errors, e.g. https://sentry.calitp.org/organizations/sentry/issues/73065/?project=3
The database file cannot be served anyway, but this just rejects the request earlier in the chain to avoid hitting the application layer at all.
> Chore: block Sqlite scraper patterns

- benefits/enrollment/templates/enrollment/retry.html
- benefits/enrollment/views.py
fix #1755 
- Pass `retry_button` as `True` to the `enrollment/retry` page, so that the button appears
> Show retry button on enrollment/retry page

- docs/requirements.txt
- mkdocs.yml
Useful for #1762 
This PR adds the `mdx_truly_sane_lists` extension to our Mkdocs configuration, which makes it so indenting a list item with 2 spaces in Markdown will make a nested list.
Without the extension, Mkdocs's default is to expect 4 spaces; this behavior is due to [Mkdocs's usage of Python-Markdown](https://github.com/mkdocs/mkdocs/issues/545). Prettier, our configured formatter, re-formats 4-space indents into 2-space indents.
So in our current docs site, we have lists like:
With this extension added, they are nested:
> Docs: add extension to make nested lists work

- .gitignore
- bin/init.sh
Updates the `bin/init.sh` script to first rename the existing database file before deleting, in the case of a DB reset.
This is a follow-up to #1775 -- with the Sqlite file stored in an Azure SMB fileshare, when we `rm django.db` the file is only _marked for deletion_ in Azure, which could take a few minutes.
In the meantime, `python manage.py migrate` is attempting to recreate/write to the file that may still exist (and locked for deletion). We're seeing an increase in healthcheck failures as the app restarts and finally clears the file lock:
```log
2023-12-01T17:35:15.514065207Z + bin/init.sh
2023-12-01T17:35:15.554876476Z + [[ true = true ]]
2023-12-01T17:35:15.555739988Z + DB_DIR=./data
2023-12-01T17:35:15.555886290Z + DB_FILE=./data/django.db
2023-12-01T17:35:15.556020892Z + rm -f …
```
> Fix: attempt db rename during reset

- benefits/enrollment/api.py
- tests/pytest/enrollment/test_api_GroupResponse.py
> Fix: Re-enrollment

- docs/product-and-design/.pages
- docs/product-and-design/analytics.md
closes #953 
- adds an Analytics page on the docs, under the Product & design category
- Analytics docs covers all the criteria in #953 and links to Amplitude Benefits events docs https://data.amplitude.com/public-doc/hdhfmlby2e
- Analytics docs DOES NOT link to Metabase or show any charts
> Docs: Analytics

- benefits/enrollment/templates/enrollment/index.html
- docs/use-cases/system-use-cases.md
Closes #1762 
The resources that I took a lot of inspiration from are:
- https://guides.visual-paradigm.com/a-comprehensive-guide-to-use-case-modeling
- https://en.wikipedia.org/wiki/Use_case#Examples
From that Wikipedia page, this is what I hope we can get out of writing use cases at this level of granularity:
> **Better communication**
> 
> Use cases are often written in natural languages with structured templates. This narrative textual form, understandable by almost everyone, and complemented by visual UML diagrams fosters better and deeper communications among all stakeholders, including customers, end-users, developers, testers, and managers. Better communications result in quality requirements and thus quality systems delivered.
> 
> **Quality requirements by structured …
> Docs: add system use case with retry as alternate flow

- docs/product-and-design/.pages
- docs/product-and-design/use-cases/enrollment-use-cases.md
- mkdocs.yml
- Add Use Cases back to the sidebar: Renames the page to `Enrollment use cases` so it fits better in the hierarchy
- Fixes Alternate flows bullet bug:
- Updates redirect to go to the proper URL, removes College redirect (page is now deleted)
> Docs: Various small fixes

- .devcontainer/server/.env.server
I was finally able to reproduce the issue we've been seeing in our GitHub Actions Cypress test failures. That workflow [starts up `client` and `server` via Docker Compose](https://github.com/cal-itp/benefits/blob/cb8db9e62b024b49fb28d3ab9a67891c1154cf0a/.github/workflows/tests-cypress.yml#L19).
I had to delete all my containers and images to finally see the issue:
```
2023-12-20 12:35:09 + bin/init.sh
2023-12-20 12:35:09 + flask init-db
2023-12-20 12:35:09 Error: Could not import 'app'.
2023-12-20 12:35:09 
2023-12-20 12:35:09 Usage: flask [OPTIONS] COMMAND [ARGS]...
2023-12-20 12:35:09 Try 'flask --help' for help.
2023-12-20 12:35:09 
2023-12-20 12:35:09 Error: No such command 'init-db'.
```
I guess somewhere in some cached layer of a Docker image, there must've been something that made …
> Fix(server): remove unnecessary configuration of FLASK_APP

- docs/README.md
Small follow-up to #1815 and #1821 
- normalize intro with repo README 
- simplify some language 
- consolidate and elevate sections
- links to additional pages e.g. Analytics
> Docs: update landing page

- .github/workflows/mkdocs.yml
Closes #1844 
Decided to try and do this in the existing workflow file as a separate job, rather than a separate workflow. Hopefully that works!
> Feat: docs site previews for Pull Requests

- docs/product-and-design/analytics.md
closes #1841 
- Adds a table for default user props, with definitions from https://help.amplitude.com/hc/en-us/articles/215562387-Appendix-Amplitude-User-Property-Definitions
- Removes explicit reference to Littlepay. People can see if it they click through to the Amplitude docs.
- Reaching a compromise with regard to linking to the Benefits application or not:
1. On first reference, the app is now referred to like this: For people who might think "app" means a mobile application, I use the phrase `currently live at https://....`. But, I do *not* link the actual link - because we are trying to discourage "drive-by clicks" that artificially inflate our click-through numbers. (Though remember, if we want to filter out People Who Came To Benefits via the Documentation or any Calitp.org …
> docs(analytics): add table for default user props

- benefits/core/templates/core/base.html
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
- benefits/static/css/styles.css
closes #1852 
- Restyles Skip to main content link focus ring
- Refactors focus ring CSS to use variables, so both rings can use same variable
A11y testing this branch versus test:
> Skip to main content link

- .devcontainer/server/settings.py
- benefits/core/migrations/0002_data.py
After https://github.com/cal-itp/eligibility-server/pull/414 was merged and the `dev` branch was deleted over there, these URLs need to be updated to point to `main`.
Note these values are only used locally / in CI, not in production.
See e.g. [failing Cypress tests](https://github.com/cal-itp/benefits/actions/runs/7705421373/job/20999418005), related to WIP PR #1859
> Fix: update GitHub branch for sample eligibility server config

- .devcontainer/Dockerfile
- .env.sample
- benefits/secrets.py
- benefits/sentry.py
- benefits/settings.py
- benefits/urls.py
- docs/configuration/environment-variables.md
- docs/getting-started/README.md
- pyproject.toml
- tests/pytest/test_secrets.py
- tests/pytest/test_settings.py
Part of #1847 
* Defines a new setting `RUNTIME_ENVIRONMENT()` to dynamically calculate one of `local`, `dev`, `test`, or `prod` based on the values in `ALLOWED_HOSTS`
* Uses [`azure-keyvault-secrets`](https://pypi.org/project/azure-keyvault-secrets/) and [`azure-identity`](https://pypi.org/project/azure-identity/) based on [Getting Started with Azure Key Vault Secrets client library for Python](https://learn.microsoft.com/en-us/python/api/overview/azure/keyvault-secrets-readme?view=azure-python&source=recommendations#getting-started)
* Installs the Azure CLI into the devcontainer, to make debugging and testing of this functionality possible within the same environment we use for daily development.
* For `local` runtime environment, falls back to reading from environment variables
The …
> Feat: helper script to read KeyVault secrets

- .env.sample
- benefits/secrets.py
- docs/configuration/environment-variables.md
- tests/pytest/test_secrets.py
Docker, bash, etc. support multiline environment variables, by simply wrapping the value in single quotes with newlines, e.g. in an .env file:
```env
multi_line_value='first line
second line
third line'
```
Resulting in the expected:
```console    
$ echo "$multi_line_value"
first line
second line
third line
```
Due to a quirk in VS Code's Python extension, multiline values are not parsed, see https://code.visualstudio.com/docs/python/environments#_environment-variables
> ... Multiline values aren't supported ...
And more ongoing discussion at microsoft/vscode-python#18307
When running locally in e.g. Debug mode, and secrets are read dynamically from the environment, Python loses the multiline value and we end up with:
```console
>> value = os.environ.get("multi_line_value")
>> …
```
> Secrets: update guidance and parsing for local multiline env vars

- docs/deployment/infrastructure.md
- terraform/.terraform.lock.hcl
- terraform/storage.tf
- terraform/terraform.tfvars.sample
Closes #1816 
1. Defines an Azure Recovery Services Vault; this is where snapshots are stored. The default Geo-redundant storage is configured, so that backups are stored across various Azure geographic regions for maximum availability in case of e.g. a data center outage. The cost difference for our level of transactions and storage is mostly irrelevant at this point.
2. Links the existing Storage Account, containing the file(s) to be backed up, to this new Recovery Services Vault.
3. Creates an Azure File Share backup and retention policy: a daily snapshot taken at 14:00 UTC (roughly 6-7am Pacific), keeping 1 backup per day and 5 per week (1 for each weekday). The thinking here is we likely make changes throughout the day, so the snapshot will be at the beginning of a new day, capturing …
> Feat: configure Azure file share backup

- .github/workflows/check-api.yml
Closes #1814 
This PR refactors the `check-api` workflow to use [cal-itp/littlepay](https://github.com/cal-itp/littlepay) instead. 
Like the previous implementation, this approach checks if it can get an access token for the QA and prod environments. Additionally it does those checks for each participant, as defined in the job matrix.
> Refactor: use cal-itp/littlepay to check API access

- docs/enrollment-pathways/README.md
Front-matter should be in the form of
```yaml
---
key: value
---
```
This adds the colon to the title key
> fix(docs): clean up front-matter

- docs/enrollment-pathways/low-income.md
The ordered list under basic flow isn't presenting sequence correctly.  Instead of adding an order to elements in the list, I've changed all numbering to one so the elements are ordered when they are presented.
> Update low-income.md changed ordered list markdown to all 1s

- terraform/app_service.tf
Quick follow-up to #1855 that was missed in review
> Fix: correct Google SSO secret names

- .env.sample
- bin/reset_db.sh
* wraps the sample secret value in quotes in `.env.sample` because bash can choke on the spaces
* fix an apparent syntax error in `bin/reset_db.sh` that was causing evaluation of the fixtures file to fail
> Fix: sample env and reset_db helper

- benefits/core/migrations/local_fixtures.json
- benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--calfresh.html
- benefits/eligibility/templates/eligibility/start--calfresh.html
Closes #1916 
Run `./bin/reset_db.sh` in devcontainer to load in new fixtures that contain new start template for CalFresh verifier. Start the app with <kbd>F5</kbd> and navigate through to the eligibility start page for CalFresh.
> Feat: CalFresh eligibility start

- docs/tests/automated-tests.md
Fixing a 404 I noticed on our docs site:
The `mkdocs.yml` GitHub workflow publishes the coverage report at [`docs/tests/coverage`](https://github.com/cal-itp/benefits/blob/2024.03.3/.github/workflows/mkdocs.yml#L100).
The link to the coverage report was on a page that got moved under `docs/tests/automated-tests` in https://github.com/cal-itp/benefits/commit/a5c63c54228209d94124f0725468ef79820da1f3, and we forgot to update the link.
> Fix: path to coverage report

- benefits/core/templates/core/includes/media-item.html
- benefits/enrollment/templates/enrollment/includes/media-item--bankcardcheck--index.html
Fixes #1975 
Previously `h3` was hard-coded as the heading tag for media items.
This caused a bug in `enrollment:index`, where heading levels skip from `h1` (the page title) to `h3` (the first media item).
In `eligibility:start` (the other place where media items are used), there is an intervening `h2` that keeps the order correct.
This change allows a child media item to override the heading tag, while maintaining the `h3` styling for all `.media-item--heading`, regardless of tag used.
The default tag remains `h3` if a child media item does not choose to override.
Found this answer on SO which showed that, with an extra wrapping `{% block %}`, context from the child can be passed up to the parent using `{% with %}`: https://stackoverflow.com/a/46581444 TIL!
> Fix: allow custom media-item--heading tag

- benefits/core/context_processors.py
- benefits/core/session.py
- tests/pytest/core/test_context_processors.py
- tests/pytest/core/test_session.py
Closes #1981
New `session` helpers:
* `enrollment_expiry` gets the current user's expiration as a datetime, or None
* `enrollment_reenrollment` gets the current user's reenrollment as a datetime, or None
* `update` accepts `enrollment_expiry` as a datetime
New `context_processor`:
* Adds `expiration`, `reenrollment`, and `supports_expiration` under the `enrollment` key 
```
{ 
"enrollment": {
"expiration": datetime | None,
"reenrollment": datetime | None, 
"supports_expiration": bool
}
}
```
Also removed most of the noisy logging from `session`.
> Feat: store/retrieve enrollment expiry in session

- benefits/core/session.py
- benefits/settings.py
- tests/pytest/core/test_session.py
Quick follow-up to #1985 
* Forgot to activate the new context processor in `settings.py`
* Forgot to clear the enrollment expiry in `session.reset()`
> Fix: enrollment expiry session

- bin/reset_db.sh
With `-e`, the script returns an error code whenever any command does so, which can cause the rest of the Dev Container setup to fail.
`grep` returns an error code when no match is found, but we don't want that to end the script in error, so test the `grep` return code
See https://stackoverflow.com/a/49627999/453168
> Fix: catch grep failure so reset script doesn't die

- benefits/enrollment/views.py
- benefits/settings.py
- tests/pytest/conftest.py
- tests/pytest/enrollment/test_views.py
Closes #1877
This PR refactors the enrollment phase so that we no longer catch a 409 error to detect existing enrollments. Instead we see if the enrollment already exists for the group. This also allows us to inspect the expiration date of any existing enrollment.
So this PR also introduces support for enrollments that expire. See the table below for expected behavior.
_copied directly from [our dev meeting notes](https://docs.google.com/document/d/1vActZALSbRwO0HxDvm-YQK37p22SPbL4XuMdcRx-BI8/edit#heading=h.1qwtpkwx040s)_
<details><summary>Expand to view table</summary>
| Eligibility state           | Enrollment state | Expiration state                | Expected enrollment outcome              | Expected end page for user       |
| --------------------------- | ---------------- | …
> Feat: enrollments can expire

- docs/README.md
As part of the effort to backfill enrollment data from the early days of Benefits when we used the DMV for eligibility verification, @thekaveman did some research to determine the date of our official deployment of Benefits for MST. We're using [this release](https://github.com/cal-itp/benefits/tree/2021.12.0) to denote launch. I updated the documentation accordingly.
> Updated initial agency launch date for MST

- compose.yml
Since `ghcr.io/cal-itp/eligibility-server:dev` is now a multi-platform image (built off the multi-platform `ghcr.io/cal-itp/docker-python-web:main` image), the `platform` attribute is no longer needed.
> fix(docker): remove platform attribute from server service

- benefits/core/templates/core/includes/form.html
Fixes #2033 
djlint was re-formatting the HTML to put the `label` element on separate lines. However, this caused there to be whitespace surrounding the text for the field label.
This PR disables djlint for the form's `label` elements and removes the whitespace. See [djlint docs](https://djlint.com/docs/ignoring-code/) on ignoring code.
The built-in [`spaceless` tag](https://docs.djangoproject.com/en/5.0/ref/templates/builtins/#spaceless) from Django was close to what we needed except that it doesn't remove whitespace between tags and text.
> Fix: unnecessary space on required form field label

- benefits/enrollment/views.py
- tests/pytest/enrollment/test_views.py
> Fix: update param name for expiry

- benefits/enrollment/templates/enrollment/retry.html
- benefits/enrollment/views.py
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
- tests/pytest/enrollment/test_views.py
Closes #2031 
The `/retry` page was functioning as both our "user" enrollment error page (i.e. #2031) and our "system" enrollment error page (i.e. #2032).
This PR updates the language so the page is more explicitly for "user" enrollment errors.
#2032 will have to make additional changes e.g. by creating a new route/template.
This PR also simplifies the view logic of `/retry`, to remove the unnecessary blocking of `GET` requests to that endpoint (which makes testing easier).
_Current on top of #2039_
1. Launch the app locally
2. Verify eligibility for any flow
3. One verified, visit `/enrollment/retry`
4. See the updated copy and design
> Chore: update enrollment retry page

- benefits/core/templates/core/base.html
- benefits/core/templates/core/includes/form.html
- benefits/eligibility/forms.py
- benefits/eligibility/templates/eligibility/confirm.html
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
- benefits/static/css/styles.css
Closes #2011 
This PR updates the copy as shown in Figma and updates styles for the Eligibility Confirm form fields.
Followed precedent set by https://github.com/cal-itp/benefits/pull/1610 in using unit-less value for `line-height`
- Launch the app from this branch
- Check that copy and styles were updated as specified in #2011
| Before (using test-benefits) | After (this branch) | Figma | 
| --- | --- | --- |
| ![image](https://github.com/cal-itp/benefits/assets/25497886/65e373f6-c2bc-4bf6-a82d-757a098ba618) | ![image](https://github.com/cal-itp/benefits/assets/25497886/abaf7fd5-81be-489e-8e96-499116ca80d9) | ![image](https://github.com/cal-itp/benefits/assets/25497886/0ebe4964-7565-4a2e-9058-6266bbbfb0c9) |
| Before (using test-benefits) | After (this branch) | Figma | 
| --- | --- | …
> Feat: eligibility confirm copy and UX

- benefits/enrollment/views.py
- benefits/settings.py
- tests/pytest/conftest.py
- tests/pytest/enrollment/test_views.py
This reverts commit 479b249d6059a7d7148aef8bdb5d5fc3066d6d17, reversing changes made to 96ea690df50b556cf8ee15bff606cfb2e59cf3e9.
We're reverting the change to how enrollment is performed to unblock other in-progress changes that we'd like to be able to deploy.
This reverts all the logic for looking up funding sources linked to a group, and determining if a user is eligible for re-enrollment. Instead we go back to handling the `409` error that indicates a user is already enrolled in a group, with no logic for expiration.
[We are working with Littlepay to identify issues with testing this expiration logic](https://cal-itp.slack.com/archives/C03V716MKQS/p1712089166817549), and will bring these changes back to `dev` once we solve those issues.
> Revert "Feat: enrollments can expire (#1989)"

- benefits/enrollment/templates/enrollment/includes/media-item--bankcardcheck--index.html
- benefits/enrollment/templates/enrollment/index.html
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
- tests/cypress/specs/courtesy-cards.cy.js
Closes #2014
This PR updates the `enrollment/index` copy as shown in Figma.
| Before (using test-benefits) | After (this branch) | Figma |
| --- | --- | --- |
| ![image](https://github.com/cal-itp/benefits/assets/20033812/9193e00c-2661-4619-853a-feefa875af51) | ![image](https://github.com/cal-itp/benefits/assets/20033812/3dada991-8040-439c-b980-13c35b2e19ae) | ![image](https://github.com/cal-itp/benefits/assets/20033812/032164e2-0088-42ac-ad55-25a81c5e0127) |
| Before (using test-benefits) | After (this branch) | Figma |
| --- | --- | --- |
| ![image](https://github.com/cal-itp/benefits/assets/20033812/797e128e-257a-47ed-ab9b-f7913de00161) | ![image](https://github.com/cal-itp/benefits/assets/20033812/993f8c21-6e68-4053-86dc-7733f2c29e16) | …
> Feat: enrollment index update copy

- benefits/core/analytics.py
- tests/pytest/core/test_analytics.py
Closes #2034.
Uses [request.GET.get()](https://docs.djangoproject.com/en/5.0/ref/request-response/#django.http.QueryDict.get) to get the UTM code. If a UTM code is not present in the query string, returns `null` for that UTM code.
Using a local instance of `benefits`, send a request that looks something like `http://localhost:port/?utm_campaign=transit`. Verify that the property `utm_campaign` has been added to `event_properties` and `user_properties`.
| Browser | Debug Message |
|---|---|
| ![image](https://github.com/cal-itp/benefits/assets/20033812/25b599f0-1a71-4aef-87dd-a2d9632c60cd) | ![image](https://github.com/cal-itp/benefits/assets/20033812/fc1d8dfe-3811-40e4-9d13-64aefcad2b42) |
> Feat: add properties for UTM codes

- benefits/core/models.py
- tests/pytest/core/test_models.py
Closes #2065
* implements the `__str__` method on `AuthProvider` so it gets a human-readable label in the Admin
Closes #2072 
* removes the override of `blank = False` from `SecretNameField` to prevent validation errors in the Admin
> Fix: model cleanups for the Admin

- benefits/core/migrations/local_fixtures.json
- benefits/enrollment/templates/enrollment/index--agency-card.html
- benefits/enrollment/templates/enrollment/index.html
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
> Fix: enrollment index headline

- .github/workflows/add-to-project-dependabot.yml
This is a good default and can always be adjusted. I usually set this manually on just about every Dependabot PR :upside_down_face:
> CI: initialize Dependabot PR effort to 1

- .github/workflows/add-to-project-dependabot.yml
Quick follow-up to #2083 -- the step inputs use underscores, not dashes: https://github.com/EndBug/project-fields?tab=readme-ov-file#inputs
> Fix: correct syntax in field update step

- .github/workflows/mkdocs.yml
This permission is needed to allow the step that adds a comment with the preview URL
> Fix: allow mkdocs preview job to write comments on PRs

- benefits/enrollment/templates/enrollment/retry.html
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
Part of #2074 
Rows 21, 161, 205-207 of `forTranslation` tab.
> Feat: Spanish translations for 500, user enrollment error

- benefits/enrollment/templates/enrollment/system_error.html
- benefits/enrollment/views.py
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
- benefits/static/css/styles.css
- benefits/templates/error.html
- tests/pytest/enrollment/test_views.py
Part of #2032 
This PR implements the system enrollment error page template and adds error-handling to the `benefits.enrollment.views.index` function so that if a 500-level HTTP error occurs when we try to link a funding source to a group, the system enrollment error page will be shown. The CTA takes the user back to the agency index.
A Sentry notification will be sent - see [an example from my testing](https://sentry.calitp.org/organizations/sentry/issues/75377/?project=3&referrer=slack). **Note:** since I don't know how to cause an actual 500 error with the linking endpoint, I had to add some code locally to fake it (more details in steps for reviewing / testing).
<details><summary>Expand</summary>
| Desktop | Mobile |
| --- | --- |
| …
> Feat: system enrollment error - 500 error when linking

- .github/workflows/deploy.yml
Closes #1880 
This PR replaces usage of GitHub webhooks for the `package.publish` event that trigger the Azure Web App image pull + restart, with the [`azure/webapps-deploy`](https://github.com/Azure/webapps-deploy/) action step. Using this actions step, we can target the specific Web App (e.g. `dev`, `test`, or `prod`) that needs to be deployed/restarted, and avoid the current situation where the `package.publish` event triggers a restart in all 3 environments, regardless of which branch/environment was deployed.
Use of a Publish Profile avoids needing a Microsoft Entra ID generated Service Principle.
Following the outline on [Deploy a custom container to App Service using GitHub Actions](https://learn.microsoft.com/en-us/azure/app-service/deploy-container-github-action?tabs=publish-profi …
> CI: deploy Azure Web App with GitHub Actions

- benefits/enrollment/analytics.py
- benefits/enrollment/templates/enrollment/index.html
- benefits/enrollment/urls.py
- benefits/enrollment/views.py
- tests/pytest/enrollment/test_analytics.py
- tests/pytest/enrollment/test_views.py
Part of #2032 
Similar to review steps for #2088, you can add some code locally to simulate a 500 error.
To `/token`, add:
```diff
try:
+          class response:
+             def __init__(self):
+                self.status_code = 500
+
+          raise HTTPError(response=response())
response = client.request_card_tokenization_access()
except Exception as e:
```
> Feat: system enrollment error - 500 error during /token

- docs/deployment/release.md
We have been using annotated tags, so this updates our docs to reflect that.
> Chore: update docs on tagging a release

- benefits/oauth/views.py
- tests/pytest/oauth/test_views.py
Closes #2046 
Set Django's database `authprovider` fixtures to the new [scopes](https://cal-itp.slack.com/archives/C037Y3UE71P/p1715882088978089?thread_ts=1715881952.138259&cid=C037Y3UE71P)/[claims](https://cal-itp.slack.com/archives/C037Y3UE71P/p1715882216002199?thread_ts=1715881952.138259&cid=C037Y3UE71P). Run bin/reset_db.sh to reset database.
> Refactor: use integer claims in OAuth

- .github/workflows/check-makemigrations.yml
Closes #2092 
I tested this locally with `act`:
I think this will need to be reviewed, approved, and merged into `dev` before we can see it in action on a PR.
> CI: check for up-to-date migrations

- tests/pytest/conftest.py
- tests/pytest/eligibility/test_verify.py
- tests/pytest/eligibility/test_views.py
- tests/pytest/enrollment/test_views.py
- tests/pytest/oauth/test_analytics.py
- tests/pytest/oauth/test_middleware_authverifier_required.py
- tests/pytest/oauth/test_views.py
Prompted by @lalver1 's questions / notes for #2125
`test_authorize_success_without_verifier_claim` was giving us a false positive because the verifier fixture is also not behaving correctly when returning `uses_auth_verification`. Also see our [Slack thread](https://cal-itp.slack.com/archives/C037Y3UE71P/p1717085288461349).
I'm not sure at what point this test became incorrect. It could be that when the test was written, we were using `VerifierSessionRequired` rather than `VerifierUsesAuthVerificationSessionRequired`, and so we expected to be able to reach `ROUTE_CONFIRM` which would then handle the fact that no claim was stored. See https://github.com/cal-itp/benefits/issues/1535 for why we changed the middleware behavior.
We can revisit if showing `user_error` is the correct UX here, …
> Fix: test assertions for missing claim on AuthProvider

- benefits/core/urls.py
- benefits/core/views.py
- benefits/enrollment/templates/enrollment/index.html
- benefits/enrollment/views.py
- tests/pytest/enrollment/test_views.py
Part of #2032 
**To test handling of 400-level HTTP errors**, you'll have to force it like in other PRs such as #2089.
To `/token`, add:
```diff
try:
+          class response:
+             def __init__(self):
+                self.status_code = 400
+
+          raise HTTPError(response=response())
response = client.request_card_tokenization_access()
except Exception as e:
```
**To test other exceptions**:
- setting an incorrect `client_id` on `PaymentProcessor` causes `UnsupportedTokenTypeError` on `client.request_card_tokenization_access`
- setting an incorrect `api_base_url` on `PaymentProcessor` causes a `ConnectionError` on `client.ensure_active_token`
- setting an incorrect `client_secret_name` on `PaymentProcessor` could cause an error when creating `Client` (we read from …
> Feat: server error - 400 errors / other exceptions during /token

- docs/deployment/README.md
Follow-up to #2123
There was one last bit of documentation talking about GitHub webhooks in the Deployment process section.
> Docs: deployment process to Azure Web App

- .github/workflows/check-makemigrations.yml
Closes #2092 
We want the migration check to be a required check but not for it to block PRs that don't match the path filter, so we have to remove the path filters
> CI: remove path filters from migration check

- docs/deployment/README.md
- docs/deployment/infrastructure.md
- docs/deployment/workflows.md
- terraform/app_service.tf
Closes #2118 
[Plan looks good](https://calenterprise.visualstudio.com/CDT.OET.CAL-ITP/_build/results?buildId=45314&view=logs&j=5af648c4-4294-55a7-6072-dd70820d3dba&t=42899ae2-6397-58a2-7641-cec3214b180b).
> Refactor: terraform app service deployment

- .github/workflows/codeql.yml
Only run the CodeQL Analyze job if there are languages to analyze.
I'm not 100% this is the right syntax :crossed_fingers:
> CI: guard against empty language array for CodeQL runs

- .github/workflows/codeql.yml
Follow-up to #2137, the syntax was in fact wrong :roll_eyes: 
Failed workflow run: https://github.com/cal-itp/benefits/actions/runs/9391520844
> Fix: correct invalid syntax in CodeQL

- terraform/app_service.tf
Closes #1948 
This is what I see in the Azure portal. Looks like they might've renamed the button
<br>
<br>
Message when you click the button:
<br><br>
> Refactor: delete app setting meant for refreshing secrets

- terraform/app_service.tf
Closes #2118 
1. Get this branch locally
2. [Initialize terraform locally for `dev`](https://docs.calitp.org/benefits/deployment/infrastructure/#local-development)
3. `terraform plan`
4. Verify output: `No changes. Your infrastructure matches the configuration.`
> Fix: terraform source control block

- benefits/oauth/analytics.py
- benefits/oauth/views.py
- tests/pytest/oauth/test_analytics.py
- tests/pytest/oauth/test_views.py
Closes #2049 
To test the error condition, insert something like `claim_value = "20"` after line 73 in `benefits.oauth.views.authorize`. Then check that `"error_code": 20` appears as a property of `"event_properties"` in the log.
The behavior originally described in these notes was fixed by #2127.
~~When running the test `test_authorize_success_without_verifier_claim`, the oauth middleware `VerifierUsesAuthVerificationSessionRequired` that decorates the `authorize` view seems to behave differently compared to debugging the application.~~
~~Specifically, [line 19](https://github.com/cal-itp/benefits/blob/dev/benefits/oauth/middleware.py#L19C12-L19C59) in `benefits/oauth/middleware.py` evaluates to a `<Mock>` object if running the test, but it evaluates to a boolean if debugging the …
> Feat: analytics for auth claims flow

- terraform/pipeline/deploy.yml
Resolves some issues with `Warning`s in the output.
For example:
```
~ resource "azurerm_storage_account" "main" {
- edge_zone                         = "" -> null
...
name                              = "sacdtcalitpd001"
~ primary_access_key                = (sensitive value)
~ primary_blob_connection_string    = (sensitive value)
~ primary_connection_string         = (sensitive value)
~ secondary_access_key              = (sensitive value)
~ secondary_blob_connection_string  = (sensitive value)
~ secondary_connection_string       = (sensitive value)
- secondary_file_endpoint           = "" -> null
- secondary_file_host               = "" -> null
tags           
```
> Chore: update Terraform version in pipeline

- tests/pytest/core/test_models.py
Closes #2108
Minor refactor to align the [`test_EligibilityType_enrollment_index_template`](https://github.com/cal-itp/benefits/blob/dev/tests/pytest/core/test_models.py#L241) and [`test_EligibilityType_enrollment_success_template`](https://github.com/cal-itp/benefits/blob/dev/tests/pytest/core/test_models.py#L251) tests.
> Refactor(tests): Update eligibility type enrollment index template test

- docs/development/.pages
- docs/development/application-logic.md
Based on some recent discussion and onboarding new team members, this page provides a high-level overview of all of the main phases through which the user is taken by the app.
Preview page: https://benefits-2139--cal-itp-previews.netlify.app/development/application-logic/
> Docs: overview of the application logic

- .devcontainer/devcontainer.json
- .devcontainer/postAttach.sh
- appcontainer/Dockerfile
- appcontainer/nginx.conf
- compose.yml
- terraform/app_service.tf
Part of #2153 
Related to:
* https://github.com/cal-itp/docker-python-web/pull/42
* https://github.com/cal-itp/eligibility-server/pull/463
This PR should be merged after the one in `docker-python-web`.
From that PR's description:
> There are two directories with application code:
>
> * `run/` is created by this image and contains the default `nginx` and `gunicorn` configuration
> * `app/` is created by the consuming image (`benefits` or `eligibility-server`) and contains the application code
> 
> This image defines these two directories under `/home/calitp/` (the Docker `$USER`s home).
> 
> This PR moves them to the top-level `/calitp/` (again, from the Docker `$USER`).
> 
> This change is part of addressing #2153. When we enable the setting `WEBSITES_ENABLE_APP_SERVICE_STORAGE=true`, …
> Refactor: move the application directory up a level

- .github/workflows/add-to-project-dependabot.yml
New practice established in the June 2024 Backlog Review session. This is part of focusing the Sprint time on Sprint items and saving dependencies for Slush time.
> Feat: default dependabot PR status to In review

- terraform/app_service.tf
This reverts commit ff98a62f1e6546f5e9e894fd4090f82ac9a110c2.
Follow up to https://github.com/cal-itp/benefits/pull/2160#issuecomment-2166411527
> Revert "fix(terraform): turn on manual integration"

- docs/deployment/infrastructure.md
This PR  reorganizes the infrastructure documentation to be friendlier to a new developer.
- Added an intro section with more context on how to get access
- Moved up sections that explain the environments and architecture
- Made some content edits to remove unnecessary detail  and use clearer wording
> Docs: clean up / reorganize Infrastructure documentation

- terraform/app_service.tf
Azure will manage the `/home` directory and restore it when the app restarts.
Closes #2153
> Feat: enable app service storage

- benefits/core/context_processors.py
This PR fixes #2168  by making sure the context variable `agency.help_templates` doesn't include empty strings.
The logic previously did not consider the case where the admin interface populates the `help_template` as an empty string rather than `None`. If you load an `EligibilityVerifier` fixture that doesn't specify `help_template`, the field gets set as `None`.
> Fix: verifier help templates

- benefits/core/templates/core/includes/lang-selector.html
- benefits/enrollment/views.py
Closes #2058 
On the enrollment success page, the Django [`set_language`](https://github.com/django/django/blob/main/django/views/i18n.py#L30) redirect view was redirecting the user to the enrollment index page when the language was changed. Looking at the [Django documentation](https://docs.djangoproject.com/en/5.0/topics/i18n/translation/#the-set-language-redirect-view), adding a `next` parameter in the `POST` data and explicitly including the enrollment success page url in the context seems to be what was missing.
For all other views, when changing languages, I think we don't see this behavior because the `Referer` request header contains the address of the same view, but for the enrollment success view, `Referer` is `/enrollment/` (I think because it is called from `/enrollment/` …
> Fix: changing languages on the enrollment success page

- benefits/oauth/views.py
Closes #2184
This PR changes the [`logout` view to call the helper function `create_client`](https://github.com/cal-itp/benefits/blob/dev/benefits/oauth/views.py#L104). Just a note that I couldn't recreate the exception described in #2184, but in any case, this PR makes creating an `oauth_client` consistent across the `login`, `authorize`, and `logout` views of [`oauth`](https://github.com/cal-itp/benefits/blob/dev/benefits/oauth/views.py).
> Fix: oauth client not registered exception in logout

- .github/ISSUE_TEMPLATE/release.yml
- .github/workflows/codeql.yml
- .github/workflows/deploy.yml
- .github/workflows/labeler-deploy-dev.yml
- .github/workflows/labeler-docs.yml
- .github/workflows/labeler-infrastructure.yml
- .github/workflows/mkdocs.yml
- .github/workflows/tests-ui.yml
- benefits/secrets.py
- docs/configuration/README.md
- docs/configuration/data.md
- docs/configuration/oauth.md
- docs/deployment/README.md
- docs/deployment/infrastructure.md
- docs/deployment/release.md
- docs/deployment/workflows.md
- docs/development/README.md
- docs/development/application-logic.md
- docs/development/commits-branches-merging.md
- docs/development/i18n.md
- docs/development/models-migrations.md
- docs/getting-started/README.md
- docs/getting-started/documentation.md
- docs/product-and-design/analytics.md
- docs/product-and-design/copy-delivery.md
- docs/tests/automated-tests.md
- terraform/azure-pipelines.yml
- terraform/pipeline/deploy.yml
- terraform/pipeline/workspace.py
This PR implements the first step of code changes needed to transition the `benefits` repository to tag-based deployments as described in #1527. The code changes are associated with:
- GitHub workflows
- GitHub Issues template
- Terraform
- References to `dev` in the documentation or code comments
To merge these code changes:
These may be helpful when reviewing [workspace.py](https://github.com/cal-itp/benefits/pull/2202/files#diff-33a8fda4d235c86352a2629618f4d0829b626df6084edef709ad22d97e8f80fc):
- `REASON` = `Build.Reason`: The event that caused the build to run.
- `OTHER_SOURCE` = `System.PullRequest.SourceBranch`: The branch that is being reviewed in a pull request.
- `INDIVIDUAL_SOURCE` = `Build.SourceBranchName`: The name of the branch in the triggering repo the build was queued …
> Chore: Rename `dev` branch to `main`

- .devcontainer/Dockerfile
- .devcontainer/postAttach.sh
- .dockerignore
- .github/workflows/check-migrations-and-messages.yml
- .github/workflows/deploy.yml
- .github/workflows/tests-cypress.yml
- .github/workflows/tests-pytest.yml
- .github/workflows/tests-ui.yml
- appcontainer/Dockerfile
- pyproject.toml
- terraform/azure-pipelines.yml
- terraform/pipeline/deploy.yml
- terraform/pipeline/tag.py
- terraform/pipeline/workspace.py
- tests/pytest/test_version.py
This PR implements the second step of code changes needed to transition the benefits repository to tag-based deployments as described in https://github.com/cal-itp/benefits/issues/1527. 
The code changes are associated with:
- GitHub workflows
- Azure DevOps/Terraform pipeline
- Python package versioning using `git` metadata
The last step needed to close #1527, will be to remove the `test` and `prod` branches and remove references to them in all the GitHub workflows.
> Refactor: implement tag-based deployment

- benefits/core/admin.py
- benefits/core/migrations/0014_staff_group_view_permissions.py
Closes #2199 
This is what the user sees upon logging in:
When viewing model objects, the user sees a read-only view of fields that are not in the `exclude` list for each model.
Here is an example using the `TransitAgency` model:
> Feat: Cal-ITP staff can view configuration values

- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
- benefits/oauth/analytics.py
- benefits/oauth/middleware.py
- benefits/oauth/redirects.py
- benefits/oauth/templates/oauth/system_error.html
- benefits/oauth/urls.py
- benefits/oauth/views.py
- tests/pytest/oauth/test_analytics.py
- tests/pytest/oauth/test_middleware_authverifier_required.py
- tests/pytest/oauth/test_redirects.py
- tests/pytest/oauth/test_views.py
Closes #2019 
* Implements a new error screen in the `oauth` app
* Handles errors on creation/registration of the OAuth client
* Handles errors for all OAuth client method calls
* Sends a new analytics event `oauth error` in all cases
* `operation` property indicates the specific client call: `init`, `authorize_redirect`, `authorize_access_token`, and `load_server_metadata`
* `message` property describes the exception
* Captures an exception in Sentry in all cases
1. Checkout the branch locally
2. Run `bin/init.sh` to get the PO file updates
3. Launch the app with `F5`
4. Select an agency or enter via their slug URL
5. Manually enter the URL in the browser: `/oauth/error`: see the error page
6. Attempt a Login.gov flow for the agency (without configuring the `AuthProvider`): see the error …
> Feat: handle OAuth errors

- terraform/azure-pipelines.yml
- terraform/pipeline/deploy.yml
- terraform/pipeline/tag.py
This PR is a follow-up to PR #2213. The terraform `plan` and `apply` steps were not running when expected because the conditions on the steps were not evaluating correctly. Contrary to the [documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops#parameters-in-conditions), we noticed that [`parameters` don't get evaluated in `conditions`](https://github.com/cal-itp/benefits/blob/2f628637fefe66fde24cebecdcd4cf3a7d6ddb1b/terraform/pipeline/deploy.yml#L74-L75). Because of this, even though `tag_type` was set in [`Terraform apply`](https://github.com/cal-itp/benefits/blob/main/terraform/pipeline/deploy.yml#L60), this step wouldn't run when a tag was pushed.
This PR fixes this behavior by changing `parameters.tag_type` to …
> Fix: terraform plan and apply conditions

- benefits/enrollment/templates/enrollment/index.html
- benefits/enrollment/views.py
- tests/pytest/enrollment/test_views.py
Closes #2195 
Given that the Littlepay Hosted Card Tokenization overlay supports multiple languages, this PR uses this feature to set the overlay's language to the user's language in Benefits.
Note that the Littlepay docs list `es_419` as the code for `Spanish (Latin America)`, but this seems to be a typo since the overlay did not work with this code, instead it does work with `es-419`.
Run through a complete flow until you get to the enrollment index page. Then, change languages in Benefits and close/open the overlay to see the overlay in the language that was selected in Benefits.
> Feat: set language code on Littlepay overlay

- terraform/pipeline/deploy.yml
- terraform/pipeline/tag.py
Closes #2240 
This PR normalizes setting `tag_type`. It moves the setting of `tag_type` from the shell into `tag.py`, consistent with how setting the environment-related variables is done in [`workspace.py`](https://github.com/cal-itp/benefits/blob/main/terraform/pipeline/workspace.py#L52-L53).
> Chore: normalize lines for tag_type

- benefits/core/templates/core/base.html
closes #2271 
The problem: Vertical alignment of the `We use the ...` paragraph is off for both Desktop and Tablet.
The issue:
These two divs need to be siblings, not a parent/child relationship. Having a `row justify-content-center` _inside_ another `row justify-content-center` is giving the paragraph in the child div a more padding left and right. The heading text and the paragraph text need to be siblings, not a parent/child.
This parent/child relationship was created in the `base.html` file that the `confirm.html` is based off of.
Since `explanatory-text-wrapper` is _only_ used on this `confirm.html` page, I was able to safely change the `base.html` to fix the issue, and know that this is will only change the confirm page and not any other pages.
Test is by looking at all pages for …
> Fix: Eligibility Confirm - Unnest explanatory-text-wrapper div

- .github/ISSUE_TEMPLATE/release.yml
- docs/deployment/.pages
- docs/deployment/hotfix.md
- docs/deployment/release.md
- docs/deployment/rollback.md
- docs/deployment/workflows.md
- docs/development/commits-branches-merging.md
Closes #1249
This PR, which updates the documentation and the `New Release` issue template, is the last followup to PR #2213.
> Chore: update documentation and issue template due to tag-based releases

- benefits/eligibility/templates/eligibility/index.html
closes #2288 
- Go through full flow in desktop and mobile to ensure no visual regressions
> Fix: Elig Index - Wrap explanatory text in centered row

- .vscode/settings.json
Closes #2281 
VS Code associates `.pages` files with `markdown`. Because of this, the indentation in the files is not preserved when saving them using VS Code. This PR [associates](https://code.visualstudio.com/docs/languages/overview#_add-a-file-extension-to-a-language) `.pages` files with `yaml` so that formatting is preserved when saving them using VS Code.
> Chore: associate .pages files with yaml

- benefits/in_person/apps.py
- benefits/in_person/urls.py
- benefits/in_person/views.py
- benefits/settings.py
- benefits/urls.py
- tests/pytest/in_person/test_views.py
Closes #2295 and closes #2284 
**Not logged in yet**
- Start the app
- Use browser's URL bar to go to `/in_person/eligibility` or `/in_person/enrollment`
- You should be prompted with the admin interface login screen
- Log in
- You should see an empty page  
**Logged in**
- Start the app
- Go to `/admin`
- Log in
- Use URL bar to go to `/in_person/eligibility` or `/in_person/enrollment`
- You should see an empty page
> Feat: introduce separate app for in-person eligibility / enrollment

- benefits/settings.py
> Hide native Django login fields

- docs/README.md
- added Medicare cardholders to supported enrollment pathways table
> Adding Medicare cardholders

- benefits/core/models.py
- tests/pytest/core/test_models.py
Follow-up to #2307 
If we use `group.transitagency` to get a `Group`'s `TransitAgency`, Django will raise a `RelatedObjectDoesNotExist` error if the group does not have a `TransitAgency`.
The Django docs recommend either catching the exception or checking for the attribute. This PR checks if the group has the attribute before trying to get the object.
https://docs.djangoproject.com/en/5.1/topics/db/examples/one_to_one/
> Fix: getting a group's transit agency

- tests/pytest/core/test_admin.py
closes #2242 
This PR does not add any code, but it adds 2 tests. 
This PR's tests test the `add_staff_user_to_group` method, which runs in the `pre_login_user` callback. In these tests, we are testing a new scenario that will come up when the Admin app starts allowing Transit Agency admin users:
- Engineers add a new transit agency's domain to the `GOOGLE_SSO_ALLOWABLE_DOMAINS` list, like `cst.org`
- Users with a `cst.org` email address can create Admin accounts via the site's OAuth button.
- But, these users should not be added to the Cal-ITP group, because their email addresses are not specifically in the `GOOGLE_SSO_STAFF_LIST` list.
These 2 specs test out both scenarios of ensuring a transit agency user does not get added to the Cal-ITP group, and to ensure that people with email …
> Admin: Test that transit user does not get added to calitp group

- benefits/templates/admin/agency-base.html
- benefits/templates/admin/agency-dashboard-index.html
Part of #2246
This PR creates a base template which defines the header navbar and includes the styles that every in-person eligibility/enrollment page will need at a minimum. It extends Django's [admin base template](https://github.com/django/django/blob/main/django/contrib/admin/templates/admin/base.html). 
The `agency-dashboard-index.html` template is also refactored to use this new base template.
> Feat: create base template for in-person eligibility

- benefits/static/css/admin/styles.css
- benefits/static/img/icon/box-arrow-right.svg
- benefits/templates/admin/agency-base.html
Closes #2246
This PR is the last part of #2246 and it implements the top right usertools block for in-person eligibility/enrollment pages. It overrides the `text-transform` property it inherits from Django's base admin site so that the welcome message is capitalized (WELCOME, USER) but the sign out message isn't (Sign out). ~It uses the same idea to remove the underline from `Sign out`.~ In addition, it adds a [Bootstrap icon](https://icons.getbootstrap.com/icons/box-arrow-right/) and uses it as the `Sign out` icon.
> Feat: implement the top-right usertools block

- benefits/templates/admin/agency-base.html
closes #2328 
This PR adds jQuery to the `agency-base` template, so all Admin pages that use this template will have access to jQuery. jQuery is used in `form.html` - the main form base template that the app uses for all forms.
> Chore: Admin - Add jQuery to agency base template

- benefits/in_person/forms.py
- benefits/in_person/templates/in_person/eligibility.html
- benefits/in_person/views.py
- benefits/routes.py
- benefits/static/css/admin/styles.css
- tests/pytest/in_person/test_views.py
closes #2269 
http://localhost:11369/in_person/eligibility/
Light mode
Dark mode
- Follow https://github.com/cal-itp/benefits/pull/2325#issue-2489892807 to get into the dashboard
- Click New Enrollment button
- Test clicking submit without choosing anything
- Test clicking submit with only checkbox
- Test clicking submit with only radio button
- Use <kbd>enter</kbd> or <kbd>spacebar</kbd> and <kbd>tab</kbd> for form completion and submission
- Use <kbd>tab</kbd> to skip to main content correctly
- Accessibility: Passes WCAG AA (except for 1 known ARIA form issue coming from `form.html` - which isn't going to be changed in this PR)
- Check that the Console warning area is empty
- The log out user tools area does not get rendered.
- Has jQuery library loaded
- Does not have recaptcha
- Uses …
> Admin: Eligibility View

- tests/pytest/core/test_admin.py
> Admin test: Use settings instead of mocker

- benefits/enrollment/enrollment.py
- benefits/enrollment/views.py
- tests/pytest/enrollment/test_enrollment.py
- tests/pytest/enrollment/test_views.py
Part of #2244 
Extracts logic from `benefits.enrollment.token` view into `benefits.enrollment.enrollment` module. This is needed for the in-person enrollment view.
Similar to #2338 
There shouldn't be any regressions with enrollment in the Benefits app.
> Refactor: enrollment token logic

- benefits/settings.py
- terraform/app_service.tf
This PR sets the login form configuration using an environment variable.
Before merging this PR, ensure that:
> Feat: customize the login form using an environment variable

- benefits/in_person/forms.py
- benefits/in_person/templates/in_person/enrollment.html
- benefits/in_person/urls.py
- benefits/in_person/views.py
- benefits/routes.py
- benefits/settings.py
- benefits/static/css/admin/styles.css
- tests/pytest/in_person/test_views.py
Part of #2244
This PR implements the `enrollment` view:
- front-end template which shows the transit processor's enrollment form as an iframe
- back-end handling of `GET` and `POST` requests to `/in_person/enrollment`
The templates which this view redirects to are all blank. A separate PR will implement `in_person/enrollment/success.html`, and #2345 will implement the error templates. 
This PR also does not include sending analytic events since #2245 will do that.
- Make your Google account be seen as a "transit agency staff user" - i.e. not put into the "Cal-ITP" group but still marked as `is_staff`:
- Set your `GOOGLE_SSO_STAFF_LIST` environment variable to `*`
- Make sure your `GOOGLE_SSO_ALLOWABLE_DOMAINS` environment variable is `compiler.la`
- Launch the app and go to `/admin`
- Log …
> Feat: in-person enrollment view

- benefits/core/migrations/local_fixtures.json
- benefits/eligibility/templates/eligibility/includes/modal--medicare.html
- benefits/eligibility/templates/eligibility/includes/selection-label--medicare.html
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
- tests/cypress/specs/benefit-select.cy.js
closes #2351 
closes #2350 
closes #2358 
To get the new fixture and copy:
```
./bin/reset_db.sh
./bin/init.sh
```
> Medicare: Eligibility Index - Modal and Radio Button Label

- benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--medicare.html
- benefits/eligibility/templates/eligibility/start--medicare.html
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
Closes #2352
This PR implements a new template for the start screen for the Medicare flow. The Spanish translation will be implemented as part of #2369.
> Feat: Medicare cardholder eligibility start template

- benefits/admin.py
- benefits/static/css/admin/styles.css
- benefits/templates/admin/agency-base.html
- benefits/templates/admin/login.html
closes #2265 
- Sets `site_header`, `site_title` for BenefitsAdminSite
- CSS: Add default Benefit focus states to login inputs, buttons
- CSS: Removes darkmode from Agency Base and Login
- Templates: Login and Agency Base - Moves Django's Login.css code to Styles.css and changes some of the style declarations
- Login template: Creates login.html to override parts of Django's login.html's branding section to add the Cal-ITP image.
- Test with `SSO_SHOW_FORM_ON_ADMIN_PAGE` set to False 
- Test with `SSO_SHOW_FORM_ON_ADMIN_PAGE` set to True
- Test with an error/info/warning message
- Test on dark (browser set to dark mode) and light mode - Should only show light mode
- Test focus states
- Test with a wrong password, error message should show up
This PR also resolves all outstanding WCAG 2.0 …
> Admin: Log in page

- benefits/in_person/templates/in_person/enrollment/success.html
- benefits/in_person/views.py
- benefits/static/css/admin/styles.css
- benefits/static/img/icon/check-circle-fill.svg
Closes #2244 
This PR implements `in_person/success.html`, completing the happy path for in-person enrollment.
> Feat: success template for in-person enrollment

- benefits/in_person/templates/error-base.html
- benefits/in_person/templates/in_person/enrollment/reenrollment_error.html
- benefits/in_person/templates/in_person/enrollment/retry.html
- benefits/in_person/templates/in_person/enrollment/server_error.html
- benefits/in_person/templates/in_person/enrollment/system_error.html
- benefits/in_person/views.py
- benefits/static/css/admin/styles.css
- benefits/static/img/icon/exclamation-circle-fill.svg
- tests/pytest/in_person/test_views.py
Closes #2345 
This PR implements the templates for in-person error pages and also adds the call to send a Sentry notification for those errors.
You can view the pages by going directly to the URLs:
- system error: `in_person/enrollment/error`
- server error: `in_person/error`
- re-enrollment error: `in_person/enrollment/error/reenrollment`
- user enrollment error: `in_person/enrollment/retry`
If you want to test the actual view redirecting logic, you'll need to simulate the errors.
You can simulate errors by changing the returned `Status` and exception on this line: https://github.com/cal-itp/benefits/blob/e6af3db073e1c816b1b2e61a8e97bb6989d46e42/benefits/in_person/views.py#L78
For re-enrollment errors, you also need the dates to be populated, so:
- (Temporarily) override the value …
> Feat: error templates for in-person enrollment

- benefits/core/analytics.py
- benefits/core/models.py
- benefits/eligibility/analytics.py
- benefits/eligibility/views.py
- benefits/enrollment/views.py
- docs/product-and-design/analytics.md
- tests/pytest/core/test_analytics.py
- tests/pytest/core/test_models.py
- tests/pytest/eligibility/test_analytics.py
Part of #2248, update new events that are sent.
* Renames event/user property `eligibility_types` to `enrollment_flows`
* Renames event `selected eligibility verifier` to `selected enrollment flow`
* Updates the value sent for event/user property `eligibility_verifier` to the same logic as from #2267
> Refactor: analytics for `EnrollmentFlow`

- benefits/enrollment/analytics.py
- benefits/enrollment/templates/enrollment/index.html
- docs/development/application-logic.md
- docs/product-and-design/analytics.md
Part of #2249
- Analytics event `started payment connection` renamed to `started card tokenization`
- Analytics event `closed payment connection` renamed to `ended card tokenization`
- Analytics event property `payment_group` renamed to `enrollment_group`
- Updated docs
> Refactor: analytics for PaymentProcessor

- benefits/templates/registration/logged_out.html
closes #2359 
This PR creates a template, `logged_out.html`, which extends `agency-base` to get Bootstrap and Button styles, and combines code from:
- the default Django log out page for the HTML https://github.com/django/django/blob/39de2e97a06d0317973b280bc159ca6f89fc64e3/django/contrib/admin/templates/registration/logged_out.html
- the default Django log in page css style (adding the `login`class to the body element) brings in default Django login page styles
- the customizations created in app's Log in page https://github.com/cal-itp/benefits/blob/main/benefits/templates/admin/login.html for the repeated styles of the branding header and the main div.
0 WCAG AA issues.
> Admin: Log out page styled

- benefits/in_person/templates/in_person/enrollment.html
Closes #2398 
Latest mock-up:
Screenshot of what it looks like now in this branch:
> Refactor: remove "Go back" button from in-person enrollment

- benefits/settings.py
- benefits/templates/admin/agency-base.html
closes #2380 
The Administrator app should use "Log in" and "Log out" in app copy. This PR changes this in:
- Google SSO button copy
- Admin header
Test this by logging in and out as a super user and a transit agency user.
> Admin: Use "log" not "sign"

- benefits/admin.py
- benefits/in_person/templates/error-base.html
- benefits/in_person/templates/in_person/eligibility.html
- benefits/in_person/templates/in_person/enrollment.html
- benefits/in_person/templates/in_person/enrollment/success.html
- benefits/in_person/views.py
- benefits/templates/admin/agency-base.html
- benefits/templates/admin/agency-dashboard-index.html
- benefits/templates/admin/login.html
- benefits/templates/registration/logged_out.html
- tests/pytest/in_person/test_views.py
closes #2381 
- Updates all Administrator app page titles according to what's on https://miro.com/app/board/uXjVKwXyUy0=/ - check the text above the bordered page sections
- Uses Django admin variables or Django template default titles for as much as possible: https://docs.djangoproject.com/en/5.1/ref/contrib/admin/#adminsite-attributes
- Updated anywhere we could use above variables
> Admin: Update admin page titles

- benefits/eligibility/analytics.py
- benefits/eligibility/views.py
- benefits/in_person/views.py
- benefits/oauth/analytics.py
- docs/development/application-logic.md
- docs/product-and-design/analytics.md
- tests/pytest/eligibility/test_views.py
- tests/pytest/oauth/test_analytics.py
Part of #2247 
Included a number of small renames/docs updates that I missed during #2379.
> Refactor: analytics for `claims_provider`

- benefits/eligibility/forms.py
- benefits/in_person/forms.py
- tests/pytest/eligibility/test_views.py
- tests/pytest/in_person/test_views.py
closes #2396 
- Only display supported enrollment flows (in-person, digital or both) on Eligibility forms for Digital flow and In-Person flow.
- Update tests: Adds a spec case to both in-person and digital specs, where a form must filter out the 2 supported flows out of 3 total flows.
- Set some enrollment flows to be In-Person only or Digital only via the Admin tool
- Check the digital flow's eligibility page
- Log in as a CST staff user on Admin and check the in-person flow page
> Eligibility: Filter enrollment flows by supported method

- tests/pytest/in_person/test_views.py
Part of #2245 (and #2269, just by virtue of cleaning up the test names)
This PR adds assertions for the analytics calls that are expected to be made in in-person view functions.
> Refactor: test name clean-up and assertions for in-person analytics

- benefits/templates/admin/agency-base.html
- benefits/templates/admin/includes/bootstrap.html
- benefits/templates/admin/includes/branding-login.html
- benefits/templates/admin/includes/favicon.html
- benefits/templates/admin/includes/style-admin.html
- benefits/templates/admin/includes/usertools.html
- benefits/templates/admin/login.html
- benefits/templates/registration/logged_out.html
Closes #2425
This PR has a few cleanups. It fixes the indentation of the `usertools` block in `agency-base`; extracts `favicon`, `Bootstrap`, and `styles.css` for the admin app; and extracts  the `login` and `logged_out` branding.
> Chore: extract common Admin overrides

- benefits/templates/admin/includes/usertools.html
Part of #2433 
@indexing mentioned we don't need the "Change password" feature for the in-person event on October 17th and that it would be better to not show it.
> Chore: remove "Change password" link from admin interface for now

- benefits/enrollment/templates/enrollment/index.html
- benefits/in_person/templates/in_person/enrollment/index.html
- docs/development/application-logic.md
- docs/product-and-design/analytics.md
Looking through the analytics/warehouse as part of https://github.com/cal-itp/data-infra/pull/3468 and I noticed this slight inconsistency.
E.g. our OAuth events use
* `started sign in`
* `finished sign in`
So this small fix aligns the card tokenization event.
_this was my bad, I wrote the initial spec in #2249_
> Refactor: rename the finished card tokenization event

- benefits/settings.py
Closes #2445 
#2445 revealed that in production, the `frame-src` directive only includes `google.com` and therefore blocks the transit processor iframe.
This is because in `settings.py`, the logic was to throw away the originally assigned value of `CSP_FRAME_SRC` and instead use whatever is in `env_frame_src`.
https://github.com/cal-itp/benefits/blob/8cce5addeaff897220fd97e8a7eb25f3cbe0b285/benefits/settings.py#L310-L315
This logic was fine when the originally assigned value was `'none'` since the directive only allows [`'none'` or a space separated list of values](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-src#syntax), but in [a23b51e2](https://github.com/cal-itp/benefits/commit/a23b51e26511110af8528bdcd4c70027ad6635ba#diff-d71405aa44f1e899a9cd …
> Fix: add to CSP_FRAME_SRC

- benefits/enrollment/templates/enrollment/includes/media-item--bankcardcheck--index.html
closes #2428 
- Make a fix to the Enrollment Index page that shows up on the Agency Card, Veterans, Senior, Medicare flows (all but CalFresh).
- Remove the space that appears after the Littlepay link by *not* using the includes and using the `a href` link code directly, allowing the link code to be right next to the copy, which allows the HTML to be rendered w/o any extra whitespaces.
- The only drawback to this is that if there is ever a style change to `modal-trigger`, we need to make sure the change is made here too. I found this drawback to be acceptable, b/c I think most changes if any that happen to the modal-trigger will be done with CSS classes, and it wouldn't be hard to add the CSS classes in both places. I'm open to the alternatives considered though.
- Tried removing line …
> Enrollment Index: Remove space after Littlepay

- README.md
- docs/README.md
closes #2448 
- Updates README that appears https://github.com/cal-itp/benefits/
- Update README that appears https://docs.calitp.org/benefits/, preview link here https://benefits-2457--cal-itp-previews.netlify.app/
I don't know why all the other tables on the docs/README.md file got formatted, but seems to read better.
> Docs: add note about Compiler to both READMEs

- .devcontainer/Dockerfile
- .dockerignore
- appcontainer/Dockerfile
- pyproject.toml
Closes #2389.
Fixes the issue with the dynamic version calculation being incorrect, because of a dirty git index during Docker build time / pip install time.
There's no reason to have the .git directory in the app image, same with all the extra files, tests, .devcontainer, etc.
Uses the approach from eligibility-server: https://github.com/cal-itp/eligibility-server/blob/main/Dockerfile
1. Check out this branch locally, ensure you have no pending/unstaged changes (`git status`)
1. Apply an annotated tag e.g. `git tag -a 2024.10.999`
1. `docker compose build --no-cache client` to rebuild the app image
1. `docker compose up -d client` to start a new app container
1. `docker compose exec -ti client /bin/bash` to connect to running container
1. `python manage.py shell` to enter a Django shell …
> Refactor: Multi-stage Docker build for app image

- benefits/core/templates/core/base.html
- benefits/locale/en/LC_MESSAGES/django.po
- benefits/locale/es/LC_MESSAGES/django.po
> Footer: Add Compiler line

- benefits/enrollment/templates/enrollment/success.html
closes #2429 
- Reduces the H1 parent container width from `col-8` to `col-7`, only on the Enrollment Success page, to get the headline to break into a second line at a semantic spot:
- Alternatives considered: Use a manual `<br>` but that doesn't scale responsively well, and it's really hacky. 
A note to other developers - this is a bit of a heavy-handed custom override, and we (dev) don't want to be doing things like this too often. We want to be building an app that exists and works great in all browser-widths and all browser dimensions as possible. If the `col-7` trick didn't just happen to conveniently work, I wouldn't pursue this fix. This is truly a one-off case.
> Enrollment Success: Reduce h1 parent container width for readability

- .github/ISSUE_TEMPLATE/release.yml
Adds a new question / section for the the Release process issue template to make it easier to paste in the Slack thread in a standard location.
This is not required to create a Release issue. Also removed the requirement for smoke tester, as that is not always known when the Release issue is created.
> Feat: add Slack thread to Release issues

- benefits/templates/error.html
closes #2475 
This is a small design fix request from @srhhnry 
Makes the error page text easier to read, by making the text width narrower from 8 columns to 6 columns on desktop.
﻿
- Run the app in `Debug=False` mode
- Go to a random fake URL, like `/asdfsdf`
> Error pages: Make text area narrower for better legibility

- benefits/templates/admin/base_site.html
Closes #2443
This PR overrides the `admin/base_site.html` template to show the favicon in the Superuser's admin page by [extending an overridden template](https://docs.djangoproject.com/en/5.1/howto/overriding-templates/#extending-an-overridden-template).
Log in as a Superuser to the admin page, click around the different models and verify that the favicon appears on the pages.
> Fix: show favicon on the Superuser's admin

- .devcontainer/Dockerfile
Part of #2490 
This is an optional PR. If we don't want this in the devcontainer, we can just close this.
This PR installs CLI tools from Google, including [`cwebp`](https://developers.google.com/speed/webp/docs/cwebp), to create and work with WebP images, giving us a consistent way to create WebP images rather than each of us doing it our own way, e.g. using online tools like https://squoosh.app/ (from https://github.com/GoogleChromeLabs/squoosh) or using [ImageMin](https://web.dev/articles/serve-images-webp#convert_images_to_webp), etc.
I couldn't find a way to just install `cwebp`, which is what I think we'd mainly use; the full `webp` package contains `cwebp`, so just install the whole thing.
Rebuild the devcontainer, and then in a terminal, run `cwebp` to see the help screen.
``` …
```
> Feat: add webp CLI to devcontainer

- benefits/static/css/styles.css
Part of #2490 
This PR will be merged in to #2523.
I think it makes sense for the changes from both PRs to be merged into `main` together, but I also wanted to have separate code reviews.
I took the color from the left side of the background image and used that as the `background-color` for the main section of the landing page.
The WebAIM contrast checker shows this contrast ratio [passes WCAG AAA requirements](https://webaim.org/resources/contrastchecker/?fcolor=FFFFFF&bcolor=1A1B16).
| Desktop | Mobile |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/c1652518-c17e-485d-beba-90d91e851ac2) | ![localhost_11369_(Moto G Power)](https://github.com/user-attachments/assets/8eecbf4c-403f-45f2-8866-60df576eb496) |
> Feat: fallback background color

- benefits/static/css/styles.css
Closes #2431
This PR fixes the Agency selector modal to arrange the agencies in the following manner:
- 2 in the first row and 1 centered in the second row when 3 agencies are shown
- 2 in the first row and 2 in the second row when 4 agencies are shown
- 2 in the first row, 2 in the second row, and 1 centered in the third row when 5 agencies are shown
- all in one column in mobile view
Replace your local `TransitAgency` fixtures to use (the data is incorrect, but we only need to review the modal)
```
{
"model": "core.transitagency",
"pk": 1,
"fields": {
"active": true,
"slug": "cst",
"short_name": "CST (local)",
"long_name": "California State Transit (local)",
"info_url": "https://www.agency-website.com",
"phone": "1-800-555-5555",
"index_template": "core/index--cst.html", …
```
> Fix: modal for 4 or more agencies

- benefits/core/templates/core/base.html
- benefits/core/templates/core/includes/lang-selector.html
- benefits/core/templates/core/includes/nocookies.html
- benefits/core/templates/core/includes/noscript.html
- benefits/core/templates/core/landing.html
- benefits/in_person/templates/error-base.html
- benefits/in_person/templates/in_person/eligibility.html
- benefits/in_person/templates/in_person/enrollment/index.html
- benefits/in_person/templates/in_person/enrollment/success.html
- benefits/settings.py
- benefits/static/css/styles.css
- benefits/templates/admin/agency-dashboard-index.html
closes #2491 
- Remove CA State Web Template CSS, which will then remove the call to the CA State Web Template font
- Remove CA State Web Template domain from CSP
- Makes any CSS fixes necessary
- fix:`text-left` to `text-start`
- fix: add css to fix skip nav
- fix: button focuses
- slight refactor: buttons in general. could be greatly refactored to mostly be written with css variables instead, reducing the number of new classes/modified classes.
- Trigger the skip nav
- Go through the whole app via keyboard, paying attention to the way the modals behave with the radio buttons
- Manually enable the JavaScript/Cookies warnings via HTML (remove the no display class) and compare it visually with the current one
- Check the app on responsive widths
> Refactor: Remove CA State Web Template

- benefits/core/migrations/local_fixtures.json
This is a follow-up to #2471 to add back values for the local CST TransitAgency fixture's `info_url`, `phone`, `logo_large`, and `logo_small` fields.
In that PR, those values were removed from the local fixtures because the idea at one point was to use them as defaults for those fields. 
We decided to default to the empty string instead after discussion in https://github.com/cal-itp/benefits/pull/2471#discussion_r1858988519 and https://github.com/cal-itp/benefits/pull/2471#discussion_r1859137740.
Currently in `main`, if you run `./bin/reset_db.sh` and run the app, you will see missing values:
**Missing logo**
**Missing `info_url` and `phone`**
> Chore: add back values for CST local fixture

- benefits/core/templates/core/base.html
- benefits/core/templates/core/includes/bootstrap-css.html
- benefits/templates/admin/agency-base.html
- benefits/templates/admin/includes/bootstrap.html
- benefits/templates/admin/login.html
closes #2551
The #2491 PR made a regression on Admin, by changing this line in the settings CSP: https://github.com/cal-itp/benefits/pull/2526/files#diff-d71405aa44f1e899a9cd920e5187aa1d02affdbd0da472eca95f814b0a8c1210R357, which then made the Bootstrap CSS version used on Admin inaccessible.
This PR:
- Moves the Bootstrap includes from Admin into Core
- Upgrades the Bootstrap includes version to 5.3.3
- Uses that includes in both Admin and Benefits apps
QA:
- QA the app flow on Benefits
- QA a in-person verification flow on Admin
- QA logging in and out of Admin
---
I've now realized that #2491 introduced a few small changes (mostly deleting style declarations no longer necessary, that were overriding CA State Web Template) to the Button CSS in the Benefits app stylesheet, but not …
> Fix: Use same Bootstrap version for both Admin and Benefits

- benefits/core/templates/core/includes/media-item.html
- benefits/eligibility/templates/eligibility/includes/media-item--contactless-card--start.html
- benefits/eligibility/templates/eligibility/includes/media-item--identification--start--cst-agency-card.html
- benefits/eligibility/templates/eligibility/includes/media-item--identification--start--login-gov.html
- benefits/eligibility/templates/eligibility/includes/media-item--identification--start--medicare.html
- benefits/eligibility/templates/eligibility/includes/media-item--identification--start--mst-agency-card.html
- benefits/eligibility/templates/eligibility/includes/media-item--identification--start--sbmtd-agency-card.html
- benefits/eligibility/templates/eligibility/start--calfresh.html
- benefits/eligibility/templates/eligibility/start--cst-agency-card.html
- benefits/eligibility/templates/eligibility/start--medicare.html
- benefits/eligibility/templates/eligibility/start--senior.html
- benefits/eligibility/templates/eligibility/start--veteran.html
- benefits/eligibility/templates/eligibility/start.html
- benefits/enrollment/templates/enrollment/includes/media-item--contactless-card--index.html
- benefits/enrollment/templates/enrollment/index--calfresh.html
- benefits/enrollment/templates/enrollment/index.html
- benefits/static/css/styles.css
closes #2542 
- Login.gov button on Mobile: 72px height
- Login.gov button on Desktop: 64px height 
- From `media-item.html` template: Removed the now unused `heading_wrapper` block, which was previously allowing us to change h1/h2/h3 declarations (see more here https://github.com/cal-itp/benefits/commit/93293f868a437fa0e30cc0b973a7a228caf23002). We now no longer have an "intervening h2" on Eligibility Start, so all the media item headings can go be upgraded to h2s.
- From `media-item.html` template: Removed the `media-body` div and class entirely. No CSS and no need.
- From the `media-item--XXXX--start.html` templates, the `media-body--details` div/class are removed. Now the `body` is a series of `<p>`s plus any modals.
- Now, the `media-item` gives you a `<li>` with an `<h2 class="h3 …
> reCAPTCHA: Eligibility Start

- benefits/core/templates/core/logged-out.html
- benefits/enrollment/templates/enrollment/success.html
closes #2544 
This is now the only page in the flow that _isn't_ `col-lg-6`. Though, as a reminder, the home page and the Help page aren't either. The Help page will remain `col-lg-8`. This page doesn't by any columns on Figma, both the headline text and the image/text combo. On the app, we are using a `col-lg-9` as our closest approximate.
A `col-lg-6` page with the now standard, 72px between header and headline, and 24px between icon and graf.
> reCAPTCHA: Enrollment Success, Logged Out

- benefits/static/css/variables.css
- docs/enrollment-pathways/README.md
- added "support for multiple identity providers" in Q4 2024
- updated epics for Q1, Q2, and H2 2025
- many small copy edits, mostly for consistency
> Product roadmap updates

- benefits/static/css/variables.css
I need to make a pull request to update the protected `recaptcha-copy` branch. I cannot rebase `main` into it. And I wanted to fix this `pre-commit` hook linting change. So here's the PR.
> chore(pre-commit): run autofix

- benefits/core/templates/core/help.html
closes #2545 (Part 1) / Error pages to come in separate PR
- Changes text alignment to `col-lg-8`
- Changes button alignment
- Squashes some of the divs into 1 div
> reCAPTCHA: Help page

- benefits/core/templates/core/includes/agency-links.html
fixes #2547 
- Why did this focus ring have square corners, rather than rounded corners - even though this <a> tag has the exact same CSS styles were applied as the rest of the links on the site and page?
Because of the `d-table`, display: table on these links. Turning that class off makes the corners round again. (I guess a table can't have rounded corners).
- But why was the `d-table` applied? (What even is `display: table` anyway. This is not a table or tabular data.)
Because without `d-table`, the links would appear in one row one after each other, like a `display: inline` text. 
- Why not use `d-block`?
That would make the links go on each line, but then the focus ring would be the whole width of the container.
- So maybe having two `<a>` links here is not right somehow. Why not use …
> Agency link focus rings are now rounded

- .github/workflows/check-metadata.py
- .github/workflows/check-metadata.yml
- .gitignore
Closes https://github.com/cal-itp/eligibility-server/issues/515
Redoing [this PR](https://github.com/cal-itp/eligibility-server/pull/516) in the Benefits repo to reuse the Slack notification app secret. 
Notify on failure:
- mismatched last update timestamp
- no eligibility types loaded
- no users loaded
> CI: workflow checks eligibility server metadata

- .github/workflows/check-metadata.yml
Getting runtime errors on the job, e.g. https://github.com/cal-itp/benefits/actions/runs/12655445699
Forgot to checkout the code, so the files aren't available to the workflow... Doh!
> Fix: check out code first in workflow

- compose.yml
The `dev` tag is no longer used as of https://github.com/cal-itp/eligibility-server/pull/414
~The `main` tag is also not being pushed! Need an update in Eligibility Server too.~
The `main` tag is where all new development/features are published, see https://github.com/cal-itp/eligibility-server/pull/519
> Fix: use `server:main` image

- benefits/core/templates/core/includes/form.html
- benefits/eligibility/forms.py
- benefits/in_person/forms.py
- benefits/static/css/admin/styles.css
- benefits/static/css/styles.css
fixes #2608 
- Form class: Passing in a class declares a class on `div.form-field-container`
- CSS refactor: Instead of adding styles on the last field, use `.form-group:has(input[type="checkbox"])` to select any parent div that has a checkbox in it.  
- A11y: Makes an Aria fix
- It is confusing to have to read both Admin's CSS and Transit User's CSS style pages to figure out what is going on. We want to make it easier for the developer to know what exact form they are working on, and where the styles are coming from.
- I removed all Bootstrap utility classes in `form.html`. The form container now only has: `form-field-container` (which has all of our app style _defaults_), and an optional `{{ form.classes }}` that is delcared from the Python form class per form.
- The convention here is …
> Fix: reCAPTCHA-related - Fix Admin form style regression

- .github/workflows/check-api.yml
Should not be merged until after https://github.com/cal-itp/littlepay/pull/72
But _needs_ to be merged after that PR for this check to continue to work.
> CI: update littlepay switch syntax

- benefits/urls.py
Closes #2618 
The reason why the images were not being served is because when DEBUG was false, there was no URL mapping from `/media` to the `django.views.static.serve` view.
If we simply move `urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))` outside of the `if settings.DEBUG` block, the URL mapping still is not added because the `static` helper function only works when [DEBUG is true](https://github.com/django/django/blob/main/django/conf/urls/static.py#L23-L25). So to get around this, we can just add the URL mapping ourselves.
This URL mapping does not affect the way media images are served by the `client` container because we configured NGINX to [handle the `/media` path](https://github.com/cal-itp/benefits/blob/main/appcontainer/nginx.conf#L75-L80).
> Fix: have Django serve media files even when DEBUG=False

- benefits/eligibility/templates/eligibility/start--sbmtd-agency-card.html
closes https://github.com/cal-itp/benefits/issues/2630
This PR fixes a small bug in `benefits/eligibility/templates/eligibility/start--sbmtd-agency-card.html` , where `block` should be `headline-text` instead of `headline` to render the title properly.
> Fix: use headline-text for block

- benefits/core/templates/core/base.html
- benefits/core/templates/core/includes/form.html
Part of #2493
This PR moves the loading of the reCAPTCHA script to only where it's actually used. This is a small change that belongs to the category of **Identify inline Javascript that doesn't need to be on every page**.
> Refactor: web perf - load recaptcha script only where it's needed

- benefits/core/templates/core/base.html
Part of #2493 
Goes with this recommendation:
and belongs to the category of **Load external Javascript in a non-blocking manner**.
We can use `async` to load Bootstrap JS because it doesn't need to be loaded before or after any other scripts. I tested the performance of `defer` vs. `async` with Lighthouse, and below are the results.
Also, side note: while reading about [Lightouse report variability](https://developer.chrome.com/docs/lighthouse/performance/performance-scoring/#fluctuations), I noticed this line about the [median of 5 runs](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md#run-lighthouse-multiple-times) being a more stable score, so I'm going to start using Median instead of Average. Here I've included Average and 90th percentile just because I had …
> Perf: load Bootstrap JS asynchronously

- benefits/static/css/styles.css
closes #2601 
Bootstrap has a class called `h4`, which has different sizing than what we want.
I could have done a few things:
- Rename the `h4` class in our styles
- Use this `disable-rfs` class that Bootstrap gives you
- Or add `important` to the existing `h4` size declaration
I decided to go with the latter, so that any future use of `h4` will be covered (and not require the dev to know to use `disable-rfs`). I didn't want to rename all the hX classes.
> Fix: Set important to override bootstrap h4

- docs/development/application-logic.md
Getting `Unsupported markdown: list` error in these charts
https://docs.calitp.org/benefits/development/application-logic
With this change
https://benefits-2645--cal-itp-previews.netlify.app/development/application-logic/
Related:
- https://github.com/mermaid-js/mermaid/issues/5824
- https://github.com/mermaid-js/mermaid/issues/6099
> Docs: update syntax for non-markdown numbering

- benefits/core/templates/core/base.html
- benefits/core/templates/core/includes/form.html
- benefits/core/templates/core/includes/ready-js.html
- benefits/eligibility/templates/eligibility/index.html
- benefits/enrollment/templates/enrollment/includes/jquery.html
- benefits/enrollment/templates/enrollment/index.html
- benefits/in_person/templates/in_person/enrollment/index.html
- benefits/templates/admin/agency-base.html
Part of #2493 
This PR makes it so we only use jQuery for enrollment. This allows us to stop loading jQuery on every page.
I originally set out to extract inline Javascript as separate files to be loaded in with `async` or `defer`. A lot of them would have to be `defer` since they depend on `jQuery` being loaded and available.
I tried it out and saw that the performance change was negligible. There was basically no difference.
It seemed then that a more impactful change would be to reduce the need for jQuery. A lot of what we were doing with jQuery can be done with plain Javascript that is well-supported by all modern browsers.
Using https://youmightnotneedjquery.com/ and https://tobiasahlin.com/blog/move-from-jquery-to-vanilla-javascript/#document-ready as reference and testing each …
> Refactor: reduce usage of jQuery

- benefits/core/templates/core/base.html
Closes #2492 
This PR audits and improves how the Google Web Font is loaded.
In [`base.html`](https://github.com/cal-itp/benefits/blob/933cd572b6b5731665f877b40da677ccad8c5ee1/benefits/core/templates/core/base.html#L21), the external font (Roboto) is loaded first, and the local font (Public Sans) is loaded after. Since there are no conflicts, Roboto takes precedence. Then, Roboto is set for [`--bs-font-sans-serif`](https://github.com/cal-itp/benefits/blob/933cd572b6b5731665f877b40da677ccad8c5ee1/benefits/static/css/variables.css#L14) so it is used throughout the site. The local font is only used for [login.gov buttons](https://github.com/cal-itp/benefits/blob/933cd572b6b5731665f877b40da677ccad8c5ee1/benefits/static/css/styles.css#L423).
> Perf: improve Google Web Font performance

- benefits/core/admin/__init__.py
- benefits/core/admin/enrollment.py
- benefits/core/admin/users.py
- tests/pytest/core/admin/test_users.py
Part of #2201
Following our [approach](https://github.com/cal-itp/benefits/pull/2638#issuecomment-2622595676) to breaking up [Refactor: Admin permissions for Cal-ITP Staff](https://github.com/cal-itp/benefits/pull/2638) into smaller PRs, this PR adds the `is_staff_or_superuser` helper function to check if user is staff or superuser and adds more tests for the helper functions in  `benefits/core/admin/users.py`.
> Feat: helper function checks if user is staff or superuser

- tests/pytest/core/admin/conftest.py
- tests/pytest/core/admin/test_users.py
This PR extracts out the `conftest.py` from #2654. This is so other PRs can be worked on to add and test the `add` permissions for `ClaimsProvider` and `TransitAgency` without having to wait for #2654.
Some guidance for the other PRs:
- Continue using `model_AdminUser`. We can look into switching to `admin_user` as a separate PR after these PRs that add the permissions.
- No need to add or test any `"regular"` user scenarios
> Test: introduce admin conftest to use for testing `add` permissions

- benefits/core/admin/transit.py
- tests/pytest/core/admin/test_transit.py
Closes #2665
This PR sets visible/nonvisible and editable/readonly permissions on the fields of `TransitAgency` and `TransitProcessor` models for `superuser` and `Cal-ITP` group members, and lets `Cal-ITP` group members add `TransitAgency` models.
Set `DJANGO_ALLOWED_HOSTS=benefits.calitp.org,localhost` in your `.env` file (and don't forget to `source .env` in the dev container's terminal) so that you can see the add `TransitProcessor` and `TransitAgency` model behavior as it would run on `prod`. Otherwise, you will always be able to add the `TransitProcessor` model because of
```python
def has_add_permission(self, request):
if settings.RUNTIME_ENVIRONMENT() != settings.RUNTIME_ENVS.PROD:
return True
```
Log in to the admin interface as a `superuser` and verify the checklist for …
> Feat: field/add permissions for Transit models

- .devcontainer/devcontainer.json
Closes #2642
This PR changes the behavior of the dev container to only auto forward the ports associated with the `docs` and `server` services in the compose file. By setting `"otherPortsAttributes": { "onAutoForward": "ignore" }`, [any other ports should not be auto-forwarded at all](https://containers.dev/implementors/json_reference/#port-attributes).
1. Exit your current dev container
2. Switch to this branch
3. Rebuild and reopen the dev container
4. Start the debugger
5. Verify that the app is always reachable from your browser at `localhost:DJANGO_LOCAL_PORT/` (open the benefits app, submit the eligibility form, navigate to the admin, etc.) and that the `PORTS` tab in VS Code always only shows 2 ports, the `server` and `docs` ports
> Fix: port forwarding in VS Code

- benefits/core/migrations/local_fixtures.json
Closes #2675
This PR adds to the database a `calitp-user` to make local testing and QA a little simpler without having to manually set up user accounts.
Reset your database using the new fixture file in this PR, log in to the admin area, confirm that you can use the `calitp-user` credentials that are stored in the shared LastPass area, and that the permissions match the `Cal-ITP` staff group.
> Chore: add fixture for Cal-ITP Staff account

- benefits/core/admin/claims.py
- tests/pytest/core/admin/test_claims.py
Closes #2663
This PR sets visible/nonvisible and editable/readonly permissions on the fields of `ClaimsProvider` for `superuser` and `Cal-ITP` group members, and lets `Cal-ITP` group members add instances of the `ClaimsProvider` model.
Set `DJANGO_ALLOWED_HOSTS=benefits.calitp.org,localhost` in your `.env` file (and don't forget to `source .env` in the dev container's terminal) so that you can see the add `ClaimsProvider` model behavior as it would run on `prod`. Otherwise, you will always be able to add the `ClaimsProvider` model because of
```python
def has_add_permission(self, request):
if settings.RUNTIME_ENVIRONMENT() != settings.RUNTIME_ENVS.PROD:
return True
```
Log in to the admin interface as a `superuser` and verify the checklist for `superuser` shown below. 
Log in to the admin …
> Feat: field/add permissions for ClaimsProvider model

- benefits/core/admin/enrollment.py
- benefits/core/models/enrollment.py
- benefits/core/models/transit.py
- tests/pytest/core/admin/test_enrollment.py
- tests/pytest/core/models/test_enrollment.py
- tests/pytest/core/models/test_transit.py
- tests/pytest/eligibility/test_views.py
Part of #2201
Closes #2664 
Allows Cal-ITP staff members to add new `EnrollmentFlow` objects.
Login into Benefits Admin as `calitp-user` from our LastPass shared credentials.
- Cal-ITP staff member can add a new `EnrollmentFlow`:
- Cal-ITP staff member should not be able to add incomplete `EnrollmentFlow` to a transit agency
- ~~[ ] incomplete - some but not all fields for API verification have been filled out~~ - not possible for staff member to do by themselves
>  Cal-ITP staff member should not be able to add incomplete `EnrollmentFlow` to a transit agency
<details><summary>Incomplete - none of the fields for claims or API verification have been filled out</summary>
</details>
<details><summary>Incomplete - some but not all fields for expiration have been filled out</summary> …
> Feat: Cal-ITP staff can add EnrollmentFlow

- benefits/core/admin/common.py
- tests/pytest/core/admin/test_common.py
Closes #2666
This PR sets visible/nonvisible and editable/readonly permissions on the fields of `PemData` for `superuser` and `Cal-ITP` group members, and does not allow `Cal-ITP` group members to add instances of the `PemData` model.
Log in to the admin interface as a `superuser` and verify the checklist for `superuser` shown below. 
Log in to the admin interface as a `Cal-ITP` group member (the easiest way to set up a `Cal-ITP` group member is to remove the `superuser` attribute from the `benefits-admin` user and to add it to the `Cal-ITP` group) and verify the checklist for `Cal-ITP` group member shown below.
For the verification, ensure model and field permissions match the permissions in the [Benefits admin configuration](https://docs.google.com/spreadsheets/d/1lPp_LJTfJoWCyOkRC4RaljA …
> Feat: field/add permissions for PemData model

- benefits/core/admin/enrollment.py
- tests/pytest/core/admin/test_enrollment.py
Closes #2683 
This PR cleans up `EnrollmentEventAdmin` so that it no longer specifies `id` as a read-only field. Per the [docs](https://docs.djangoproject.com/en/5.1/ref/models/fields/#primary-key), the `id` field is already read-only since it's a primary key. The cleanup originally occurred in https://github.com/cal-itp/benefits/commit/6540f51370bb599d438484b3b689de713b586991.
> Chore: unnecessary read-only field in EnrollmentEventAdmin

- benefits/static/css/styles.css
- benefits/static/css/variables.css
We're not sure what changed to cause the prettier pre-commit hook to fail on `styles.css` and `variables.css`. It keeps getting re-run on our PRs like #2691 and #2689 and [even on merges into `main`](https://results.pre-commit.ci/run/github/285501392/1739894951.TJKhBB2dS7e70pbofhCPNA), so let's just apply the re-formatting so it stops re-running.
Ran `pre-commit run --all-files`:
> Chore: run pre-commit on all files

- benefits/urls.py
I needed this change while testing #2694.
In [746f322](https://github.com/cal-itp/benefits/commit/746f32246847aeacad52490a1183344788b5a753#diff-0a52f0f149d58e26a1c8fc3a6c333e6557c065bad6b9259e48c8531ee4728b54R53), we introduced an `error/` route to core's URLconf. We overlooked that in the root URLconf, there already was an `error/` route if `DEBUG=True`, which is for the purpose of testing Sentry.
That change was in May 2024, so I'm not sure how we've been able to test Sentry updates since then. For example, in [November 2024](https://github.com/cal-itp/benefits/pull/2532#pullrequestreview-2459325168), I was somehow able to hit the root `error/` and trigger the `RuntimeError("Test error")`.
Today, what I saw was that when I go to `error/`, I hit the core `error/` and see the Error page. …
> Fix: rename test route to `testerror/`

- tests/pytest/core/context/test_agency.py
This will protect us from forgetting to add Agency Index copy.
Other PRs (like #2705) can add their own tests.
> Test: ensure core_context.agency_index contains all AgencySlugs

- benefits/eligibility/verify.py
- benefits/eligibility/views.py
- tests/pytest/eligibility/test_verify.py
While working on https://github.com/cal-itp/benefits/pull/2700, I noticed that we were not using this parameter anymore. This PR makes this small cleanup.
> Chore: remove unused parameter in eligibility_from_oauth

- benefits/core/session.py
- benefits/oauth/redirects.py
- benefits/oauth/views.py
- tests/pytest/conftest.py
- tests/pytest/core/test_middleware_login_required.py
- tests/pytest/core/test_session.py
- tests/pytest/eligibility/test_views.py
- tests/pytest/oauth/test_redirects.py
- tests/pytest/oauth/test_views.py
Part of #2678
Due to sign out changes in the IdG, in this PR we're replacing `id_token_hint` with `client_id` in the `deauthorize_redirect` helper that is used as part of the sign out process.
**~We can review this PR but we should hold off from merging it to `main` since this functionality has been deployed to IdG `dev`, but~ we should coordinate with the IdG team before deploying this to the `test` and `prod` environments.**
Using this branch, set up a login.gov flow, such as Older Adult, and go through the flow until eligibility is confirmed
Click on `Sign out of Login.gov` and confirm that you can successfully sign out
Compare this behavior with [`dev`](https://dev-benefits.calitp.org/) (or `main`, where this fix has not been deployed yet) and notice these extra pages provided by the …
> Refactor: IdG sign out to use client_id

- benefits/settings.py
- pyproject.toml
Closes #2734
This PR installs [django-cdt-identity](https://github.com/Office-of-Digital-Services/django-cdt-identity) using the package's Git URL (`main` branch) while we get it published to PyPI.
- If you have a running dev container:
- Switch to this branch
- Run `pip install -e .` in your dev container's terminal
- Run `pip freeze` to verify that `django-cdt-identity` is in the list of installed packages. The git URL will display the SHA of the latest commit in [`main`](https://github.com/Office-of-Digital-Services/django-cdt-identity)
- Run `bin/init.sh` to apply one migration associated with `cdt_identity`
- Start a debug session and in the `DEBUG CONSOLE` type `from cdt_identity.hooks import DefaultHooks` to verify that you can import from the `cdt_identity` app.
- If you are …
> Refactor: install cdt_identity app

- docs/configuration/transit-agency.md
Forgot to remove these in #2674 and #2705.
> Docs: remove reference to `index_template` and `eligibility_index_template`

- benefits/admin.py
closes #2740 
We do not want the sidebar to show up across the Django admin app.
This is what the sidebar looks like and how it functions, when open and closed on the Reset Password page:
This PR sets the `enable_nav_sidebar` setting to False, so that it does not appear at all:
> Admin: Disable sidebar

- benefits/oauth/hooks.py
- tests/pytest/oauth/test_hooks.py
Part of #2723 
This PR implements the hook methods that are called in the `django-cdt-identity` [`login`](https://github.com/Office-of-Digital-Services/django-cdt-identity/blob/main/cdt_identity/views.py#L117) view.
Here are the lines in the existing Benefits `login` view that correspond with each hook:
- https://github.com/cal-itp/benefits/blob/af0ec2cb2980978820856149cb374cb8b6e1af1f/benefits/oauth/views.py#L66 --> [`pre_login`](https://github.com/Office-of-Digital-Services/django-cdt-identity/blob/main/cdt_identity/views.py#L130) hook 
- https://github.com/cal-itp/benefits/blob/af0ec2cb2980978820856149cb374cb8b6e1af1f/benefits/oauth/views.py#L81-L83 --> [`system_error`](https://github.com/Office-of-Digital-Services/django-cdt-identity/blob/main/cdt_identity/views.py#L151) hook
- none …
> Feat: OAuth hooks for `login` view

- benefits/oauth/hooks.py
- tests/pytest/oauth/test_hooks.py
Part of #2723 
This PR implements the `cancel_login` hook method that is called in the django-cdt-identity [`cancel`](https://github.com/Office-of-Digital-Services/django-cdt-identity/blob/main/cdt_identity/views.py#L110) view.
- [`cancel_login`](https://github.com/Office-of-Digital-Services/django-cdt-identity/blob/main/cdt_identity/views.py#L114): https://github.com/cal-itp/benefits/blob/270492d228c0541e8952fe7719d971e61ad560c1/benefits/oauth/views.py#L157-L159
> Feat: OAuth hooks for `cancel` view

- benefits/oauth/hooks.py
- tests/pytest/oauth/test_hooks.py
Part of #2723 
This PR implements the hooks for the `logout` view.
- [`pre_logout`](https://github.com/Office-of-Digital-Services/django-cdt-identity/blob/main/cdt_identity/views.py#L171) - https://github.com/cal-itp/benefits/blob/270492d228c0541e8952fe7719d971e61ad560c1/benefits/oauth/views.py#L177-L180
- [`system_error`](https://github.com/Office-of-Digital-Services/django-cdt-identity/blob/main/cdt_identity/views.py#L187) - already handled by #2757
> Feat: OAuth hooks for `logout` view

- benefits/oauth/hooks.py
- tests/pytest/oauth/test_hooks.py
Part of #2723 
Built on top of #2769 
This PR implements the hooks for the `post_logout` view.
- [`post_logout`](https://github.com/Office-of-Digital-Services/django-cdt-identity/blob/main/cdt_identity/views.py#L201) - https://github.com/cal-itp/benefits/blob/270492d228c0541e8952fe7719d971e61ad560c1/benefits/oauth/views.py#L196-L199
> Feat: OAuth hooks for `post_logout` view

- benefits/core/admin/enrollment.py
- tests/pytest/core/admin/test_enrollment.py
@lalver1 pointed out that `test_EnrollmentFlowForm_clean_supports_expiration` started failing due to some model refactoring in #2721 and that it was not clear why the test still fails even after making the expected changes to reflect the refactor.
It turns out the test itself had a mistake, namely that the field for the eligibility claim was not correct. 
Correcting that revealed another bug which is that if you had both field-errors and non-field errors during form validation, you would lose the non-field errors.
Lastly, we also noticed that trying to re-use the same test for both `super` and `staff` parameters didn't actually make sense because `staff` users cannot actually POST some fields, like `reenrollment_error_template`. To address this, we decided to split the test out.
These …
> Fix: `EnrollmentFlowForm` test and validation

- benefits/eligibility/verify.py
- benefits/eligibility/views.py
- benefits/oauth/hooks.py
- tests/pytest/eligibility/test_verify.py
- tests/pytest/eligibility/test_views.py
- tests/pytest/oauth/test_hooks.py
Part of #2723 
This PR implements the hook methods that are called in the `django-cdt-identity` [`authorize`](https://github.com/Office-of-Digital-Services/django-cdt-identity/blob/main/cdt_identity/views.py#L53) view.
These are the hooks and the corresponding Benefits code:
- [`pre_authorize`](https://github.com/Office-of-Digital-Services/django-cdt-identity/blob/main/cdt_identity/views.py#L67): none
- [`system_error`](https://github.com/Office-of-Digital-Services/django-cdt-identity/blob/main/cdt_identity/views.py#L83): https://github.com/cal-itp/benefits/blob/270492d228c0541e8952fe7719d971e61ad560c1/benefits/oauth/views.py#L116-L118 (already done by #2757 with [the last two commits](https://github.com/cal-itp/benefits/pull/2757/files/b320e98a699f4ce20f001c5827456eb2d5e4a221..72705baa4bb …
> Feat: OAuth hooks for `authorize` view

- .vscode/launch.json
With this option set on the debugger's launch configuration we can set breakpoints in external modules and debug them.
> Chore: enable debugging of external python modules

- benefits/core/session.py
- tests/pytest/core/test_session.py
Part of #2722 
This PR adds the session flow's `oauth_config` and `claims_request` to the session as well.
> Feat(session): set config for cdt_identity when setting flow

- benefits/oauth/urls.py
- benefits/oauth/views.py
- tests/pytest/oauth/test_views.py
Part of #2788 
Replaces Benefits oauth `post_logout` with cdt_identity `post_logout` view.
Run through a Login.gov flow, and click on any links for logging out. You should see that the `post_logout` hook is called.
Choose a non-Login.gov flow (e.g. Agency Card), and then attempt to go to `oauth/post_logout`. The `FlowUsesClaimsVerificationSessionRequired` middleware should get called and end up showing you the user error screen.
> Refactor: use cdt_identity `post_logout` view

- benefits/settings.py
- benefits/static/css/admin/theme.css
- benefits/templates/admin/base.html
closes #2741 
Currently, you might notice that when screensharing the Admin app with someone on a different operating system, the app looks different than yours. That's because the font is set to a user's system font. This can be confusing and delivers a disjointed experience for transit agency operators who may be using this app across various hardware (iPads, tablets, desktops) and browsers.
Originally, I had thought that it would be complicated to add Noto as a font for all the different parts of Admin - so I wanted to hold off on it. But now that all of Admin is on Bootstrap (#2766), I realized that we can easily make all of Admin use 1 font, with just changing one thing - Bootstrap's `--bs-font-family` variable in the `theme.css` file. I imported the 400, 500 and 700 font weights, …
> Admin: Add Noto font

- benefits/static/css/admin/styles.css
- benefits/static/css/admin/theme.css
- benefits/templates/admin/agency-dashboard-index.html
- benefits/templates/admin/login.html
closes #2790 
This PR ended up getting a little bigger than the original issue. The theme of this PR is "small visual fixes" on these 2 pages that are now most prominent to current Agency users. This PR does _not_ touch any of the "flow" pages.
- Test this PR with reCAPTCHA turned _on_ to get the reCAPTCHA warning text
- CTA Button for Log In/Log Out and Sign in with Google: Border radius, font size, icon size and resulting total button height now match Figma - 3rem (48px) height buttons with 1rem (16px) font size text, centered with border-radius 2px.
- Make the external link icon 1rem, to match the font size
- CTA Button: Border radius, font size, and resulting total button height now match Figma
- Spacing above the transit agency name now matches Figma
- Spacing above the button now …
> Admin: Fixes to Log In/Out and Agency Dashboard page

- benefits/oauth/urls.py
- benefits/oauth/views.py
- tests/pytest/oauth/test_views.py
Closes #2788 
~Builds on #2791~
Replaces Benefits oauth `cancel` with cdt_identity `cancel` view.
~Run through a Login.gov flow, and on the Login.gov login screen, click the link that says `‹ Back to Dev Cal-ITP Benefits`. You should see that the `cancel_login` hook is called.~
We can't test this hook locally because the dev IdG redirects to `dev-benefits.calitp.org` when that `‹ Back to Dev Cal-ITP Benefits` link is clicked.
Choose a non-Login.gov flow (e.g. Agency Card), and then attempt to go to `oauth/cancel`. The `FlowUsesClaimsVerificationSessionRequired` middleware should get called and end up showing you the user error screen.
> Refactor: use cdt_identity `cancel` view

- benefits/oauth/urls.py
- benefits/oauth/views.py
- benefits/urls.py
- tests/pytest/oauth/test_views.py
Closes #2786 
As part of the oauth refactor, this PR replaces `benefits.oauth.views.login` with `cdt_identity.views.login`.
Run through a login.gov flow and ensure you can confirm your eligibility. Also notice that when you click on the `Get started with LOGIN.GOV` CTA button, the `cdt_identity` `login` view is called.  In addition, a `started sign in` analytics event will be created as part of the `pre_login` hook.
> Refactor: use cdt_identity `login` view

- benefits/oauth/urls.py
- benefits/oauth/views.py
- tests/pytest/oauth/test_hooks.py
- tests/pytest/oauth/test_views.py
Closes #2787
As part of the oauth refactor, this PR replaces `benefits.oauth.views.logout` with `cdt_identity.views.logout`.
Run through a login.gov flow and ensure you can confirm your eligibility. On the eligibility confirmation page, click on `Sign out of Login.gov ` and check that the `cdt_identity` `logout` view is called.  In addition, a `started sign out` analytics event will be created as part of the `pre_logout` hook; and a `finished sign out` analytics event will be created as part of the `post_logout` hook.
> Refactor: use cdt_identity `logout` view

- benefits/oauth/urls.py
- benefits/routes.py
- benefits/urls.py
Closes #2813 
~Builds off #2819~
In https://github.com/cal-itp/benefits/pull/2793, we uncovered a need for the `oauth/authorize` route to have a namespace of `cdt`. See https://github.com/cal-itp/benefits/pull/2793#discussion_r2023782407 for more details. The temporary solution was to add a duplicate URL pattern that pointed to `cdt_identity.urls`.
@thekaveman, @lalver1, and I took a closer look at this today and figured out a cleaner solution, which is to make the URL patterns in `benefits.oauth.urls` have a namespace of `cdt`. Then there is no need for the duplicate.
We also cleaned up duplication in `benefits.oauth.urls` by extracting repeated values into variables.
> Refactor: OAuth URLconf

- benefits/core/admin/enrollment.py
Closes #2809
There is now a default descending sort on the date when viewing enrollments in the admin.
We do this by setting [`ModelAdmin.ordering`](https://docs.djangoproject.com/en/5.1/ref/contrib/admin/#django.contrib.admin.ModelAdmin.ordering) on `EnrollmentEventAdmin`.
> To indicate descending order with the `ordering` argument you can use a hyphen prefix on the field name.
_from https://docs.djangoproject.com/en/5.1/ref/contrib/admin/_
> Feat: default descending sort on date for enrollments list

- benefits/core/templates/core/index--agency.html
- benefits/eligibility/templates/eligibility/index.html
- benefits/eligibility/templates/eligibility/start.html
Closes #2760 
Removes unneeded `translate`s from Agency Index and Eligibility Start.
The [ones on Eligibility Index](https://github.com/cal-itp/benefits/pull/2824/commits/b246fb8d178c99f29954da8c9bd8e6a3a739e1fe#diff-1e3c02710205416114dcc25094079f5cdd0a6d71b504924fe9c6d0d215612ef1L24-L26) are needed because, for some reason, removing it causes translation to break (i.e. switching to Spanish does not show Spanish copy. The English copy sticks around.) Seems like something to do with the `%` character.
> Refactor: remove unnecessary usage of `translate`

- pyproject.toml
dependabot upgraded [Pillow](https://github.com/python-pillow/Pillow) to [11.2.0](https://github.com/cal-itp/benefits/pull/2807) but upon further inspection, pillow 11.2.0 was never released in the [GitHub repo](https://github.com/python-pillow/Pillow/releases) nor in [PyPI](https://pypi.org/project/pillow/#history). This caused the `client` image build to fail locally as well as in our [CI](https://github.com/cal-itp/benefits/actions/runs/14437112114/job/40480010017). This version upgrade fixes this issue by upgrading to version [11.2.1](https://pypi.org/project/pillow/) which was published in PyPI.
> Chore: update pillow to 11.2.1

- benefits/core/session.py
- tests/pytest/core/test_session.py
This PR brings back a check to avoid trying to access `eligibility_claim` on a flow that does not use claims verification. Without this fix, an exception would be raised when trying to access `eligibility_claim` on an agency card flow, for example:
The exception would occur on [line 74 of enrollment index ](https://github.com/cal-itp/benefits/blob/main/benefits/enrollment/views.py#L74)when `extra_claims` would be requested from the `session`.
Run through an agency card and a login.gov flow (all the way to the end) and ensure that you can successfully enroll.
> Fix: check if flow uses claims verification

- benefits/core/mixins.py
- tests/pytest/core/test_mixins.py
Closes #2873 
Modeled after existing middleware class [`AgencySessionRequired`](https://github.com/cal-itp/benefits/blob/main/benefits/core/middleware.py#L29), and will eventually replace this entirely once all dependent views are refactored to CBV.
> Feat: CBV mixin enforces agency in session

- benefits/core/mixins.py
- tests/pytest/core/test_mixins.py
Closes #2874 
Modeled after existing middleware class [`FlowSessionRequired`](https://github.com/cal-itp/benefits/blob/main/benefits/core/middleware.py#L85), and will eventually replace this entirely once all dependent views are refactored to CBV.
> Feat: CBV mixin enforces flow in session

- benefits/core/mixins.py
- tests/pytest/core/test_mixins.py
Closes #2875
Modeled after existing middleware class [`RecaptchaEnabled`](https://github.com/cal-itp/benefits/blob/main/benefits/core/middleware.py#L127) and will eventually replace this entirely once all dependent views are refactored to CBV.
> Feat: CBV mixin sets required reCAPTCHA settings

- benefits/in_person/templates/in_person/enrollment/success.html
fixes #2867 
This PR fixes the button issue by using the same set of classes the button on the Admin dashboard does (btn btn-lg text-white btn-primary d-block). Eventually, when the Benefits design language is ready to be implemented, this should be improved so we don't need a long string of buttons to make the standard button.
> Fix: Admin - Fix secondary button text color

- benefits/enrollment/urls.py
- benefits/enrollment/views.py
- benefits/enrollment_littlepay/templates/enrollment_littlepay/index.html
- benefits/enrollment_littlepay/urls.py
- benefits/enrollment_littlepay/views.py
- benefits/routes.py
- benefits/urls.py
- tests/pytest/enrollment/test_views.py
- tests/pytest/enrollment_littlepay/test_views.py
Part of #2907 
This PR moves the entire `token` view from `benefits.enrollment.views` into `benefits.enrollment_littlepay.views`. It also refactors the view into a class-based view.
The URL for the view was moved under `enrollment_littlepay` with a namespace of `littlepay` so that the URL is something like `<base URL>/littlepay/token`. The route was updated as well so that all consumers of the route use the new URL.
Enrollment with Littlepay should still work.
> Refactor: add enrollment_littlepay token view

- benefits/enrollment_littlepay/templates/enrollment_littlepay/index.html
- benefits/enrollment_littlepay/views.py
- benefits/settings.py
- terraform/app_service.tf
- tests/pytest/enrollment_littlepay/test_views.py
Closes #2901 
Closes #2942 
I wasn't able to see a difference in the Littlepay tokenization overlay with the flag set to `True` -- but I can confirm that the correct list of `cardTypes` is passed as an `option` to the function call:
Easiest way to test is just set `LITTLEPAY_ADDITIONAL_CARDTYPES = True` in your local settings file (e.g. on the very last line in the file).
```python
LITTLEPAY_ADDITIONAL_CARDTYPES = os.environ.get("LITTLEPAY_ADDITIONAL_CARDTYPES", "False").lower() == "true"
LITTLEPAY_ADDITIONAL_CARDTYPES = True  # <-- quick and dirty override
```
> Feat: additional Littlepay card types

- benefits/enrollment_switchio/api.py
- tests/pytest/enrollment_switchio/test_api.py
Closes #2903
This PR introduces a `Client` class that encapsulates interaction with the Switchio registration API. This API is responsible for managing the back-end state of a card tokenization session. The two API endpoints allow you to
- establish a session and get back an ID and corresponding URL (`Client.request_registration`)
- get the status of a session, by ID (`Client.get_registration_status`)
Note about their naming: "registration" here is not "enrollment". If it helps at all, think of "registration" here as "card tokenization" or a "card tokenization session".
> Feat: Switchio API module

- docs/configuration/environment-variables.md
Closes #2956 
During the deployment process, @angela-tran and I noticed that I did not write docs on this env var, or how to configure it. And we reflected that it's good to have some sort of place to do this, at least so the person deploying remembers to configure it. So we created this ticket to remedy this. Even though this is a fairly simple variable, that we will only need for a short temporary period, I thought it would be good to be thorough and document it. 
Note: These docs should be also removed when the environment variable and the feature flagged copy is removed.
> Docs on littlepay-additional-cardtypes variable

- benefits/enrollment_littlepay/enrollment.py
- benefits/enrollment_littlepay/views.py
- benefits/in_person/templates/in_person/enrollment/index.html
- benefits/in_person/views.py
- tests/pytest/enrollment_littlepay/test_enrollment.py
- tests/pytest/enrollment_littlepay/test_views.py
- tests/pytest/in_person/test_views.py
Closes #2963.
It turns out the In-person flow does not mention card types in the user-facing copy, so this was a simple change to the overlay window `options`.
Similar to #2943, the easiest way to test is just set `LITTLEPAY_ADDITIONAL_CARDTYPES = True` in your local settings file (e.g. on the very last line in the file).
```python
LITTLEPAY_ADDITIONAL_CARDTYPES = os.environ.get("LITTLEPAY_ADDITIONAL_CARDTYPES", "False").lower() == "true"
LITTLEPAY_ADDITIONAL_CARDTYPES = True  # <-- quick and dirty override
```
Then launch the app, login to the Admin as `cst-user`, and go to the enrollment step. It should support the existing Visa/MC, and Discover/Amex as well:
| Existing card types | New card types |
| --------------------------- | -----------------------| 
| …
> Feat: support additional card types for Littlepay in-person enrollment

- benefits/enrollment/analytics.py
- benefits/enrollment_littlepay/views.py
- benefits/enrollment_switchio/enrollment.py
- benefits/enrollment_switchio/views.py
- benefits/in_person/views.py
- tests/pytest/enrollment/test_analytics.py
- tests/pytest/enrollment_littlepay/test_views.py
- tests/pytest/enrollment_switchio/test_enrollment.py
- tests/pytest/enrollment_switchio/test_views.py
- tests/pytest/in_person/test_views.py
Part of #2904 
Builds off #2952 
This PR adds error-handling for the Switchio `/gateway_url` view, similar to what we added for Littlepay in https://github.com/cal-itp/benefits/issues/2032. That is:
- 500 errors from Switchio should take the user to the "system error" page
- 400 errors from Switchio should take the user to the "server error" page (because it's most likely a problem on our end)
- non-HTTP errors occurring from calling Switchio should take the user to the "server error" page
Code changes that were done:
- extracts usage of `benefits.enrollment_switchio.api` to an intermediary module - `benefits.enrollment_switchio.enrollment` - which is responsible for providing additional data about the response like exceptions, status_codes, etc.
- refactors `GatewayUrlView` to use this …
> Feat: error-handling for GatewayUrlView

- benefits/eligibility/urls.py
- benefits/eligibility/views.py
- tests/pytest/eligibility/test_views.py
Closes #2872 
- Run through an agency card and non-agency card flow
- Fail eligibility verification
- Confirm you still see the same `eligibility:unverified` view for each flow type
> Refactor: class-based view for Eligibility Unverified

- benefits/eligibility/views.py
- benefits/oauth/hooks.py
- tests/pytest/conftest.py
- tests/pytest/eligibility/test_views.py
- tests/pytest/oauth/test_hooks.py
Closes #2871 
- Run through an agency card and non-agency card flow
- Pass eligibility verification
- Confirm you still see the same `enrollment:index` view for each flow type
> Refactor: class-based view for Eligibility Verified

- docs/enrollment-pathways/README.md
Project board URL now points to the Compiler Unified Sprint Board rather than the now-closed Digital Services project.
> Docs: update URL for project board

- benefits/oauth/hooks.py
- tests/pytest/oauth/test_hooks.py
Follow up to #3009.
The `VerifiedView` only runs e.g. session and analytics logic for POST requests. 
GET requests represent having a previously verified session (where we don't need to e.g. send another analytics event).
But the request coming back from the OAuth flow is a GET, so this PR temporarily overrides its method to POST in the hook that calls `VerifiedView`.
> Fix: override request method for OAuth verified logic

- docs/styles/theme.css
closes #2899 
- Run the docs locally
- Test the docs in mobile mode
- Click on the nav
- Click the back arrow
- All the Benefits family of repos' docs themes will be updated
> Docs - Fix: Update mobile sidebar color to match theme

- benefits/core/urls.py
Closes #3055
See the issue above for context. 
This PR removes the upper limit for what values can go through the `TransitAgencyPathConverter`. Increasing the limit just sets us up to run into it again in the future when / if we have an agency with a longer slug.
> Fix: allow `ventura` slug to go through `TransitAgencyPathConverter`

- terraform/storage.tf
Closes #3059 
Adds `allow_nested_items_to_be_public = false` to storage account definition.
> Fix: remove anonymous blob access to storage account

- .devcontainer/Dockerfile
- .dockerignore
- .github/workflows/deploy.yml
- appcontainer/Dockerfile
- pyproject.toml
Uses [Buildkit cache mounts](https://docs.docker.com/build/cache/optimize/#use-cache-mounts) to avoid re-downloading `apt` and `pip` dependencies that haven't changed between builds of both the app container and devcontainer. Some Docker commands were also rearranged to improve [Docker's layer caching](https://docs.docker.com/build/cache/optimize/#order-your-layers).
These changes result in a significant speed-up of image build times, both locally and in the CI/CD pipeline.
https://github.com/cal-itp/docker-python-web/pull/56 has to be merged first.
This will start your local environment from a clean slate, to ensure caching is working as expected (also, removes a bunch of Docker build assets you may or may not want hanging around!)
Run this in any directory on your local machine: …
> Feat: Buildkit caching for Docker builds

- benefits/enrollment/urls.py
- benefits/enrollment/views.py
- tests/pytest/enrollment/test_views.py
Closes #3015
This PR converts the enrollment index view function into a `RedirectView` class-based view.
> Refactor: Class-based views - Enrollment Index

- benefits/core/models/transit.py
- benefits/enrollment/views.py
- benefits/in_person/urls.py
- benefits/in_person/views.py
- benefits/routes.py
- tests/pytest/core/models/test_transit.py
- tests/pytest/enrollment/test_views.py
- tests/pytest/in_person/test_views.py
Closes #3075
This PR defines a base Enrollment view for in-person. The new base view inherits from `IndexView` on the Digital side and redirects to the appropriate in-person enrollment view based on the transit agency.
- The in_person `urls.py` file has placeholders for `enrollment/littlepay` and `"enrollment/switchio` but both are associated with the current `enrollment` (Littlepay) view so that the app continues to work during this in-person refactor.
- ~The refactor in be4445ae1512eabadbe8970a7cb76e563a8df996 tried to make the least amount of changes to `TransitAgency` yet still introduce a way for it to support in-person too. We could replace this with a more significant refactor (such as changing `enrollment_index_route` from a property to a function and passing in the enrollment …
> Feat: base Enrollment view for in-person

- benefits/enrollment/enrollment.py
- benefits/enrollment_switchio/enrollment.py
- benefits/enrollment_switchio/templates/enrollment_switchio/index.html
- benefits/enrollment_switchio/templates/enrollment_switchio/script.html
- benefits/enrollment_switchio/views.py
- benefits/in_person/templates/in_person/enrollment/index_switchio.html
- benefits/in_person/urls.py
- benefits/in_person/views.py
- benefits/routes.py
- tests/pytest/enrollment/test_enrollment.py
- tests/pytest/enrollment_switchio/test_enrollment.py
- tests/pytest/enrollment_switchio/test_views.py
- tests/pytest/in_person/test_views.py
Closes #3068 
Closes #3069 
1. Ensure you are setup locally for Switchio INT/ACC environment
1. Start the app with `F5`
1. In the browser, enter the URL `/admin`
1. Log in with `cst-user`
1. Start a new in-person enrollment (choose any flow)
1. See a quick loading message, then click `Enroll`
1. Redirect into Switchio's tokenization flow, enter card details
1. Redirect back to Admin In-Person, see a quick loading message
1. See the success message with buttons to start a `New enrollment` or be `Done`
1. Confirm Switchio enrollment on Digital side works as normal
> Feat: Support in-person for Switchio

- benefits/enrollment_switchio/templates/enrollment_switchio/script.html
- benefits/in_person/templates/in_person/enrollment/index_switchio.html
- benefits/in_person/templates/in_person/enrollment/switchio_script.html
- benefits/in_person/views.py
- tests/pytest/in_person/test_views.py
Closes #3089 
- Pre-tokenization loading message matches that in Figma
- Immediate redirect into Switchio gateway
- Post-tokenization loading message matches that in Figma
- Fixed handling of the Switchio gateway "Back" button, similar to Littlepay "Cancel" button
- _This does not yet update the loading icon from the spinner to the bar -- this will be a little more complex_
1. Checkout this branch, make sure you are setup for Switchio enrollment with CST
2. `F5` to launch the app
3. Login to the `/admin` as `cst-user`
5. Start a new enrollment, choose any flow
6. Note the initial loading message `Connecting with payment processor...`
7. Note the auto-redirection into tokenization gateway
8. Enter sample card details and submit
9. Upon redirection back to In-person, note the second loading …
> Fix: Switchio in-person UX

- benefits/settings.py
Similar to the session cookie, we need to have the language cookie's `SameSite` flag set to `Lax` so that the cookie stays with the user during redirects e.g. for IdG/Login.gov and Switchio.
Otherwise, the user gets the app's default language (`en`) upon redirection back, even if they originally left the app with a different language selection (e.g. `es`).
Fixes #3081 
See more: https://docs.djangoproject.com/en/5.2/ref/settings/#language-cookie-samesite
1. Checkout this branch, start the app with `F5`
2. Click the `Español` button to change to `es`
3. Use the browser dev tools to confirm a cookie was set with name `django_language`, value `es`, and `SameSite = Lax`
4. Select a flow that takes you through Login.gov, e.g. Older Adult
5. Complete identity proofing with Login.gov
6. Confirm …
> Fix: allow language cookie to travel with user

- .pre-commit-config.yaml
- benefits/static/css/admin/styles.css
- benefits/static/css/admin/theme.css
- benefits/static/css/styles.css
- benefits/static/css/variables.css
resolves #3227
the crux of the issue is that we don't want pre-commit to run prettier@4x if [`esbenp.prettier-vscode`](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) is running 2x
i'm planning on rebasing this PR prior to merge to get rid of the redundant commit, but i thought it would be helpful initially to have evidence that pre-commit is finally applying the same formatting changes to files that y'all are (hopefully) seeing in VS Code locally.
> chore: use prettier@2.x in pre-commit
