cal-itp/benefits

eligibility_verification/core/viewmodels.py, eligibility_verification/core/views.py, eligibility_verification/eligibility/views.py
Fallback to all active agencies
=> Present contact info for configured agency

LICENSE
Since this service is delivered over the web
=> Use AGPLv3

benefits/core/templates/core/payment-options.html, benefits/discounts/templates/discounts/success.html, benefits/discounts/views.py, benefits/locale/en/LC_MESSAGES/django.po, benefits/locale/es/LC_MESSAGES/django.po
**All content** is now in the PO files!
Nearly all Spanish translations are finished. Heads up @calexity, I'll add review comments where we still have outstanding translations.
=> Language updates

.github/workflows/deploy-ecs.yml
Need to merge this into `main` to be able to trigger this workflow manually.
=> Allow manual triggers using workflow_dispatch

README.md
This option was recently removed in favor of S3 in #21
=> Remove outdated configuration doc

benefits/core/templates/core/help.html, benefits/core/views.py, benefits/locale/en/LC_MESSAGES/django.po, benefits/locale/es/LC_MESSAGES/django.po
=> Link to source code

benefits/core/migrations/0001_initial.py, benefits/core/models.py, benefits/discounts/api.py, data/client.json
* updates to the API endpoint and payload format
* be a little more cautious with the "500 response indicates customer exists in group" strangeness
=> Group API fixes

benefits/discounts/api.py, benefits/discounts/views.py
`GET` customer creates the record if needed!
Yes, a `GET` with side-effects! :shrug:
=> Remove explicit create from Customer API

.vscode/settings.json, benefits/core/migrations/0001_initial.py, benefits/core/models.py
* configure VSCode to use the Pylance language server by default (new improved over Jedi etc.)
* black/flake8 ignores for models/migrations, preventing Django from thinking we need to makemigrations
=> Formatting cleanups

benefits/locale/en/LC_MESSAGES/django.po
- Updated alt text for the new image
- Removed prepaid card language from everywhere except Payment Options page
=> Updated a few of the English language pieces

benefits/core/templates/core/base.html, benefits/core/templates/core/includes/alert-bar.html, benefits/core/templates/core/includes/debug.html, benefits/core/templates/core/includes/nocookies.html, benefits/core/templates/core/includes/noscript.html, benefits/locale/en/LC_MESSAGES/django.po, benefits/locale/es/LC_MESSAGES/django.po, benefits/settings.py, benefits/urls.py
Display warnings to end-users with either JavaScript or cookies disabled. Fix CSRF failure error template.
Closes #24.
=> UI warnings

.pyup.yml
This should make it easier to selectively apply or time certain updates over others.
=> Don't batch pyup.io changes

benefits/core/admin.py, benefits/core/migrations/0001_initial.py, benefits/core/models.py, benefits/core/viewmodels.py, benefits/enrollment/api.py, benefits/enrollment/templates/enrollment/index.html, benefits/enrollment/views.py, localhost/data/client.json
Previously this object was called `core.models.BenefitsProvider`.
Renaming to `PaymentProcessor` as this is a more accurate reflection of the role the entity plays.
=> Refactor core.models.PaymentProcessor naming

benefits/core/analytics.py, benefits/core/session.py, benefits/enrollment/views.py
To help streamline the logs and elevate more important info
* downgrade basic info logs to `DEBUG`
* upgrade the message about the `card_tokenize_url` entry to `WARN`
=> Update log message levels

.gitignore
Adds `__pycache__` directory to .gitignore
=> chore(gitignore): add __pycache__ directory to gitignore

docs/README.md
Closes #193 
There was one link to update
=> Update links to new API docs

benefits/settings.py
=> Secure Django's language cookie

.aws/ecs-task.json, bin/init.sh
Using a single init file is easier for now.
=> Revert initialization changes

docs/deployment/release.md
Initial write-up of the current process to make a new release.
Does this make sense? Any clarifications needed? Changes to the process?
=> Document steps to make a new release

benefits/__init__.py
Bumping the version number and prepping for the next release.
=> Prepare release 2021.12.1

benefits/core/templates/core/payment-options.html, benefits/locale/en/LC_MESSAGES/django.po, benefits/locale/es/LC_MESSAGES/django.po
=> Fix: payment options content

.github/workflows/pre-commit.yml, .pre-commit-config.yaml, benefits/__init__.py, docs/deployment/release.md
Bumping the version number and prepping for the next release.
=> Prepare release 2022.01.1

benefits/core/migrations/0001_initial.py, benefits/core/models.py, benefits/eligibility/api.py, benefits/eligibility/views.py, fixtures/04_transitagency.json
Closes #320 
Made all the changes mentioned in #320. Also changed `TransitAgency.types_to_verify` to take in a verifier.
Manually tested to make sure that the eligibility flow still works. ✔️
=> TransitAgency model allows for multiple verifiers

benefits/core/templates/core/base.html, benefits/core/templates/core/help.html, benefits/core/templates/core/includes/nocookies.html, benefits/core/templates/core/includes/noscript.html, benefits/core/templates/core/payment-options.html, benefits/core/viewmodels.py, benefits/core/views.py, benefits/eligibility/forms.py, benefits/eligibility/views.py, benefits/enrollment/templates/enrollment/success.html, benefits/enrollment/views.py, benefits/locale/en/LC_MESSAGES/django.po, benefits/locale/es/LC_MESSAGES/django.po
=> Chore: normalize msgids in language files

benefits/core/models.py, benefits/core/session.py, benefits/core/views.py, benefits/eligibility/views.py
=> Feat: track verifier in session

benefits/core/middleware.py, benefits/eligibility/views.py
=> Feat: middleware to require verifier in session

benefits/core/session.py, benefits/eligibility/views.py
=> Fix: eligibility reset

.pre-commit-config.yaml
=> Fix: update black in pre-commit

benefits/core/templates/core/page.html, benefits/core/viewmodels.py, benefits/core/views.py, benefits/eligibility/views.py
=> Feat: show layout image by default

benefits/static/css/styles.css
fixes footer list item alignment on mobile screen sizes
=> fix(visual bug): better align footer text #412

docs/.pages, docs/configuration/.pages, docs/configuration/README.md, docs/configuration/content-security-policy.md, docs/configuration/environment-variables.md, docs/configuration/fixtures.md, docs/configuration/oauth.md, docs/configuration/rate-limit.md, docs/configuration/recaptcha.md
Closes #420.
Closes #421.
Closes #422.
Closes #423.
Definitely room for improvement and expansion, but hopefully this sets up a good starting place.
=> Docs: configuration, environment variables, fixtures

benefits/locale/en/LC_MESSAGES/django.po, benefits/locale/es/LC_MESSAGES/django.po
Closes #433 
Updates content title english
Spanish translation unavailable therefore the following text has been placed in its stead.
"TODO: Cal-ITP Benefits makes it easy to use your public transit discount everytime you ride."
=> feat: updates content title

benefits/oauth/views.py
* the configured OAUTH_CLIENT_NAME
* the app's redirect_uri for the authorize_redirect call
* whether or not the access token is authorized
Closes #440
=> Chore: add log statements for OAuth flow

benefits/core/views.py, benefits/locale/en/LC_MESSAGES/django.po, benefits/locale/es/LC_MESSAGES/django.po, benefits/static/css/styles.css
Closes #432
| Before (`dev` branch)  | After |
| ------- | ------ |
| ![image](https://user-images.githubusercontent.com/25497886/163873353-7e194914-7f42-4c17-a8e4-ed937becfbd0.png) | ![image](https://user-images.githubusercontent.com/25497886/163873259-03835c74-22ad-4d26-a703-ac1d4c3839f8.png) |
**UI tests still pass**
=> Refactor: remove paragraphs from index

.devcontainer/Dockerfile, .vscode/settings.json, docs/getting-started/testing.md, pyproject.toml, tests/pytest/requirements.txt, tests/pytest/test_session.py
This was started a little while ago by @angela-tran; creating a pull request to increase visibility.
=> Chore: set up app-level tests

.github/workflows/labeler-actions.yml
Similar to #482 but for the `actions` label
=> Feat: workflow to label PRs that touch actions

benefits/core/analytics.py, benefits/eligibility/analytics.py, benefits/oauth/analytics.py, benefits/oauth/views.py, tests/pytest/oauth/test_views.py
=> Feat: add analytics for auth flows

benefits/core/analytics.py, benefits/eligibility/analytics.py, benefits/oauth/analytics.py, benefits/oauth/views.py, tests/pytest/oauth/test_views.py
=> Feat: anchor link analytics

.devcontainer/compose.yml
This image works to start the server and test verification locally.
Temporary and quick fix while we figure out #468
=> Fix: point to working server image

benefits/core/templates/core/agency_index.html, benefits/core/viewmodels.py, benefits/core/views.py, benefits/locale/en/LC_MESSAGES/django.po, benefits/locale/es/LC_MESSAGES/django.po, tests/cypress/specs/ui/index.spec.js
Related to #522. Covers `core:index` and `core:agency_index`
=> Update English copy: core

docs/README.md, docs/deployment/README.md, tests/cypress/package-lock.json
Pulling in from [hosting overview](https://docs.google.com/document/d/1DXBB3sw8tOtp0jdLDzjEQq-hkUx0DRPyIZU9PfnrztI/edit#).
=> docs: expand on architecture docs

.github/ISSUE_TEMPLATE/design.md
=> Chore: issue template for design tasks

.devcontainer/devcontainer.json
[Git Graph](https://marketplace.visualstudio.com/items?itemName=mhutchie.git-graph) is a useful GUI tool for working with Git. Let's add it to our devcontainer! I would love to add it to [eligibility-server](https://github.com/cal-itp/eligibility-server) and [eligibility-api](https://github.com/cal-itp/eligibility-api) as well.
=> Devcontainer: add Git Graph extension

.github/workflows/deploy-dev.yml
=> Feat: configure Azure deploy for dev env

.github/workflows/deploy-dev.yml, benefits/core/templates/core/base.html
Azure will grab the image from GHCR
=> Fix: remove deploy to Azure web apps

tests/pytest/run.sh
Fixes #648 
See notes on the issue itself for more context.
=> Fix(ci): use importlib as import mode

docs/deployment/azure.md, mkdocs.yml
Includes a couple starter diagrams for the new deployment. Part of https://github.com/cal-itp/benefits/issues/537.
Open to ideas about how to represent that "exploded" view of the second diagram in relation to the first.
=> Add Azure page

benefits/core/templates/core/base.html
=> Link to CDT privacy policy

benefits/core/templates/core/page.html, benefits/eligibility/templates/eligibility/start.html, benefits/eligibility/views.py, benefits/locale/en/LC_MESSAGES/django.po, benefits/locale/es/LC_MESSAGES/django.po, benefits/static/css/styles.css, tests/cypress/specs/ui/eligibility-auth.cy.js, tests/cypress/specs/ui/eligibility-no-auth.cy.js
closes #654 
One-column layout for Eligibility Start
Note: Photo dimensions/sizing will be improved in next PR. Login.gov button will be perfected in the next PR.
=> IAL2 Login.gov: New Eligibility Start page design

benefits/static/css/styles.css
closes one bullet point from https://github.com/cal-itp/benefits/issues/689#issuecomment-1156779411
=> Fix: New footer link color is #73B3E7

.github/workflows/labeler-back-end.yml, .github/workflows/labeler-docker.yml, .github/workflows/labeler-front-end.yml, .github/workflows/labeler-i18n.yml
* `front-end`
* `back-end`
* `docker`
* `i18n`
=> CI: add a few more PR labelers

README.md
For anyone landing on the repo
=> Docs: improve readme description

benefits/locale/en/LC_MESSAGES/django.po, benefits/locale/es/LC_MESSAGES/django.po
=> Chore: remove unused language file entries

terraform/app_service.tf
Closes https://github.com/cal-itp/benefits/issues/735.
=> document the deployment slot settings

terraform/app_service.tf
Removes a bunch that were auto-populated but aren't needed, and adds a couple that should be slot-specific.
=> update list of deployment slot settings

benefits/logging.py, benefits/settings.py
Trying to figure out if it's picking up the environment variable.
=> chore: add debugging messages around Azure configuration

.devcontainer/devcontainer.json
Makes creating/editing diagrams slightly easier.
https://marketplace.visualstudio.com/items?itemName=bpruitt-goddard.mermaid-markdown-syntax-highlighting
=> add Mermaid syntax highlighting plugin

.pre-commit-config.yaml, benefits/core/templates/core/agency_index.html, benefits/core/templates/core/base.html, benefits/core/templates/core/includes/alert-bar.html, benefits/core/templates/core/includes/alert.html, benefits/core/templates/core/includes/analytics.html, benefits/core/templates/core/includes/debug.html, benefits/core/templates/core/includes/form.html, benefits/core/templates/core/includes/icon.html, benefits/core/templates/core/includes/lang-selector.html, benefits/core/templates/core/includes/nocookies.html, benefits/core/templates/core/includes/noscript.html, benefits/core/templates/core/page.html, benefits/core/templates/core/widgets/radio_select.html, benefits/core/templates/core/widgets/radio_select_option.html, benefits/eligibility/templates/eligibility/start.html, benefits/enrollment/templates/enrollment/index.html
#188 
Adds https://github.com/rtts/djhtml to pre-commit
This extension will indent HTML files.
To test this locally:
```
$ pip install djhtml
$ djhtml -i template.html
```
To see changes.
=> chore(pre-commit): add DJHTML pre-commit for indenting html template files

.vscode/settings.json
Turn this setting on by default for all languages.
=> Fix: format on save in devcontainer

Dockerfile
Building the client image from scratch was failing on my machine.
=> chore: fix Docker build

terraform/.terraform.lock.hcl, terraform/app_service.tf, terraform/main.tf, terraform/network.tf
Brings in some bug fixes, etc.
=> upgrade Azure Terraform provider

docs/.pages, docs/students.md
Closes https://calitp.teamwork.com/index.cfm#/tasks/26219542.
=> add page on student discount use case

mkdocs.yml
Ha, didn't realize we were working on this at the same time.
Mermaid is already loaded by MkDocs.
=> chore: remove extraneous loading of Mermaid

terraform/network.tf
Testing delegation for creation of Environment.
=> chore: switch to new subnet

terraform/app_service.tf, terraform/network.tf
=> Revert "chore: switch to new subnet"

terraform/app_service.tf
Closes #686 
Changes already made manually in the UI.
=> Terraform: add slot storage mounts

tests/pytest/core/test_models.py
Closes #723.
Brings coverage of `benefits/core/models.py` to `100%`.
=> Model tests

appcontainer/Dockerfile
Fixes #839
Temporarily on top of #838 to get the fix there.
=> Fix: Docker migrations permissions

.devcontainer/server/.env.server, .devcontainer/server/data.csv, compose.yml
This PR resurrects changes from #468 since the TODO has been resolved by cal-itp/eligibility-server#101.
I rebased the commit and made some fixes to account for all the work that's gone into `dev`.
=> Fix: configure and use latest test eligibility server

benefits/enrollment/analytics.py, benefits/enrollment/views.py, tests/pytest/enrollment/test_views.py
closes #869 
Sends `completed enrollment` event
=> Analytics - Send event when user successfully completes payment processor enrollment

docs/README.md, docs/deployment/infrastructure.md, docs/use-cases/seniors.md
Also removed a now-duplicate process diagram for student enrollment.
=> update references to the Identity Gateway

.github/ISSUE_TEMPLATE/release.yml, .github/workflows/labeler-migrations.yml
* Adds reminder steps to the checklist to update data migrations
* Adds labeler workflow that labels PRs that may require data migrations updates
=> Chore: data migration reminders

docs/development/.pages
Just noticed that it's an important thing that isn't mentioned in the docs, so added a link under Development. Happy to move the link or embed somewhere else.
=> link to Style Guide

benefits/core/templates/core/agency_index.html, benefits/core/templates/core/includes/media-list.html, benefits/eligibility/templates/eligibility/start.html, benefits/static/css/styles.css
closes #934 
Note: This PR does not do https://github.com/cal-itp/benefits/issues/996
- Redesign the Media List on Mobile to match Figma: Delete a lot of previously-required media list CSS styles for Mobile. Rewrite the CSS to be mobile first. Set as much alignment with Bootstrap classes. Use CSS Variables set responsively to change the Icon Size, Icon Margin.
- Update Media List includes and Eligibility Start Media List (The code is the same now)
- Creates a `p-sm` utility class: Paragraph size body text up to small width, and then for Desktop - turns into whatever it actually is. An `h3` with a `p-sm` class will be `p` up to small, and then `h3` after that. 
Media List is an unstyled unordered list of Media Items, with an optional Media List Title at the top. Media List Title is …
=> Refactor: Media List on Mobile & Desktop

docs/use-cases/seniors.md
=> reduce size of senior success flow GIF

benefits/static/css/styles.css
Follow up to #1025
Make the style mobile-first since we want the same behavior across mobile/desktop
=> Fix: remove previous button hover background

benefits/core/templates/core/base.html, benefits/core/templates/core/includes/icon.html, benefits/core/templates/core/logged_out.html, benefits/core/views.py, benefits/enrollment/templates/enrollment/success.html, benefits/locale/en/LC_MESSAGES/django.po, benefits/locale/es/LC_MESSAGES/django.po, benefits/static/css/styles.css
=> Style: enrollment success

docs/deployment/infrastructure.md, terraform/app_service.tf, terraform/key_vault.tf, terraform/storage.tf
Split out from https://github.com/cal-itp/benefits/pull/1074. Closes https://github.com/cal-itp/benefits/issues/829.
=> prevent destruction of Terraform resources containing secrets

benefits/core/templates/core/base.html, benefits/core/templates/core/page.html, benefits/core/viewmodels.py, benefits/locale/en/LC_MESSAGES/django.po, benefits/locale/es/LC_MESSAGES/django.po, tests/pytest/core/test_viewmodels.py
Closes #1080 
- Cleaned up extra spaces
- Change to new title format
=> Fix: title whitespace

benefits/core/templates/core/includes/form.html, benefits/static/css/styles.css
Closes #948
Rebased @machikoyasuda's work from #1043 on the new reCAPTCHA fixes. 
Also fixed the ordering of the jQuery function calls to ensure the `disabled` state is applied to the _button_ and not the _text_ element inside.
=> Feat: spinner on Check Status button

docs/deployment/README.md
Closes #168, a ticket I opened almost exactly 1 year ago!!!
=> Docs: link to GHCR images

.devcontainer/server/settings.py
Corresponds to cal-itp/eligibility-server#165
=> Devcontainer: update sample server settings

benefits/__init__.py
Bump version to 2022.11.1 for 2022.11.1 release.
Part of #1124
=> Prep release 2022.11.1

terraform/app_service.tf, terraform/key_vault.tf, terraform/variables.tf
Part of https://github.com/cal-itp/benefits/issues/704.
Import the:
=> chore(Terraform): manage production certitificate binding in code

docs/deployment/infrastructure.md
Split out from https://github.com/cal-itp/benefits/pull/1074.
=> docs: elaborate on what is managed by DevSecOps team

docs/configuration/environment-variables.md, docs/deployment/infrastructure.md, docs/deployment/troubleshooting.md
Closes https://github.com/cal-itp/benefits/issues/960.
Put that on a new Troubleshooting page, and moved the Monitoring and Logs information in there as well.
=> docs(Terraform): add information about locking

docs/development/.pages, docs/development/i18n.md
=> Docs: workflow for Django message files

benefits/__init__.py
For https://github.com/cal-itp/benefits/issues/1167.
=> Prep 2022.12.1 release

terraform/app_service.tf
Fixes https://github.com/cal-itp/benefits/issues/1142. Holding on merging due to https://github.com/cal-itp/benefits/issues/1142#issuecomment-1363117266.
=> fix(Terraform): downgrade App Service plan

appcontainer/requirements.txt
=> Chore: use eligibility-api package from PyPI

benefits/__init__.py
Release will happen in February.
Updated #1220
=> Chore: bump version

docs/tests/README.md
When viewing the diff, I suggest [ignoring whitespace](https://github.com/cal-itp/benefits/pull/1299/files?w=1).
=> Fix Cypress setup instructions

appcontainer/nginx.conf, benefits/__init__.py, tests/cypress/specs/scrapers.cy.js
=> Deploy to test

benefits/core/session.py, benefits/eligibility/views.py, benefits/oauth/client.py, tests/pytest/core/test_session.py, tests/pytest/eligibility/test_views.py, tests/pytest/oauth/test_client.py, tests/pytest/oauth/test_views.py
Closes #1457 
Supersedes #1465
=> Feat: reset OAuth for new flows

benefits/eligibility/templates/eligibility/start.html, benefits/eligibility/templates/eligibility/start__login_gov.html, benefits/eligibility/templates/eligibility/start__mst_courtesy_card.html, benefits/eligibility/templates/eligibility/start__veteran.html, benefits/locale/en/LC_MESSAGES/django.po, benefits/locale/es/LC_MESSAGES/django.po
Closes #1474 
| | Screenshot |
| --- | --- | 
| Previous (dev-benefits) | ![image](https://github.com/cal-itp/benefits/assets/25497886/a0950f69-e691-4406-8d1d-57e81facf409) | 
| This PR | ![image](https://github.com/cal-itp/benefits/assets/25497886/d7b5bf17-8120-42a1-b9de-b3b7bc7f792b) | 
| Figma | ![image](https://github.com/cal-itp/benefits/assets/25497886/447f4148-e264-488c-808f-76c7c02e7c5e) |
=> Chore: eligibility start copy

benefits/static/css/styles.css
fix #1591
- Adds body letter-spacing, increase font-weight from 500 to 700
=> Footer: Fix type (letter-spacing, font-weight)

benefits/locale/en/LC_MESSAGES/django.po, benefits/locale/es/LC_MESSAGES/django.po
=> fix(copy): Seguro Social, not seguro social

.devcontainer/devcontainer.json, .vscode/settings.json, tests/pytest/core/test_models.py, tests/pytest/run.sh
Cleans up some deprecation notices (no longer just warnings) in the devcontainer.
=> Chore: clean up devcontainer

terraform/app_service.tf, terraform/storage.tf
In the spirit of trying something; part of #1773
=> Feat: create and mount Azure file share

terraform/app_service.tf
Quick follow up to #1779 while testing for #1783 
Closes #1789
=> Fix: typo in secret name

docs/README.md
We use the "ID Proofed" OIDC connection, which is not yet fully IAL2-compliant.
https://developers.login.gov/overview/
> Identity proofed accounts require the user to complete additional steps to verify their identity in addition to the Multifactor Authentication (MFA). Login.gov continues to work toward achieving certification of compliance with [NIST’s IAL2](https://pages.nist.gov/800-63-3-Implementation-Resources/63A/ial2remote/) standard from a third-party assessment organization.
=> Docs: fix small typo

docs/README.md
Because the SBMTD Mobility Pass enrollment pathway is available in production, I updates adoption status from "test" to "Live."
=> docs: README.md > SBMTD Mobility Pass status

docs/product-and-design/.pages
This page currently links to a broken Figma file. I propose we remove it and bring it back when we have relevant content.
=> Update .pages remove design style guide page

docs/enrollment-pathways/README.md
I used custom styling for the roadmap timeline diagram. mkdocs is not displaying it correctly when published. I've removed the code that constitutes the directive to see if it mkdocs renders the diagram as expected.
=> Update README.md removed directive from Mermaid chart

.github/workflows/mkdocs.yml
=> Fix: check for existing preview comment before adding one

.github/dependabot.yml, docs/requirements.txt, mkdocs.yml
=> Docs: pin key requirements, fix extension syntax

pyproject.toml
=> Chore: use calitp-littlepay from PyPI

docs/enrollment-pathways/README.md
- Updated status labels for Q1, Q2, and Q3.
- Moved low-income milestone forward to Q2.
- Rearanged the order of milestones in Q2.
=> Updates to Cal-ITP Benefits product roadmap

docs/enrollment-pathways/README.md
- Commented out our milestone to enhance the Veterans pathway. The timeline for additional attributes to verify Veteran eligibility is unclear.
- Added milestone to capture effort to improve UX for the agency card flow.
- Updated the name of the SBMTD Mobility Pass to Reduced Fare Mobility ID.
- Moved diagram styling to the end of the code block, as I was seeing a syntax error in another editor when it was placed before the Mermaid diagram type.
=> Q2 Benefits product roadmap updates

benefits/core/templates/core/includes/help--calfresh.html, benefits/eligibility/templates/eligibility/includes/modal--calfresh.html, benefits/locale/en/LC_MESSAGES/django.po, benefits/locale/es/LC_MESSAGES/django.po
Part of #1941 
Rows 179 - 187 in the [copy spreadsheet, `forTranslation` tab](https://docs.google.com/spreadsheets/d/1_Gi_YbJr4ZuXCOsnOWaewvHqUO1nC1nKqiVDHvw0118/edit#gid=610152150)
=> Feat: CalFresh Spanish updates

docs/enrollment-pathways/README.md
- added Improved UX for application error states milestone
- shifted milestones for the Benefits admin tool to later in the year.
=> Roadmap revisions

compose.yml
=> Chore: remove obsolete Compose version key

docs/enrollment-pathways/README.md
- Moved Benefits admin (in-person eligibility) to Q3 from Q4
- Moved Medicare cardholder enrollments to Q4 from Q3
- Changed references to "payment processor" to "transit processor," the more correct term.
=> Roadmap updates

docs/enrollment-pathways/README.md
- Updated status labels for each quarter in 2024
- Moved low-income enrollment pathway to Q3
- Moved Admin (in-person eligibility verification) to Q4
- Added eligibility verification for disabled Veterans (new API) to Q4
=> Q3 Benefits Roadmap Update

docs/README.md
- changed status of the low-income enrollment pathway from "in development" to "Live"
- link to release notes
- added low-income enrollment pathway to agency table
=> Update Benefits Project Overview

benefits/core/migrations/local_fixtures.json
=> Chore: update local fixtures with sample CalFresh AuthProvider

docs/enrollment-pathways/README.md
- Due to a change in priority for the admin interface, I've moved in-person eligibility verification back to Q3 and agency configuration into Q4.
=> Roadmap update

tests/pytest/test_admin.py
Closes #2321
This PR refactors the test for `BenefitsAdminSite` to use a `client` to `.get` the path for the view function instead of calling the view function directly.
=> Refactor: use client to test the BenefitsAdminSite view

docs/README.md
- Changed status of the Medicare cardholder enrollment pathway from"in development" to "code complete."
- For alignment, updated the status of the low-income pathway to "code complete" as it is deployed but we await completion of contracting to make it available to agencies.
=> Status update for Medicare cardholders

docs/enrollment-pathways/README.md
- Changed Q3 label to "Complete"
- Changed Q3 label to "Now"
=> End of Q3 roadmap updates

docs/README.md
=> Update status of low-income pathway

docs/README.md
- Added Nevada County Connects since they are now live in test
- Added Medicare cardholders column
=> Updates to Agency Adoption table

docs/README.md
- older adults = live
- Veterans = live
- agency is now live in prod
=> Updated status for SacRT

docs/enrollment-pathways/medicare-cardholders.md
- Added a Demonstration section
- Added an iframe embed of the video walkthrough on YouTube.
=> Adding video walkthrough to Medicare cardholder use case

docs/README.md
- added Medicare cardholders as LIVE for MST
- changed column order in adoption table (low-income last)
- changed Medicare cardholders to LIVE instead of CODE COMPLETE
- added Nevada county target launch date
- explored ordering the agency list by alpha instead of by launch date
=> Updating agency adoption table

docs/enrollment-pathways/README.md
- simplified mermaid code that defines diagram styling
- moved 'Enhanced Veteran eligibility checks' to Q1 2025 as we now have guidance on API access from VA.gov that may allow us to implement earlier.
=> Roadmap adjustments

docs/enrollment-pathways/README.md, docs/styles/theme.css, mkdocs.yml
=> Fix: Docs site theme and Roadmap style

terraform/app_service.tf
=> Chore(infra): allow reCAPTCHA settings on dev environment

docs/product-and-design/newsletter-archive.md
- added link to dec 2024 newsletter
- added section for 2025 newsletters (commented out)
=> docs: adding link to dec 2024 update

benefits/settings.py
=> Fix: add google recaptcha to connect-src CSP directives

docs/README.md
- updated date for Nevada county launch
- added Medicare cardholder pathway for SBMTD
=> docs: updates-to-agency-adoption-table

docs/enrollment-pathways/low-income.md
- adding YouTube video walkthrough to low-income use case
=> docs: embed calfresh video walkthrough

docs/enrollment-pathways/README.md
- moved enhanced eligibility checks for veterans to Q2
- moved single eligibility check to H2
- modified order of Q2 items
=> docs: roadmap updates

docs/README.md
- removed target and test language
- added check icons for live pathways
=> docs: marking nevada county live

docs/enrollment-pathways/medicare-cardholders.md
- added eligibility check attributes in notes on sequence diagram
=> docs: update to mermaid diagram

docs/README.md
- added veterans enrollment pathway for nevada county
- changed column order for enrollment pathways. instead of using the order in which they were released, they are now ordered by level of adoption.
- updated column heading to for veterans to match the benefit option label in the application
=> docs: changes to agency adoption table

bin/build.sh
=> Chore: re-enable BuildKit for Mac devs

benefits/templates/admin/agency-dashboard-index.html
=> Refactor: update copy on card for in-person enrollment

docs/README.md, docs/enrollment-pathways/README.md
- added VCTC to table
- slight changes in naming to align with style guide standards
=> docs: adding VCTC + roadmap updates

benefits/in_person/templates/in_person/enrollment/retry.html
=> Fix: update copy for in-person enrollment card error

.github/workflows/add-to-project-dependabot.yml, .github/workflows/add-to-project-issues.yml
Here's an example of this workflow running: https://github.com/cal-itp/test-repo/actions/runs/14864250446
And the issue on USB: <https://github.com/orgs/compilerla/projects/6/views/7?pane=issue&itemId=109328299&issue=cal-itp%7Ctest-repo%7C4>
=> CI: Unified Sprint Board automation

benefits/core/mixins.py, tests/pytest/core/test_mixins.py
=> Feat: CBV mixin enforces eligible sessions

tests/pytest/enrollment_littlepay/test_views.py
Closes #2937 
Follow-up to #2930
=> Chore: Littlepay `IndexView` test follow-up

docs/enrollment-pathways/README.md
Updating roadmap through the end of 2025 based on our current perspective.
=> End of Q2 2025 roadmap update

benefits/enrollment_switchio/enrollment.py, benefits/enrollment_switchio/views.py, tests/pytest/conftest.py, tests/pytest/enrollment_switchio/test_enrollment.py, tests/pytest/enrollment_switchio/test_views.py
Part of #2993 
This PR implements non-expiring discounts.
The fixtures in LastPass have been updated to work for Switchio, so you can use those to test this PR out. Let me know if you have any trouble :pray:
=> Feat: Switchio enrollment logic - non-expiring discounts

docs/development/application-logic.md
=> Docs: diagram for Switchio enrollment logic

benefits/core/context_processors.py, benefits/settings.py, docs/configuration/environment-variables.md, terraform/app_service.tf, tests/pytest/core/test_context_processors.py
=> Chore: cleanup cardtypes flag

.pre-commit-config.yaml, docs/development/docker-dynamic-ports.md, docs/development/test-server.md, docs/getting-started/README.md
this PR is a reboot of #3060 (and #3159)
=> chore: fix a few typos in the docs and update djlint github url

docs/deployment/README.md, docs/getting-started/README.md
two more typo fixes. cc/ @Scotchester
=> docs: typo fixes
